==================================
  TODOs for fix-cmake
==================================

- hide most advanced variables

- GTK
    - GTK3 is still not the default?
    - how to tell find_path() to look
      in any "lib" directory for glibconfig.h?

- Curses
    - FindCurses.cmake should look for libformw when CURSES_NEED_WIDE
      is true. Report to upstream?

==================================
  Out of scope TODOs for fix-cmake
==================================