############################################################################
#                                                                          #
#  ettercap -- etter.finger.mac -- passive NIC vendor database             #
#                                                                          #
#  Copyright (C) 2001-2003  ALoR & NaGA                                    #
#                                                                          #
#  This program is free software; you can redistribute it and/or modify    #
#  it under the terms of the GNU General Public License as published by    #
#  the Free Software Foundation; either version 2 of the License, or       #
#  (at your option) any later version.                                     #
#                                                                          #
############################################################################
#                                                                          #
#  Version         : $Revision: 1.3 $                        
#  Last updated on : $Date: 2003/07/10 20:25:23 $                          #
#  Total entries   : 6311                                                  #
#                                                                          #
############################################################################

00:00:00  Xerox Corporation
00:00:01  Xerox Corporation
00:00:02  Xerox Corporation
00:00:03  Xerox Corporation
00:00:04  Xerox Corporation
00:00:05  Xerox Corporation
00:00:06  Xerox Corporation
00:00:07  Xerox Corporation
00:00:08  Xerox Corporation
00:00:09  Xerox Corporation
00:00:0A  Omron Tateisi Electronics Co.
00:00:0B  Matrix Corporation
00:00:0C  Cisco Systems, Inc.
00:00:0D  Fibronics Ltd.
00:00:0E  Fujitsu Limited
00:00:0F  Next, Inc.
00:00:10  Sytek Inc.
00:00:11  Normerel Systemes
00:00:12  Information Technology Limited
00:00:13  Camex
00:00:14  Netronix
00:00:15  Datapoint Corporation
00:00:16  Du Pont Pixel Systems     .
00:00:17  Private
00:00:18  Webster Computer Corporation
00:00:19  Applied Dynamics International
00:00:1A  Advanced Micro Devices
00:00:1B  Novell Inc.
00:00:1C  Bell Technologies
00:00:1D  Cabletron Systems, Inc.
00:00:1E  Telsist Industria Electronica
00:00:1F  Telco Systems, Inc.
00:00:20  Dataindustrier Diab Ab
00:00:21  Sureman Comp. & Commun. Corp.
00:00:22  Visual Technology Inc.
00:00:23  Abb Industrial Systems Ab
00:00:24  Connect As
00:00:25  Ramtek Corp.
00:00:26  Sha-ken Co., Ltd.
00:00:27  Japan Radio Company
00:00:28  Prodigy Systems Corporation
00:00:29  Imc Networks Corp.
00:00:2A  Trw - Sedd/inp
00:00:2B  Crisp Automation, Inc
00:00:2C  Autotote Limited
00:00:2D  Chromatics Inc
00:00:2E  Societe Evira
00:00:2F  Timeplex Inc.
00:00:30  Vg Laboratory Systems Ltd
00:00:31  Qpsx Communications Pty Ltd
00:00:32  Marconi Plc
00:00:33  Egan Machinery Company
00:00:34  Network Resources Corporation
00:00:35  Spectragraphics Corporation
00:00:36  Atari Corporation
00:00:37  Oxford Metrics Limited
00:00:38  Css Labs
00:00:39  Toshiba Corporation
00:00:3A  Chyron Corporation
00:00:3B  I Controls, Inc.
00:00:3C  Auspex Systems Inc.
00:00:3D  Unisys
00:00:3E  Simpact
00:00:3F  Syntrex, Inc.
00:00:40  Applicon, Inc.
00:00:41  Ice Corporation
00:00:42  Metier Management Systems Ltd.
00:00:43  Micro Technology
00:00:44  Castelle Corporation
00:00:45  Ford Aerospace & Comm. Corp.
00:00:46  Olivetti North America
00:00:47  Nicolet Instruments Corp.
00:00:48  Seiko Epson Corporation
00:00:49  Apricot Computers, Ltd
00:00:4A  Adc Codenoll Technology Corp.
00:00:4B  Icl Data Oy
00:00:4C  Nec Corporation
00:00:4D  Dci Corporation
00:00:4E  Ampex Corporation
00:00:4F  Logicraft, Inc.
00:00:50  Radisys Corporation
00:00:51  Hob Electronic Gmbh & Co. Kg
00:00:52  Intrusion.com, Inc.
00:00:53  Compucorp
00:00:54  Modicon, Inc.
00:00:55  Commissariat A L`energie Atom.
00:00:56  Dr. B. Struck
00:00:57  Scitex Corporation Ltd.
00:00:58  Racore Computer Products Inc.
00:00:59  Hellige Gmbh
00:00:5A  Syskonnect Gmbh
00:00:5B  Eltec Elektronik Ag
00:00:5C  Telematics International Inc.
00:00:5D  Cs Telecom
00:00:5E  Usc Information Sciences Inst
00:00:5F  Sumitomo Electric Ind., Ltd.
00:00:60  Kontron Elektronik Gmbh
00:00:61  Gateway Communications
00:00:62  Bull Hn Information Systems
00:00:63  Dr.ing.seufert Gmbh
00:00:64  Yokogawa Digital Computer Corp
00:00:65  Network Associates, Inc.
00:00:66  Talaris Systems, Inc.
00:00:67  Soft * Rite, Inc.
00:00:68  Rosemount Controls
00:00:69  Concord Communications Inc
00:00:6A  Computer Consoles Inc.
00:00:6B  Silicon Graphics Inc./mips
00:00:6C  Private
00:00:6D  Cray Communications, Ltd.
00:00:6E  Artisoft, Inc.
00:00:6F  Madge Networks Ltd.
00:00:70  Hcl Limited
00:00:71  Adra Systems Inc.
00:00:72  Miniware Technology
00:00:73  Siecor Corporation
00:00:74  Ricoh Company Ltd.
00:00:75  Nortel Networks
00:00:76  Abekas Video System
00:00:77  Interphase Corporation
00:00:78  Labtam Limited
00:00:79  Networth Incorporated
00:00:7A  Dana Computer Inc.
00:00:7B  Research Machines
00:00:7C  Ampere Incorporated
00:00:7D  Sun Microsystems, Inc.
00:00:7E  Clustrix Corporation
00:00:7F  Linotype-hell Ag
00:00:80  Cray Communications A/s
00:00:81  Bay Networks
00:00:82  Lectra Systemes Sa
00:00:83  Tadpole Technology Plc
00:00:84  Supernet
00:00:85  Canon Inc.
00:00:86  Megahertz Corporation
00:00:87  Hitachi, Ltd.
00:00:88  Computer Network Tech. Corp.
00:00:89  Cayman Systems Inc.
00:00:8A  Datahouse Information Systems
00:00:8B  Infotron
00:00:8C  Alloy Computer Products (australia) Pty Ltd
00:00:8D  Verdix Corporation
00:00:8E  Solbourne Computer, Inc.
00:00:8F  Raytheon Company
00:00:90  Microcom
00:00:91  Anritsu Corporation
00:00:92  Cogent Data Technologies
00:00:93  Proteon Inc.
00:00:94  Asante Technologies
00:00:95  Sony Tektronix Corp.
00:00:96  Marconi Electronics Ltd.
00:00:97  Epoch Systems
00:00:98  Crosscomm Corporation
00:00:99  Mtx, Inc.
00:00:9A  Rc Computer A/s
00:00:9B  Information International, Inc
00:00:9C  Rolm Mil-spec Computers
00:00:9D  Locus Computing Corporation
00:00:9E  Marli S.a.
00:00:9F  Ameristar Technologies Inc.
00:00:A0  Tokyo Sanyo Electric Co. Ltd.
00:00:A1  Marquette Electric Co.
00:00:A2  Bay Networks
00:00:A3  Network Application Technology
00:00:A4  Acorn Computers Limited
00:00:A5  Compatible Systems Corp.
00:00:A6  Network General Corporation
00:00:A7  Network Computing Devices Inc.
00:00:A8  Stratus Computer Inc.
00:00:A9  Network Systems Corp.
00:00:AA  Xerox Corporation
00:00:AB  Logic Modeling Corporation
00:00:AC  Conware Computer Consulting
00:00:AD  Bruker Instruments Inc.
00:00:AE  Dassault Electronique
00:00:AF  Nuclear Data Instrumentation
00:00:B0  Rnd-rad Network Devices
00:00:B1  Alpha Microsystems Inc.
00:00:B2  Televideo Systems, Inc.
00:00:B3  Cimlinc Incorporated
00:00:B4  Edimax Computer Company
00:00:B5  Datability Software Sys. Inc.
00:00:B6  Micro-matic Research
00:00:B7  Dove Computer Corporation
00:00:B8  Seikosha Co., Ltd.
00:00:B9  Mcdonnell Douglas Computer Sys
00:00:BA  Siig, Inc.
00:00:BB  Tri-data
00:00:BC  Allen-bradley Co. Inc.
00:00:BD  Mitsubishi Cable Company
00:00:BE  The Nti Group
00:00:BF  Symmetric Computer Systems
00:00:C0  Western Digital Corporation
00:00:C1  Madge Networks Ltd.
00:00:C2  Information Presentation Tech.
00:00:C3  Harris Corp Computer Sys Div
00:00:C4  Waters Div. Of Millipore
00:00:C5  Farallon Computing/netopia
00:00:C6  Eon Systems
00:00:C7  Arix Corporation
00:00:C8  Altos Computer Systems
00:00:C9  Emulex Corporation
00:00:CA  Applitek
00:00:CB  Compu-shack Electronic Gmbh
00:00:CC  Densan Co., Ltd.
00:00:CD  Allied Telesyn Research Ltd.
00:00:CE  Megadata Corp.
00:00:CF  Hayes Microcomputer Products
00:00:D0  Develcon Electronics Ltd.
00:00:D1  Adaptec Incorporated
00:00:D2  Sbe, Inc.
00:00:D3  Wang Laboratories Inc.
00:00:D4  Pure Data Ltd.
00:00:D5  Micrognosis International
00:00:D6  Punch Line Holding
00:00:D7  Dartmouth College
00:00:D8  Novell, Inc.
00:00:D9  Nippon Telegraph & Telephone
00:00:DA  Atex
00:00:DB  British Telecommunications Plc
00:00:DC  Hayes Microcomputer Products
00:00:DD  Tcl Incorporated
00:00:DE  Cetia
00:00:DF  Bell & Howell Pub Sys Div
00:00:E0  Quadram Corp.
00:00:E1  Grid Systems
00:00:E2  Acer Technologies Corp.
00:00:E3  Integrated Micro Products Ltd
00:00:E4  In2 Groupe Intertechnique
00:00:E5  Sigmex Ltd.
00:00:E6  Aptor Produits De Comm Indust
00:00:E7  Star Gate Technologies
00:00:E8  Accton Technology Corp.
00:00:E9  Isicad, Inc.
00:00:EA  Upnod Ab
00:00:EB  Matsushita Comm. Ind. Co. Ltd.
00:00:EC  Microprocess
00:00:ED  April
00:00:EE  Network Designers, Ltd.
00:00:EF  Kti
00:00:F0  Samsung Electronics Co., Ltd.
00:00:F1  Magna Computer Corporation
00:00:F2  Spider Communications
00:00:F3  Gandalf Data Limited
00:00:F4  Allied Telesyn International
00:00:F5  Diamond Sales Limited
00:00:F6  Applied Microsystems Corp.
00:00:F7  Youth Keep Enterprise Co Ltd
00:00:F8  Digital Equipment Corporation
00:00:F9  Quotron Systems Inc.
00:00:FA  Microsage Computer Systems Inc
00:00:FB  Rechner Zur Kommunikation
00:00:FC  Meiko
00:00:FD  High Level Hardware
00:00:FE  Annapolis Micro Systems
00:00:FF  Camtec Electronics Ltd.
00:01:00  Equip'trans
00:01:01  Private
00:01:02  3com Corporation
00:01:03  3Com 3CRWE62092A
00:01:04  Dvico Co., Ltd.
00:01:05  Beckhoff Gmbh
00:01:06  Tews Datentechnik Gmbh
00:01:07  Leiser Gmbh
00:01:08  Avlab Technology, Inc.
00:01:09  Nagano Japan Radio Co., Ltd.
00:01:0A  Cis Technology Inc.
00:01:0B  Space Cyberlink, Inc.
00:01:0C  System Talks Inc.
00:01:0D  Coreco, Inc.
00:01:0E  Bri-link Technologies Co., Ltd
00:01:0F  Nishan Systems, Inc.
00:01:10  Gotham Networks
00:01:11  Idigm Inc.
00:01:12  Shark Multimedia Inc.
00:01:13  Olympus Optical Co., Ltd.
00:01:14  Kanda Tsushin Kogyo Co., Ltd.
00:01:15  Extratech Corporation
00:01:16  Netspect Technologies, Inc.
00:01:17  Canal +
00:01:18  Ez Digital Co., Ltd.
00:01:19  Action Controls Pty. Ltd.
00:01:1A  Eeh Datalink Gmbh
00:01:1B  Unizone Technologies, Inc.
00:01:1C  Universal Talkware Corporation
00:01:1D  Centillium Communications
00:01:1E  Precidia Technologies, Inc.
00:01:1F  Rc Networks, Inc.
00:01:20  Oscilloquartz S.a.
00:01:21  Rapidstream Inc.
00:01:22  Trend Communications, Ltd.
00:01:23  Digital Electronics Corp.
00:01:24  Acer Incorporated
00:01:25  Yaesu Musen Co., Ltd.
00:01:26  Pac Labs
00:01:27  The Open Group Limited
00:01:28  Enjoyweb, Inc.
00:01:29  Dfi Inc.
00:01:2A  Telematica Sistems Inteligente
00:01:2B  Telenet Co., Ltd.
00:01:2C  Aravox Technologies, Inc.
00:01:2D  Komodo Technology
00:01:2E  Pc Partner Ltd.
00:01:2F  Twinhead International Corp
00:01:30  Extreme Networks
00:01:31  Detection Systems, Inc.
00:01:32  Dranetz - Bmi
00:01:33  Kyowa Electronic Instruments C
00:01:34  Sig Positec Systems Ag
00:01:35  Kdc Corp.
00:01:36  Cybertan Technology, Inc.
00:01:37  It Farm Corporation
00:01:38  Xavi Technologies Corp.
00:01:39  Point Multimedia Systems
00:01:3A  Shelcad Communications, Ltd.
00:01:3B  Bna Systems
00:01:3C  Tiw Systems
00:01:3D  Riscstation Ltd.
00:01:3E  Ascom Tateco Ab
00:01:3F  Neighbor World Co., Ltd.
00:01:40  Sendtek Corporation
00:01:41  Cable Print
00:01:42  Cisco Systems, Inc.
00:01:43  Cisco Systems, Inc.
00:01:44  Cereva Networks, Inc.
00:01:45  Winsystems, Inc.
00:01:46  Tesco Controls, Inc.
00:01:47  Zhone Technologies
00:01:48  X-traweb Inc.
00:01:49  T.d.t. Transfer Data Test Gmbh
00:01:4A  Sony Computer Science Labs., I
00:01:4B  Ennovate Networks, Inc.
00:01:4C  Berkeley Process Control
00:01:4D  Shin Kin Enterprises Co., Ltd
00:01:4E  Win Enterprises, Inc.
00:01:4F  Luminous Networks, Inc.
00:01:50  Gilat Communications, Ltd.
00:01:51  Ensemble Communications
00:01:52  Chromatek Inc.
00:01:53  Archtek Telecom Corporation
00:01:54  G3m Corporation
00:01:55  Promise Technology, Inc.
00:01:56  Firewiredirect.com, Inc.
00:01:57  Syswave Co., Ltd
00:01:58  Electro Industries/gauge Tech
00:01:59  S1 Corporation
00:01:5A  Digital Video Broadcasting
00:01:5B  Italtel S.p.a/rf-up-i
00:01:5C  Cadant Inc.
00:01:5D  Pirus Networks
00:01:5E  Best Technology Co., Ltd.
00:01:5F  Digital Design Gmbh
00:01:60  Elmex Co., Ltd.
00:01:61  Meta Machine Technology
00:01:62  Cygnet Technologies, Inc.
00:01:63  Cisco Systems, Inc.
00:01:64  Cisco Systems, Inc.
00:01:65  Airswitch Corporation
00:01:66  Tc Group A/s
00:01:67  Hioki E.e. Corporation
00:01:68  Vitana Corporation
00:01:69  Celestix Networks Pte Ltd.
00:01:6A  Alitec
00:01:6B  Lightchip, Inc.
00:01:6C  Foxconn
00:01:6D  Triton Network Systems
00:01:6E  Conklin Corporation
00:01:6F  Haitai Electronics Co., Ltd.
00:01:70  Ese Embedded System Engineer'g
00:01:71  Allied Data Technologies
00:01:72  Technoland Co., Ltd.
00:01:73  Jni Corporation
00:01:74  Cyberoptics Corporation
00:01:75  Radiant Communications Corp.
00:01:76  Orient Silver Enterprises
00:01:77  Edsl
00:01:78  Margi Systems, Inc.
00:01:79  Wireless Technology, Inc.
00:01:7A  Chengdu Maipu Electric Industrial Co., Ltd.
00:01:7B  Heidelberger Druckmaschinen Ag
00:01:7C  Ag-e Gmbh
00:01:7D  Thermoquest
00:01:7E  Adtek System Science Co., Ltd.
00:01:7F  Experience Music Project
00:01:80  Aopen, Inc.
00:01:81  Nortel Networks
00:01:82  Dica Technologies Ag
00:01:83  Anite Telecoms
00:01:84  Sieb & Meyer Ag
00:01:85  Aloka Co., Ltd.
00:01:86  Disch Gmbh
00:01:87  I2se Gmbh
00:01:88  Lxco Technologies Ag
00:01:89  Refraction Technology, Inc.
00:01:8A  Roi Computer Ag
00:01:8B  Netlinks Co., Ltd.
00:01:8C  Mega Vision
00:01:8D  Audesi Technologies
00:01:8E  Logitec Corporation
00:01:8F  Kenetec, Inc.
00:01:90  Smk-m
00:01:91  Syred Data Systems
00:01:92  Texas Digital Systems
00:01:93  Hanbyul Telecom Co., Ltd.
00:01:94  Capital Equipment Corporation
00:01:95  Sena Technologies, Inc.
00:01:96  Cisco Systems, Inc.
00:01:97  Cisco Systems, Inc.
00:01:98  Darim Vision
00:01:99  Heisei Electronics
00:01:9A  Leunig Gmbh
00:01:9B  Kyoto Microcomputer Co., Ltd.
00:01:9C  Jds Uniphase Inc.
00:01:9D  E-control Systems, Inc.
00:01:9E  Ess Technology, Inc.
00:01:9F  Phonex Broadband
00:01:A0  Infinilink Corporation
00:01:A1  Mag-tek, Inc.
00:01:A2  Logical Co., Ltd.
00:01:A3  Genesys Logic, Inc.
00:01:A4  Microlink Corporation
00:01:A5  Nextcomm, Inc.
00:01:A6  Scientific-atlanta Arcodan A/s
00:01:A7  Unex Technology Corporation
00:01:A8  Welltech Computer Co., Ltd.
00:01:A9  Bmw Ag
00:01:AA  Airspan Communications, Ltd.
00:01:AB  Main Street Networks
00:01:AC  Sitara Networks, Inc.
00:01:AD  Coach Master International  D.b.a. Cmi Worldwide, Inc.
00:01:AE  Trex Enterprises
00:01:AF  Motorola Computer Group
00:01:B0  Fulltek Technology Co., Ltd.
00:01:B1  General Bandwidth
00:01:B2  Digital Processing Systems, Inc.
00:01:B3  Precision Electronic Manufacturing
00:01:B4  Wayport, Inc.
00:01:B5  Turin Networks, Inc.
00:01:B6  Saejin T&m Co., Ltd.
00:01:B7  Centos, Inc.
00:01:B8  Netsensity, Inc.
00:01:B9  Skf Condition Monitoring
00:01:BA  Ic-net, Inc.
00:01:BB  Frequentis
00:01:BC  Brains Corporation
00:01:BD  Peterson Electro-musical Products, Inc.
00:01:BE  Gigalink Co., Ltd.
00:01:BF  Teleforce Co., Ltd.
00:01:C0  Compulab, Ltd.
00:01:C1  Exbit Technology
00:01:C2  Ark Research Corp.
00:01:C3  Acromag, Inc.
00:01:C4  Neowave, Inc.
00:01:C5  Simpler Networks
00:01:C6  Quarry Technologies
00:01:C7  Cisco Systems, Inc.
00:01:C8  Conrad Corp.
00:01:C9  Cisco Systems, Inc.
00:01:CA  Geocast Network Systems, Inc.
00:01:CB  Netgame, Ltd.
00:01:CC  Japan Total Design Communication Co., Ltd.
00:01:CD  Artem
00:01:CE  Custom Micro Products, Ltd.
00:01:CF  Alpha Data Parallel Systems, Ltd.
00:01:D0  Vitalpoint, Inc.
00:01:D1  Conet Communications, Inc.
00:01:D2  Macpower Peripherals, Ltd.
00:01:D3  Paxcomm, Inc.
00:01:D4  Leisure Time, Inc.
00:01:D5  Haedong Info & Comm Co., Ltd
00:01:D6  Man Roland Druckmaschinen Ag
00:01:D7  F5 Networks, Inc.
00:01:D8  Teltronics, Inc.
00:01:D9  Sigma, Inc.
00:01:DA  Wincomm Corporation
00:01:DB  Freecom Technologies Gmbh
00:01:DC  Activetelco
00:01:DD  Avail Networks
00:01:DE  Trango Systems, Inc.
00:01:DF  Isdn Communications, Ltd.
00:01:E0  Fast Systems, Inc.
00:01:E1  Kinpo Electronics, Inc.
00:01:E2  Ando Electric Corporation
00:01:E3  Siemens Ag
00:01:E4  Sitera, Inc.
00:01:E5  Supernet, Inc.
00:01:E6  Hewlett-packard Company
00:01:E7  Hewlett-packard Company
00:01:E8  Force10 Networks, Inc.
00:01:E9  Litton Marine Systems B.v.
00:01:EA  Cirilium Corp.
00:01:EB  C-com Corporation
00:01:EC  Ericsson Group
00:01:ED  Seta Corp.
00:01:EE  Comtrol Europe, Ltd.
00:01:EF  Camtel Technology Corp.
00:01:F0  Tridium, Inc.
00:01:F1  Innovative Concepts, Inc.
00:01:F2  Mark Of The Unicorn, Inc.
00:01:F3  Qps, Inc.
00:01:F4  Enterasys Networks
00:01:F5  Erim S.a.
00:01:F6  Association Of Musical Electronics Industry
00:01:F7  Image Display Systems, Inc.
00:01:F8  Adherent Systems, Ltd.
00:01:F9  Teraglobal Communications Corp.
00:01:FA  Horoscas
00:01:FB  Dotop Technology, Inc.
00:01:FC  Keyence Corporation
00:01:FD  Digital Voice Systems, Inc.
00:01:FE  Digital Equipment Corporation
00:01:FF  Data Direct Networks, Inc.
00:02:00  Net & Sys Co., Ltd.
00:02:01  Ifm Electronic Gmbh
00:02:02  Amino Communications, Ltd.
00:02:03  Woonsang Telecom, Inc.
00:02:04  Bodmann Industries Elektronik Gmbh
00:02:05  Hitachi Denshi, Ltd.
00:02:06  Telital R&d Denmark A/s
00:02:07  Private
00:02:08  Unify Networks, Inc.
00:02:09  Shenzhen Sed Information Technology Co., Ltd.
00:02:0A  Gefran Spa
00:02:0B  Native Networks, Inc.
00:02:0C  Metro-optix
00:02:0D  Micronpc.com
00:02:0E  Laurel Networks, Inc.
00:02:0F  Aatr
00:02:10  Fenecom
00:02:11  Nature Worldwide Technology Corp.
00:02:12  Sierracom
00:02:13  S.d.e.l.
00:02:14  Dtvro
00:02:15  Cotas Computer Technology A/b
00:02:16  Cisco Systems, Inc.
00:02:17  Cisco Systems, Inc.
00:02:18  Advanced Scientific Corp
00:02:19  Paralon Technologies
00:02:1A  Zuma Networks
00:02:1B  Kollmorgen-servotronix
00:02:1C  Network Elements, Inc.
00:02:1D  Data General Communication Ltd.
00:02:1E  Simtel S.r.l.
00:02:1F  Aculab Plc
00:02:20  Canon Aptex, Inc.
00:02:21  Dsp Application, Ltd.
00:02:22  Chromisys, Inc.
00:02:23  Clicktv
00:02:24  Lantern Communications, Inc.
00:02:25  Certus Technology, Inc.
00:02:26  Xesystems, Inc.
00:02:27  Esd Gmbh
00:02:28  Necsom, Ltd.
00:02:29  Adtec Corporation
00:02:2A  Asound Electronic
00:02:2B  Tamura Electric Works, Ltd.
00:02:2C  Abb Bomem, Inc.
00:02:2D  Agere Systems
00:02:2E  Teac Corp. R& D
00:02:2F  P-cube, Ltd.
00:02:30  Intersoft Electronics
00:02:31  Ingersoll-rand
00:02:32  Avision, Inc.
00:02:33  Mantra Communications, Inc.
00:02:34  Imperial Technology, Inc.
00:02:35  Paragon Networks International
00:02:36  Init Gmbh
00:02:37  Cosmo Research Corp.
00:02:38  Serome Technology, Inc.
00:02:39  Visicom
00:02:3A  Zsk Stickmaschinen Gmbh
00:02:3B  Redback Networks
00:02:3C  Creative Technology, Ltd.
00:02:3D  Nuspeed, Inc.
00:02:3E  Selta Telematica S.p.a
00:02:3F  Compal Electronics, Inc.
00:02:40  Seedek Co., Ltd.
00:02:41  Amer.com
00:02:42  Videoframe Systems
00:02:43  Raysis Co., Ltd.
00:02:44  Surecom Technology Co.
00:02:45  Lampus Co, Ltd.
00:02:46  All-win Tech Co., Ltd.
00:02:47  Great Dragon Information Technology (group) Co., Ltd.
00:02:48  Pilz Gmbh & Co.
00:02:49  Aviv Infocom Co, Ltd.
00:02:4A  Cisco Systems, Inc.
00:02:4B  Cisco Systems, Inc.
00:02:4C  Sibyte, Inc.
00:02:4D  Mannesman Dematic Colby Pty. Ltd.
00:02:4E  Datacard Group
00:02:4F  Ipm Datacom S.r.l.
00:02:50  Geyser Networks, Inc.
00:02:51  Soma Networks
00:02:52  Carrier Corporation
00:02:53  Televideo, Inc.
00:02:54  Worldgate
00:02:55  Ibm Corporation
00:02:56  Alpha Processor, Inc.
00:02:57  Microcom Corp.
00:02:58  Flying Packets Communications
00:02:59  Tsann Kuen China (shanghai)enterprise Co., Ltd. It Group
00:02:5A  Catena Networks
00:02:5B  Cambridge Silicon Radio
00:02:5C  Sci Systems (kunshan) Co., Ltd.
00:02:5D  Calix Networks
00:02:5E  High Technology Ltd
00:02:5F  Nortel Networks
00:02:60  Accordion Networks, Inc.
00:02:61  I3 Micro Technology Ab
00:02:62  Soyo Group Soyo Com Tech Co., Ltd
00:02:63  Ups Manufacturing Srl
00:02:64  Audioramp.com
00:02:65  Virditech Co. Ltd.
00:02:66  Thermalogic Corporation
00:02:67  Node Runner, Inc.
00:02:68  Harris Government Communications
00:02:69  Nadatel Co., Ltd
00:02:6A  Cocess Telecom Co., Ltd.
00:02:6B  Bcm Computers Co., Ltd.
00:02:6C  Philips Cft
00:02:6D  Adept Telecom
00:02:6E  Negen Access, Inc.
00:02:6F  Senao International Co., Ltd.
00:02:70  Crewave Co., Ltd.
00:02:71  Vpacket Communications
00:02:72  Cc&c Technologies, Inc.
00:02:73  Coriolis Networks
00:02:74  Tommy Technologies Corp.
00:02:75  Smart Technologies, Inc.
00:02:76  Primax Electronics Ltd.
00:02:77  Cash Systemes Industrie
00:02:78  Samsung Electro-mechanics Co., Ltd.
00:02:79  Control Applications, Ltd.
00:02:7A  Ioi Technology Corporation
00:02:7B  Amplify Net, Inc.
00:02:7C  Trilithic, Inc.
00:02:7D  Cisco Systems, Inc.
00:02:7E  Cisco Systems, Inc.
00:02:7F  Ask-technologies.com
00:02:80  Mu Net, Inc.
00:02:81  Madge Networks Limited
00:02:82  Viaclix, Inc.
00:02:83  Spectrum Controls, Inc.
00:02:84  Alstom T&d P&c
00:02:85  Riverstone Networks
00:02:86  Occam Networks
00:02:87  Adapcom
00:02:88  Global Village Communication
00:02:89  Dne Technologies
00:02:8A  Ambit Microsystems Corporation
00:02:8B  Vdsl Systems Oy
00:02:8C  Micrel-synergy Semiconductor
00:02:8D  Movita Technologies, Inc.
00:02:8E  Rapid 5 Networks, Inc.
00:02:8F  Globetek, Inc.
00:02:90  Woorigisool, Inc.
00:02:91  Open Network Co., Ltd.
00:02:92  Logic Innovations, Inc.
00:02:93  Solid Data Systems
00:02:94  Tokyo Sokushin Co., Ltd.
00:02:95  Ip.access Limited
00:02:96  Lectron Co,. Ltd.
00:02:97  C-cor.net
00:02:98  Broadframe Corporation
00:02:99  Apex, Inc.
00:02:9A  Storage Apps
00:02:9B  Kreatel Communications Ab
00:02:9C  3com
00:02:9D  Merix Corp.
00:02:9E  Information Equipment Co., Ltd.
00:02:9F  L-3 Communication Aviation Recorders
00:02:A0  Flatstack Ltd.
00:02:A1  World Wide Packets
00:02:A2  Hilscher Gmbh
00:02:A3  Abb Power Automation
00:02:A4  Addpac Technology Co., Ltd.
00:02:A5  Compaq Computer Corporation
00:02:A6  Effinet Systems Co., Ltd.
00:02:A7  Vivace Networks
00:02:A8  Air Link Technology
00:02:A9  Racom, S.r.o.
00:02:AA  Plcom Co., Ltd.
00:02:AB  Ctc Union Technologies Co., Ltd.
00:02:AC  3par Data
00:02:AD  Asahi Optical Co., Ltd.
00:02:AE  Scannex Electronics Ltd.
00:02:AF  Telecruz Technology, Inc.
00:02:B0  Hokubu Communication & Industrial Co., Ltd.
00:02:B1  Anritsu, Ltd.
00:02:B2  Cablevision
00:02:B3  Intel Corporation
00:02:B4  Daphne
00:02:B5  Avnet, Inc.
00:02:B6  Acrosser Technology Co., Ltd.
00:02:B7  Watanabe Electric Industry Co., Ltd.
00:02:B8  Whi Konsult Ab
00:02:B9  Cisco Systems, Inc.
00:02:BA  Cisco Systems, Inc.
00:02:BB  Continuous Computing
00:02:BC  Lvl 7 Systems, Inc.
00:02:BD  Bionet Co., Ltd.
00:02:BE  Totsu Engineering, Inc.
00:02:BF  Dotrocket, Inc.
00:02:C0  Bencent Tzeng Industry Co., Ltd.
00:02:C1  Innovative Electronic Designs, Inc.
00:02:C2  Net Vision Telecom
00:02:C3  Arelnet Ltd.
00:02:C4  Vector International Buba
00:02:C5  Evertz Microsystems Ltd.
00:02:C6  Data Track Technology Plc
00:02:C7  Alps Electric Co., Ltd.
00:02:C8  Technocom Communications Technology (pte) Ltd
00:02:C9  Mellanox Technologies
00:02:CA  Endpoints, Inc.
00:02:CB  Tristate Ltd.
00:02:CC  M.c.c.i
00:02:CD  Teledream, Inc.
00:02:CE  Foxjet, Inc.
00:02:CF  Zygate Communications, Inc.
00:02:D0  Comdial Corporation
00:02:D1  Vivotek, Inc.
00:02:D2  Workstation Ag
00:02:D3  Netbotz, Inc.
00:02:D4  Pda Peripherals, Inc.
00:02:D5  Acr
00:02:D6  Nice Systems
00:02:D7  Empeg Ltd
00:02:D8  Brecis Communications Corporation
00:02:D9  Reliable Controls
00:02:DA  Exio Communications, Inc.
00:02:DB  Netsec
00:02:DC  Fujitsu General Limited
00:02:DD  Bromax Communications, Ltd.
00:02:DE  Astrodesign, Inc.
00:02:DF  Net Com Systems, Inc.
00:02:E0  Etas Gmbh
00:02:E1  Integrated Network Corporation
00:02:E2  Ndc Infared Engineering
00:02:E3  Lite-on Communications, Inc.
00:02:E4  Jc Hyun Systems, Inc.
00:02:E5  Timeware Ltd.
00:02:E6  Gould Instrument Systems, Inc.
00:02:E7  Cab Gmbh & Co Kg
00:02:E8  E.d.&a.
00:02:E9  Cs Systemes De Securite - C3s
00:02:EA  Videonics, Inc.
00:02:EB  Pico Communications
00:02:EC  Maschoff Design Engineering
00:02:ED  Dxo Telecom Co., Ltd.
00:02:EE  Nokia Danmark A/s
00:02:EF  Ccc Network Systems Group Ltd.
00:02:F0  Ame Optimedia Technology Co., Ltd.
00:02:F1  Pinetron Co., Ltd.
00:02:F2  Edevice, Inc.
00:02:F3  Media Serve Co., Ltd.
00:02:F4  Pctel, Inc.
00:02:F5  Vive Synergies, Inc.
00:02:F6  Equipe Communications
00:02:F7  Arm
00:02:F8  Seakr Engineering, Inc.
00:02:F9  Mimos Semiconductor Sdn Bhd
00:02:FA  Dx Antenna Co., Ltd.
00:02:FB  Baumuller Aulugen-systemtechnik Gmbh
00:02:FC  Cisco Systems, Inc.
00:02:FD  Cisco Systems, Inc.
00:02:FE  Viditec, Inc.
00:02:FF  Handan Broad Infocom
00:03:00  Netcontinuum, Inc.
00:03:01  Avantas Networks Corporation
00:03:02  Oasys Telecom, Inc.
00:03:03  Jama Electronics Co., Ltd.
00:03:04  Pacific Broadband Communications
00:03:05  Smart Network Devices Gmbh
00:03:06  Fusion In Tech Co., Ltd.
00:03:07  Secure Works, Inc.
00:03:08  Am Communications, Inc.
00:03:09  Texcel Technology Plc
00:03:0A  Argus Technologies
00:03:0B  Hunter Technology, Inc.
00:03:0C  Telesoft Technologies Ltd.
00:03:0D  Uniwill Computer Corp.
00:03:0E  Core Communications Co., Ltd.
00:03:0F  Digital China (shanghai) Networks Ltd.
00:03:10  Link Evolution Corp.
00:03:11  Micro Technology Co., Ltd.
00:03:12  Tr-systemtechnik Gmbh
00:03:13  Access Media Spa
00:03:14  Teleware Network Systems
00:03:15  Cidco Incorporated
00:03:16  Nobell Communications, Inc.
00:03:17  Merlin Systems, Inc.
00:03:18  Cyras Systems, Inc.
00:03:19  Infineon Ag
00:03:1A  Beijing Broad Telecom Ltd., China
00:03:1B  Cellvision Systems, Inc.
00:03:1C  Svenska Hardvarufabriken Ab
00:03:1D  Taiwan Commate Computer, Inc.
00:03:1E  Optranet, Inc.
00:03:1F  Condev Ltd.
00:03:20  Xpeed, Inc.
00:03:21  Reco Research Co., Ltd.
00:03:22  Idis Co., Ltd.
00:03:23  Cornet Technology, Inc.
00:03:24  Tottori Sanyo Electric Co., Ltd.
00:03:25  Arima Computer Corp.
00:03:26  Iwasaki Information Systems Co., Ltd.
00:03:27  Act'l
00:03:28  Private
00:03:29  F3, Inc.
00:03:2A  Unidata Communication Systems, Inc.
00:03:2B  Gai Datenfunksysteme Gmbh
00:03:2C  Abb Industrie Ag
00:03:2D  Ibase Technology, Inc.
00:03:2E  Scope Information Management, Ltd.
00:03:2F  Global Sun Technology, Inc.
00:03:30  Imagenics, Co., Ltd.
00:03:31  Cisco Systems, Inc.
00:03:32  Cisco Systems, Inc.
00:03:33  Digitel Co., Ltd.
00:03:34  Newport Electronics
00:03:35  Mirae Technology
00:03:36  Zetes Technologies
00:03:37  Vaone, Inc.
00:03:38  Oak Technology
00:03:39  Eurologic Systems, Ltd.
00:03:3A  Silicon Wave, Inc.
00:03:3B  Tami Tech Co., Ltd.
00:03:3C  Daiden Co., Ltd.
00:03:3D  Ilshin Lab
00:03:3E  Tateyama System Laboratory Co., Ltd.
00:03:3F  Bigband Networks, Ltd.
00:03:40  Floware Wireless Systems, Ltd.
00:03:41  Axon Digital Design
00:03:42  Nortel Networks
00:03:43  Martin Professional A/s
00:03:44  Tietech.co., Ltd.
00:03:45  Routrek Networks Corporation
00:03:46  Hitachi Kokusai Electric, Inc.
00:03:47  Intel Corporation
00:03:48  Norscan Instruments, Ltd.
00:03:49  Vidicode Datacommunicatie B.v.
00:03:4A  Rias Corporation
00:03:4B  Nortel Networks
00:03:4C  Shanghai Digivision Technology Co., Ltd.
00:03:4D  Chiaro Networks, Ltd.
00:03:4E  Pos Data Company, Ltd.
00:03:4F  Sur-gard Security
00:03:50  Bticino Spa
00:03:51  Diebold, Inc.
00:03:52  Colubris Networks
00:03:53  Mitac, Inc.
00:03:54  Fiber Logic Communications
00:03:55  Terabeam Internet Systems
00:03:56  Wincor Nixdorf Gmbh & Co Kg
00:03:57  Intervoice-brite, Inc.
00:03:58  Icable System Co., Ltd.
00:03:59  Digitalsis
00:03:5A  Photron Limited
00:03:5B  Bridgewave Communications
00:03:5C  Saint Song Corp.
00:03:5D  Bosung Hi-net Co., Ltd.
00:03:5E  Metropolitan Area Networks, Inc.
00:03:5F  Prueftechnik Condition Monitoring Gmbh & Co. Kg
00:03:60  Pac Interactive Technology, Inc.
00:03:61  Widcomm, Inc.
00:03:62  Vodtel Communications, Inc.
00:03:63  Miraesys Co., Ltd.
00:03:64  Scenix Semiconductor, Inc.
00:03:65  Kira Information & Communications, Ltd.
00:03:66  Asm Pacific Technology
00:03:67  Jasmine Networks, Inc.
00:03:68  Embedone Co., Ltd.
00:03:69  Nippon Antenna Co., Ltd.
00:03:6A  Mainnet, Ltd.
00:03:6B  Cisco Systems, Inc.
00:03:6C  Cisco Systems, Inc.
00:03:6D  Runtop, Inc.
00:03:6E  Nicon Systems (pty) Limited
00:03:6F  Telsey Spa
00:03:70  Nxtv, Inc.
00:03:71  Acomz Networks Corp.
00:03:72  Ulan
00:03:73  Aselsan A.s
00:03:74  Hunter Watertech
00:03:75  Netmedia, Inc.
00:03:76  Graphtec Technology, Inc.
00:03:77  Gigabit Wireless
00:03:78  Humax Co., Ltd.
00:03:79  Proscend Communications, Inc.
00:03:7A  Taiyo Yuden Co., Ltd.
00:03:7B  Idec Izumi Corporation
00:03:7C  Coax Media
00:03:7D  Stellcom
00:03:7E  Portech Communications, Inc.
00:03:7F  Atheros Communications, Inc.
00:03:80  Ssh Communications Security Corp.
00:03:81  Ingenico International
00:03:82  A-one Co., Ltd.
00:03:83  Metera Networks, Inc.
00:03:84  Aeta
00:03:85  Actelis Networks, Inc.
00:03:86  Ho Net, Inc.
00:03:87  Blaze Network Products
00:03:88  Fastfame Technology Co., Ltd.
00:03:89  Plantronics
00:03:8A  America Online, Inc.
00:03:8B  Plus-one I&t, Inc.
00:03:8C  Total Impact
00:03:8D  Pcs Revenue Control Systems, Inc.
00:03:8E  Atoga Systems, Inc.
00:03:8F  Weinschel Corporation
00:03:90  Digital Video Communications, Inc.
00:03:91  Private
00:03:92  Hyundai Teletek Co., Ltd.
00:03:93  Apple Computer, Inc.
00:03:94  Connect One
00:03:95  California Amplifier
00:03:96  Ez Cast Co., Ltd.
00:03:97  Watchfront Electronics
00:03:98  Wisi
00:03:99  Dongju Informations & Communications Co., Ltd.
00:03:9A  Nsine, Ltd.
00:03:9B  Netchip Technology, Inc.
00:03:9C  Optimight Communications, Inc.
00:03:9D  Benq Corporation
00:03:9E  Tera System Co., Ltd.
00:03:9F  Cisco Systems, Inc.
00:03:A0  Cisco Systems, Inc.
00:03:A1  Hiper Information & Communication, Inc.
00:03:A2  Catapult Communications
00:03:A3  Mavix, Ltd.
00:03:A4  Data Storage And Information Management
00:03:A5  Medea Corporation
00:03:A6  Private
00:03:A7  Unixtar Technology, Inc.
00:03:A8  Idot Computers, Inc.
00:03:A9  Axcent Media Ag
00:03:AA  Watlow
00:03:AB  Bridge Information Systems
00:03:AC  Fronius Schweissmaschinen
00:03:AD  Emerson Energy Systems Ab
00:03:AE  Allied Advanced Manufacturing Pte, Ltd.
00:03:AF  Paragea Communications
00:03:B0  Xsense Technology Corp.
00:03:B1  Abbott Laboratories Hpd
00:03:B2  Radware
00:03:B3  Ia Link Systems Co., Ltd.
00:03:B4  Macrotek International Corp.
00:03:B5  Entra Technology Co.
00:03:B6  Qsi Corporation
00:03:B7  Zaccess Systems
00:03:B8  Netkit Solutions, Llc
00:03:B9  Hualong Telecom Co., Ltd.
00:03:BA  Sun Microsystems
00:03:BB  Signal Communications Limited
00:03:BC  Cot Gmbh
00:03:BD  Omnicluster Technologies, Inc.
00:03:BE  Netility
00:03:BF  Centerpoint Broadband Technologies, Inc.
00:03:C0  Rftnc Co., Ltd.
00:03:C1  Packet Dynamics Ltd
00:03:C2  Solphone K.k.
00:03:C3  Micronik Multimedia
00:03:C4  Tomra Systems Asa
00:03:C5  Mobotix Ag
00:03:C6  Icue Systems, Inc.
00:03:C7  Hopf Elektronik Gmbh
00:03:C8  Cml Emergency Services
00:03:C9  Tecom Co., Ltd.
00:03:CA  Mts Systems Corp.
00:03:CB  Nippon Systems Development Co., Ltd.
00:03:CC  Momentum Computer, Inc.
00:03:CD  Clovertech, Inc.
00:03:CE  Eten Technologies, Inc.
00:03:CF  Muxcom, Inc.
00:03:D0  Koankeiso Co., Ltd.
00:03:D1  Takaya Corporation
00:03:D2  Crossbeam Systems, Inc.
00:03:D3  Internet Energy Systems, Inc.
00:03:D4  Alloptic, Inc.
00:03:D5  Advanced Communications Co., Ltd.
00:03:D6  Radvision, Ltd.
00:03:D7  Nextnet Wireless, Inc.
00:03:D8  Impath Networks, Inc.
00:03:D9  Secheron Sa
00:03:DA  Takamisawa Cybernetics Co., Ltd.
00:03:DB  Apogee Electronics Corp.
00:03:DC  Lexar Media, Inc.
00:03:DD  Comark Corp.
00:03:DE  Otc Wireless
00:03:DF  Desana Systems
00:03:E0  Radioframe Networks, Inc.
00:03:E1  Winmate Communication, Inc.
00:03:E2  Comspace Corporation
00:03:E3  Cisco Systems, Inc.
00:03:E4  Cisco Systems, Inc.
00:03:E5  Hermstedt Sg
00:03:E6  Entone Technologies, Inc.
00:03:E7  Logostek Co. Ltd.
00:03:E8  Wavelength Digital Limited
00:03:E9  Akara Canada, Inc.
00:03:EA  Mega System Technologies, Inc.
00:03:EB  Atrica
00:03:EC  Icg Research, Inc.
00:03:ED  Shinkawa Electric Co., Ltd.
00:03:EE  Mknet Corporation
00:03:EF  Oneline Ag
00:03:F0  Redfern Broadband Networks
00:03:F1  Cicada Semiconductor, Inc.
00:03:F2  Seneca Networks
00:03:F3  Dazzle Multimedia, Inc.
00:03:F4  Netburner
00:03:F5  Chip2chip
00:03:F6  Allegro Networks, Inc.
00:03:F7  Plast-control Gmbh
00:03:F8  Sancastle Technologies, Inc.
00:03:F9  Pleiades Communications, Inc.
00:03:FA  Timetra Networks
00:03:FB  Toko Seiki Company, Ltd.
00:03:FC  Intertex Data Ab
00:03:FD  Cisco Systems, Inc.
00:03:FE  Cisco Systems, Inc.
00:03:FF  Connectix
00:04:00  Lexmark International, Inc.
00:04:01  Osaki Electric Co., Ltd.
00:04:02  Nexsan Technologies, Ltd.
00:04:03  Nexsi Corporation
00:04:04  Makino Milling Machine Co., Ltd.
00:04:05  Acn Technologies
00:04:06  Fa. Metabox Ag
00:04:07  Topcon Positioning Systems, Inc.
00:04:08  Sanko Electronics Co., Ltd.
00:04:09  Cratos Networks
00:04:0A  Sage Systems
00:04:0B  3com Europe Ltd.
00:04:0C  Kanno Work's Ltd.
00:04:0D  Avaya, Inc.
00:04:0E  Avm Gmbh
00:04:0F  Asus Network Technologies, Inc.
00:04:10  Spinnaker Networks, Inc.
00:04:11  Inkra Networks, Inc.
00:04:12  Wavesmith Networks, Inc.
00:04:13  Snom Technology Ag
00:04:14  Umezawa Musen Denki Co., Ltd.
00:04:15  Rasteme Systems Co., Ltd.
00:04:16  Parks S/a Comunicacoes Digitais
00:04:17  Elau Ag
00:04:18  Teltronic S.a.u.
00:04:19  Fibercycle Networks, Inc.
00:04:1A  Ines Gmbh
00:04:1B  Digital Interfaces Ltd.
00:04:1C  Ipdialog, Inc.
00:04:1D  Corega Of America
00:04:1E  Shikoku Instrumentation Co., Ltd.
00:04:1F  Sony Computer Entertainment, Inc.
00:04:20  Slim Devices, Inc.
00:04:21  Ocular Networks
00:04:22  Gordon Kapes, Inc.
00:04:23  Intel Corporation
00:04:24  Tmc S.r.l.
00:04:25  Atmel Corporation
00:04:26  Autosys
00:04:27  Cisco Systems, Inc.
00:04:28  Cisco Systems, Inc.
00:04:29  Pixord Corporation
00:04:2A  Wireless Networks, Inc.
00:04:2B  It Access Co., Ltd.
00:04:2C  Minet, Inc.
00:04:2D  Sarian Systems, Ltd.
00:04:2E  Netous Technologies, Ltd.
00:04:2F  International Communications Products, Inc.
00:04:30  Netgem
00:04:31  Globalstreams, Inc.
00:04:32  Voyetra Turtle Beach, Inc.
00:04:33  Cyberboard A/s
00:04:34  Accelent Systems, Inc.
00:04:35  Comptek International, Inc.
00:04:36  Elansat Technologies, Inc.
00:04:37  Powin Information Technology, Inc.
00:04:38  Nortel Networks
00:04:39  Rosco Entertainment Technology, Inc.
00:04:3A  Intelligent Telecommunications, Inc.
00:04:3B  Lava Computer Mfg., Inc.
00:04:3C  Sonos Co., Ltd.
00:04:3D  Indel Ag
00:04:3E  Telencomm
00:04:3F  Electronic Systems Technology, Inc.
00:04:40  Cyberpixie, Inc.
00:04:41  Half Dome Systems, Inc.
00:04:42  Nact
00:04:43  Agilent Technologies, Inc.
00:04:44  Western Multiplex Corporation
00:04:45  Lms Skalar Instruments Gmbh
00:04:46  Cyzentech Co., Ltd.
00:04:47  Acrowave Systems Co., Ltd.
00:04:48  Polaroid Professional Imaging
00:04:49  Mapletree Networks
00:04:4A  Ipolicy Networks, Inc.
00:04:4B  Nvidia
00:04:4C  Jenoptik
00:04:4D  Cisco Systems, Inc.
00:04:4E  Cisco Systems, Inc.
00:04:4F  Leukhardt Systemelektronik Gmbh
00:04:50  Dmd Computers Srl
00:04:51  Medrad, Inc.
00:04:52  Rocketlogix, Inc.
00:04:53  Yottayotta, Inc.
00:04:54  Quadriga Uk
00:04:55  Antara.net
00:04:56  Pipinghot Networks
00:04:57  Universal Access Technology, Inc.
00:04:58  Fusion X Co., Ltd.
00:04:59  Veristar Corporation
00:04:5A  Linksys WPC11, WUSB11
00:04:5B  Techsan Electronics Co., Ltd.
00:04:5C  Mobiwave Pte Ltd
00:04:5D  Beka Elektronik
00:04:5E  Polytrax Information Technology Ag
00:04:5F  Evalue Technology, Inc.
00:04:60  Knilink Technology, Inc.
00:04:61  Epox Computer Co., Ltd.
00:04:62  Dakos Data & Communication Co., Ltd.
00:04:63  Philips Communication Security & Imaging
00:04:64  Fantasma Networks, Inc.
00:04:65  I.s.t Isdn-support Technik Gmbh
00:04:66  Armitel Co.
00:04:67  Wuhan Research Institute Of Mii
00:04:68  Vivity, Inc.
00:04:69  Innocom, Inc.
00:04:6A  Navini Networks
00:04:6B  Palm Wireless, Inc.
00:04:6C  Cyber Technology Co., Ltd.
00:04:6D  Cisco Systems, Inc.
00:04:6E  Cisco Systems, Inc.
00:04:6F  Digitel S/a Industria Eletronica
00:04:70  Ipunplugged Ab
00:04:71  Iprad
00:04:72  Telelynx, Inc.
00:04:73  Photonex Corporation
00:04:74  Legrand
00:04:75  3Com Corporation
00:04:76  3Com Corporation
00:04:77  Scalant Systems, Inc.
00:04:78  G. Star Technology Corporation
00:04:79  Radius Co., Ltd.
00:04:7A  Axxessit Asa
00:04:7B  Schlumberger
00:04:7C  Skidata Ag
00:04:7D  Pelco
00:04:7E  Nkf Electronics
00:04:7F  Chr. Mayr Gmbh & Co. Kg
00:04:80  Foundry Networks, Inc.
00:04:81  Econolite Control Products, Inc.
00:04:82  Medialogic Corp.
00:04:83  Deltron Technology, Inc.
00:04:84  Amann Gmbh
00:04:85  Picolight
00:04:86  Ittc, University Of Kansas
00:04:87  Cogency Semiconductor, Inc.
00:04:88  Eurotherm Action Incorporated.
00:04:89  Yafo Networks, Inc.
00:04:8A  Temia Vertriebs Gmbh
00:04:8B  Poscon Corporation
00:04:8C  Nayna Networks, Inc.
00:04:8D  Tone Commander Systems, Inc.
00:04:8E  Ohm Tech Labs, Inc.
00:04:8F  Td Systems Corp.
00:04:90  Optical Access
00:04:91  Technovision, Inc.
00:04:92  Hive Internet, Ltd.
00:04:93  Tsinghua Unisplendour Co., Ltd.
00:04:94  Breezecom, Ltd.
00:04:95  Tejas Networks
00:04:96  Extreme Networks
00:04:97  Macrosystem Digital Video Ag
00:04:98  Private
00:04:99  Chino Corporation
00:04:9A  Cisco Systems, Inc.
00:04:9B  Cisco Systems, Inc.
00:04:9C  Surgient Networks, Inc.
00:04:9D  Ipanema Technologies
00:04:9E  Wirelink Co., Ltd.
00:04:9F  Metrowerks
00:04:A0  Verity Instruments, Inc.
00:04:A1  Pathway Connectivity
00:04:A2  L.s.i. Japan Co., Ltd.
00:04:A3  Microchip Technology, Inc.
00:04:A4  Netenabled, Inc.
00:04:A5  Barco Projection Systems Nv
00:04:A6  Saf Tehnika Ltd.
00:04:A7  Fabiatech Corporation
00:04:A8  Broadmax Technologies, Inc.
00:04:A9  Sandstream Technologies, Inc.
00:04:AA  Jetstream Communications
00:04:AB  Comverse Network Systems, Inc.
00:04:AC  Ibm Corp.
00:04:AD  Malibu Networks
00:04:AE  Liquid Metronics
00:04:AF  Digital Fountain, Inc.
00:04:B0  Elesign Co., Ltd.
00:04:B1  Signal Technology, Inc.
00:04:B2  Essegi Srl
00:04:B3  Videotek, Inc.
00:04:B4  Ciac
00:04:B5  Equitrac Corporation
00:04:B6  Tellumat (pty) Ltd.
00:04:B7  Amb I.t. Holding
00:04:B8  Kumahira Co., Ltd.
00:04:B9  S.i. Soubou, Inc.
00:04:BA  Kdd Media Will Corporation
00:04:BB  Bardac Corporation
00:04:BC  Giantec, Inc.
00:04:BD  Motorola Bcs
00:04:BE  Optxcon, Inc.
00:04:BF  Versalogic Corp.
00:04:C0  Cisco Systems, Inc.
00:04:C1  Cisco Systems, Inc.
00:04:C2  Magnipix, Inc.
00:04:C3  Castor Informatique
00:04:C4  Allen & Health Limited
00:04:C5  Ase Technologies, Usa
00:04:C6  Yamaha Motor Co., Ltd.
00:04:C7  Netmount
00:04:C8  Liba Maschinenfabrik Gmbh
00:04:C9  Micro Electron Co., Ltd.
00:04:CA  Freems Corp.
00:04:CB  Tdsoft Communication, Ltd.
00:04:CC  Peek Traffic B.v.
00:04:CD  Informedia Research Group
00:04:CE  Patria Ailon
00:04:CF  Seagate Technology
00:04:D0  Softlink S.r.o.
00:04:D1  Drew Technologies, Inc.
00:04:D2  Adcon Telemetry Ag
00:04:D3  Toyokeiki Co., Ltd.
00:04:D4  Proview Electronics Co., Ltd.
00:04:D5  Hitachi Communication Systems, Inc.
00:04:D6  Takagi Industrial Co., Ltd.
00:04:D7  Omitec Instrumentation Ltd.
00:04:D8  Ipwireless, Inc.
00:04:D9  Titan Electronics, Inc.
00:04:DA  Relax Technology, Inc.
00:04:DB  Tellus Group Corp.
00:04:DC  Nortel Networks
00:04:DD  Cisco Systems, Inc.
00:04:DE  Cisco Systems, Inc.
00:04:DF  Teracom Telematica Ltda.
00:04:E0  Procket Networks
00:04:E1  Infinior Microsystems
00:04:E2  SMC SMC2632W
00:04:E3  Accton Technology Corp.
00:04:E4  Daeryung Ind., Inc.
00:04:E5  Glonet Systems, Inc.
00:04:E6  Banyan Network Private Limited
00:04:E7  Lightpointe Communications, Inc
00:04:E8  Ier, Inc.
00:04:E9  Infiniswitch Corporation
00:04:EA  Hewlett-packard Company
00:04:EB  Paxonet Communications, Inc.
00:04:EC  Memobox Sa
00:04:ED  Billion Electric Co., Ltd.
00:04:EE  Lincoln Electric Company
00:04:EF  Polestar Corp.
00:04:F0  International Computers, Ltd
00:04:F1  Wherenet
00:04:F2  Circa Communications, Ltd.
00:04:F3  Fs Forth-systeme Gmbh
00:04:F4  Infinite Electronics Inc.
00:04:F5  Snowshore Networks, Inc.
00:04:F6  Amphus
00:04:F7  Omega Band, Inc.
00:04:F8  Qualicable Tv Industria E Com., Ltda
00:04:F9  Xtera Communications, Inc.
00:04:FA  Mist Inc.
00:04:FB  Commtech, Inc.
00:04:FC  Stratus Computer (de), Inc.
00:04:FD  Japan Control Engineering Co., Ltd.
00:04:FE  Pelago Networks
00:04:FF  Acronet Co., Ltd.
00:05:00  Cisco Systems, Inc.
00:05:01  Cisco Systems, Inc.
00:05:02  Apple Computer
00:05:03  Iconag
00:05:04  Naray Information & Communication Enterprise
00:05:05  Systems Integration Solutions, Inc.
00:05:06  Reddo Networks Ab
00:05:07  Fine Appliance Corp.
00:05:08  Inetcam, Inc.
00:05:09  Avoc Nishimura Ltd.
00:05:0A  Ics Spa
00:05:0B  Sicom Systems, Inc.
00:05:0C  Network Photonics, Inc.
00:05:0D  Midstream Technologies, Inc.
00:05:0E  3ware, Inc.
00:05:0F  Tanaka S/s Ltd.
00:05:10  Infinite Shanghai Communication Terminals Ltd.
00:05:11  Complementary Technologies Ltd
00:05:12  Meshnetworks, Inc.
00:05:13  Vtlinx Multimedia Systems, Inc.
00:05:14  Kdt Systems Co., Ltd.
00:05:15  Nuark Co., Ltd.
00:05:16  Smart Modular Technologies
00:05:17  Shellcomm, Inc.
00:05:18  Jupiters Technology
00:05:19  Siemens Building Technologies Ag,
00:05:1A  3com Europe Ltd.
00:05:1B  Magic Control Technology Corporation
00:05:1C  Xnet Technology Corp.
00:05:1D  Airocon, Inc.
00:05:1E  Rhapsody Networks
00:05:1F  Taijin Media Co., Ltd.
00:05:20  Smartronix, Inc.
00:05:21  Control Microsystems
00:05:22  Lea*d Corporation, Inc.
00:05:23  Avl List Gmbh
00:05:24  Btl System (hk) Limited
00:05:25  Puretek Industrial Co., Ltd.
00:05:26  Ipas Gmbh
00:05:27  Sj Tek Co. Ltd
00:05:28  New Focus, Inc.
00:05:29  Shanghai Broadan Communication Technology Co., Ltd
00:05:2A  Ikegami Tsushinki Co., Ltd.
00:05:2B  Horiba, Ltd.
00:05:2C  Supreme Magic Corporation
00:05:2D  Zoltrix International Limited
00:05:2E  Cinta Networks
00:05:2F  Leviton Voice And Data
00:05:30  Andiamo Systems, Inc.
00:05:31  Cisco Systems, Inc.
00:05:32  Cisco Systems, Inc.
00:05:33  Sanera Systems, Inc.
00:05:34  Northstar Engineering Ltd.
00:05:35  Chip Pc Ltd.
00:05:36  Danam Communications, Inc.
00:05:37  Nets Technology Co., Ltd.
00:05:38  Merilus, Inc.
00:05:39  A Brand New World In Sweden Ab
00:05:3A  Willowglen Services Pte Ltd
00:05:3B  Harbour Networks Ltd., Co. Beijing
00:05:3C  Xircom
00:05:3D  Agere Systems
00:05:3E  Kid Systeme Gmbh
00:05:3F  Visiontek, Inc.
00:05:40  Fast Corporation
00:05:41  Advanced Systems Co., Ltd.
00:05:42  Otari, Inc.
00:05:43  Iq Wireless Gmbh
00:05:44  Valley Technologies, Inc.
00:05:45  Internet Photonics
00:05:46  K-solutions Inc.
00:05:47  Starent Networks
00:05:48  Disco Corporation
00:05:49  Salira Optical Network Systems
00:05:4A  Ario Data Networks, Inc.
00:05:4B  Micro Innovation Ag
00:05:4C  Rf Innovations Pty Ltd
00:05:4D  Brans Technologies, Inc.
00:05:4E  Philips Components
00:05:4F  Private
00:05:50  Digi-tech Communications Limited
00:05:51  F & S Elektronik Systeme Gmbh
00:05:52  Xycotec Computer Gmbh
00:05:53  Dvc Company, Inc.
00:05:54  Rangestar Wireless
00:05:55  Japan Cash Machine Co., Ltd.
00:05:56  360 Systems
00:05:57  Agile Tv Corporation
00:05:58  Synchronous, Inc.
00:05:59  Intracom S.a.
00:05:5A  Power Dsine Ltd.
00:05:5B  Charles Industries, Ltd.
00:05:5C  Kowa Company, Ltd.
00:05:5D  D-Link DWL-650, DWL-650H
00:05:5E  Cisco Systems, Inc.
00:05:5F  Cisco Systems, Inc.
00:05:60  Leader Comm.co., Ltd
00:05:61  Nac Image Technology, Inc.
00:05:62  Digital View Limited
00:05:63  J-works, Inc.
00:05:64  Tsinghua Bitway Co., Ltd.
00:05:65  Tailyn Communication Company Ltd.
00:05:66  Secui.com Corporation
00:05:67  Etymonic Design, Inc.
00:05:68  Piltofish Networks Ab
00:05:69  Vmware, Inc.
00:05:6A  Private
00:05:6B  C.p. Technology Co., Ltd.
00:05:6C  Hung Chang Co., Ltd.
00:05:6D  Pacific Corporation
00:05:6E  National Enhance Technology, Inc.
00:05:6F  Innomedia Technologies Pvt. Ltd.
00:05:70  Baydel Ltd.
00:05:71  Seiwa Electronics Co.
00:05:72  Deonet Co., Ltd.
00:05:73  Cisco Systems, Inc.
00:05:74  Cisco Systems, Inc.
00:05:75  Cds-electronics Bv
00:05:76  Nsm Technology Ltd.
00:05:77  Sm Information & Communication
00:05:78  Private
00:05:79  Universal Control Solution Corp.
00:05:7A  Hatteras Networks
00:05:7B  Chung Nam Electronic Co., Ltd.
00:05:7C  Rco Security Ab
00:05:7D  Sun Communications, Inc.
00:05:7E  Eckelmann Steuerungstechnik Gmbh
00:05:7F  Acqis Technology
00:05:80  Fibrolan Ltd.
00:05:81  Snell & Wilcox Ltd.
00:05:82  Clearcube Technology
00:05:83  Imagecom Limited
00:05:84  Absolutevalue Systems, Inc.
00:05:85  Juniper Networks, Inc.
00:05:86  Lucent Technologies
00:05:87  Locus, Incorporated
00:05:88  Sensoria Corp.
00:05:89  National Datacomputer
00:05:8A  Netcom Co., Ltd.
00:05:8B  Ipmental, Inc.
00:05:8C  Opentech Inc.
00:05:8D  Lynx Photonic Networks, Inc.
00:05:8E  Ahead Communications System Gmbh
00:05:8F  Clcsoft Co.
00:05:90  Swissvoice Ltd.
00:05:91  Active Silicon Ltd.
00:05:92  Pultek Corp.
00:05:93  Grammar Engine Inc.
00:05:94  Ixxat Automation Gmbh
00:05:95  Alesis Corporation
00:05:96  Genotech Co., Ltd.
00:05:97  Eagle Traffic Control Systems
00:05:98  Cronos S.r.l.
00:05:99  Pei Electronics, Inc.
00:05:9A  Cisco Systems, Inc.
00:05:9B  Cisco Systems, Inc.
00:05:9C  Kleinknecht Gmbh, Ing. Buero
00:05:9D  Daniel Computing Systems, Inc.
00:05:9E  Zinwell Corporation
00:05:9F  Yotta Networks, Inc.
00:05:A0  Mobiline Kft.
00:05:A1  Zenocom
00:05:A2  Celox Networks
00:05:A3  Qei, Inc.
00:05:A4  Lucid Voice Ltd.
00:05:A5  Kott
00:05:A6  Extron Electronics
00:05:A7  Hyperchip, Inc.
00:05:A8  Wyle Electronics
00:05:A9  Princeton Networks, Inc.
00:05:AA  Moore Industries International Inc.
00:05:AB  Cyber Fone, Inc.
00:05:AC  Northern Digital, Inc.
00:05:AD  Topspin Communications, Inc.
00:05:AE  Mediaport Usa
00:05:AF  Innoscan Computing A/s
00:05:B0  Korea Computer Technology Co., Ltd.
00:05:B1  Asb Technology Bv
00:05:B2  Medison Co., Ltd.
00:05:B3  Asahi-engineering Co., Ltd.
00:05:B4  Aceex Corporation
00:05:B5  Broadcom Technologies
00:05:B6  Insys Microelectronics Gmbh
00:05:B7  Arbor Technology Corp.
00:05:B8  Electronic Design Associates, Inc.
00:05:B9  Airvana, Inc.
00:05:BA  Area Netwoeks, Inc.
00:05:BB  Myspace Ab
00:05:BC  Resorsys Ltd.
00:05:BD  Roax Bv
00:05:BE  Kongsberg Seatex As
00:05:BF  Justezy Technology, Inc.
00:05:C0  Digital Network Alacarte Co., Ltd.
00:05:C1  A-kyung Motion, Inc.
00:05:C2  Digital Archway, Inc.
00:05:C3  Pacific Instruments, Inc.
00:05:C4  Telect, Inc.
00:05:C5  Flaga Hf
00:05:C6  Triz Communications
00:05:C7  I/f-com A/s
00:05:C8  Verytech
00:05:C9  Lg Innotek
00:05:CA  Hitron Technology, Inc.
00:05:CB  Rois Technologies, Inc.
00:05:CC  Sumtel Communications, Inc.
00:05:CD  Denon, Ltd.
00:05:CE  Prolink Microsystems Corporation
00:05:CF  Thunder River Technologies, Inc.
00:05:D0  Solinet Systems
00:05:D1  Metavector Technologies
00:05:D2  Dap Technologies
00:05:D3  Eproduction Solutions, Inc.
00:05:D4  Futuresmart Networks, Inc.
00:05:D5  Speedcom Wireless
00:05:D6  Titan Wireless
00:05:D7  Vista Imaging, Inc.
00:05:D8  Arescom, Inc.
00:05:D9  Techno Valley, Inc.
00:05:DA  Apex Automationstechnik
00:05:DB  Nentec Gmbh
00:05:DC  Cisco Systems, Inc.
00:05:DD  Cisco Systems, Inc.
00:05:DE  Gi Fone Korea, Inc.
00:05:DF  Electronic Innovation, Inc.
00:05:E0  Empirix Corp.
00:05:E1  Trellis Photonics, Ltd.
00:05:E2  Creativ Network Technologies
00:05:E3  Lightsand Communications, Inc.
00:05:E4  Red Lion Controls L.p.
00:05:E5  Renishaw Plc
00:05:E6  Egenera, Inc.
00:05:E7  Netrake Corp.
00:05:E8  Turbowave, Inc.
00:05:E9  Unicess Network, Inc.
00:05:EA  Rednix
00:05:EB  Blue Ridge Networks, Inc.
00:05:EC  Mosaic Systems Inc.
00:05:ED  Technikum Joanneum Gmbh
00:05:EE  Bewator Group
00:05:EF  Adoir Digital Technology
00:05:F0  Satec
00:05:F1  Vrcom, Inc.
00:05:F2  Power R, Inc.
00:05:F3  Weboyn
00:05:F4  System Base Co., Ltd.
00:05:F5  Oyo Geospace Corp.
00:05:F6  Young Chang Co. Ltd.
00:05:F7  Analog Devices, Inc.
00:05:F8  Real Time Access, Inc.
00:05:F9  Toa Corporation
00:05:FA  Ipoptical, Inc.
00:05:FB  Sharegate, Inc.
00:05:FC  Schenck Pegasus Corp.
00:05:FD  Packetlight Networks Ltd.
00:05:FE  Traficon N.v.
00:05:FF  Sns Solutions, Inc.
00:06:00  Tokyo Electronic Industry Co., Ltd.
00:06:01  Otanikeiki Co., Ltd.
00:06:02  Cirkitech Electronics Co.
00:06:03  Baker Hughes Inc.
00:06:04  @track Communications, Inc.
00:06:05  Inncom International, Inc.
00:06:06  Rapidwan, Inc.
00:06:07  Omni Directional Control Technology Inc.
00:06:08  At-sky Sas
00:06:09  Crossport Systems
00:06:0A  Blue2space
00:06:0B  Paceline Systems Corporation
00:06:0C  Melco Industries, Inc.
00:06:0D  Wave7 Optics
00:06:0E  Igys Systems, Inc.
00:06:0F  Narad Networks Inc
00:06:10  Abeona Networks Inc
00:06:11  Zeus Wireless, Inc.
00:06:12  Accusys, Inc.
00:06:13  Kawasaki Microelectronics Incorporated
00:06:14  Prism Holdings
00:06:15  Kimoto Electric Co., Ltd.
00:06:16  Tel Net Co., Ltd.
00:06:17  Redswitch Inc.
00:06:18  Digipower Manufacturing Inc.
00:06:19  Connection Technology Systems
00:06:1A  Zetari Inc.
00:06:1B  Portable Systems, Ibm Japan Co, Ltd
00:06:1C  Hoshino Metal Industries, Ltd.
00:06:1D  Mip Telecom, Inc.
00:06:1E  Maxan Systems
00:06:1F  Vision Components Gmbh
00:06:20  Serial System Ltd.
00:06:21  Hinox, Co., Ltd.
00:06:22  Chung Fu Chen Yeh Enterprise Corp.
00:06:23  Mge Ups Systems France
00:06:24  Gentner Communications Corp.
00:06:25  Linksys WPC11 v2.5, D-Link DCF-650W, Linksys WPC11 v3
00:06:26  Mwe Gmbh
00:06:27  Uniwide Technologies, Inc.
00:06:28  Cisco Systems, Inc.
00:06:29  Ibm Corporation
00:06:2A  Cisco Systems, Inc.
00:06:2B  Intraserver Technology
00:06:2C  Network Robots, Inc.
00:06:2D  Touchstar Technologies, L.l.c.
00:06:2E  Aristos Logic Corp.
00:06:2F  Pivotech Systems Inc.
00:06:30  Adtranz Sweden
00:06:31  Optical Solutions, Inc.
00:06:32  Mesco Engineering Gmbh
00:06:33  Heimann Biometric Systems Gmbh
00:06:34  Gte Airfone Inc.
00:06:35  Packetair Networks, Inc.
00:06:36  Jedai Broadband Networks
00:06:37  Toptrend-meta Information (shenzhen) Inc.
00:06:38  Sungjin C&c Co., Ltd.
00:06:39  Newtec
00:06:3A  Dura Micro, Inc.
00:06:3B  Arcturus Networks, Inc.
00:06:3C  Nmi Electronics Ltd
00:06:3D  Microwave Data Systems Inc.
00:06:3E  Opthos Inc.
00:06:3F  Everex Communications Inc.
00:06:40  White Rock Networks
00:06:41  Itcn
00:06:42  Genetel Systems Inc.
00:06:43  Sono Computer Co., Ltd.
00:06:44  Neix Inc.
00:06:45  Meisei Electric Co. Ltd.
00:06:46  Shenzhen Xunbao Network Technology Co Ltd
00:06:47  Etrali S.a.
00:06:48  Seedsware, Inc.
00:06:49  Quante
00:06:4A  Honeywell Co., Ltd. (korea)
00:06:4B  Alexon Co., Ltd.
00:06:4C  Invicta Networks, Inc.
00:06:4D  Sencore
00:06:4E  Broad Net Technology Inc.
00:06:4F  Pro-nets Technology Corporation
00:06:50  Tiburon Networks, Inc.
00:06:51  Aspen Networks Inc.
00:06:52  Cisco Systems, Inc.
00:06:53  Cisco Systems, Inc.
00:06:54  Maxxio Technologies
00:06:55  Yipee, Inc.
00:06:56  Tactel Ab
00:06:57  Market Central, Inc.
00:06:58  Helmut Fischer Gmbh & Co. Kg
00:06:59  Eal (apeldoorn) B.v.
00:06:5A  Strix Systems
00:06:5B  Dell Computer Corp.
00:06:5C  Malachite Technologies, Inc.
00:06:5D  Heidelberg Web Systems
00:06:5E  Photuris, Inc.
00:06:5F  Eci Telecom - Ngts Ltd.
00:06:60  Nadex Co., Ltd.
00:06:61  Nia Home Technologies Corp.
00:06:62  Mbm Technology Ltd.
00:06:63  Human Technology Co., Ltd.
00:06:64  Fostex Corporation
00:06:65  Sunny Giken, Inc.
00:06:66  Roving Networks
00:06:67  Tripp Lite
00:06:68  Vicon Industries Inc.
00:06:69  Datasound Laboratories Ltd
00:06:6A  Infinicon Systems, Inc.
00:06:6B  Sysmex Corporation
00:06:6C  Robinson Corporation
00:06:6D  Compuprint S.p.a.
00:06:6E  Delta Electronics, Inc.
00:06:6F  Korea Data Systems
00:06:70  Upponetti Oy
00:06:71  Softing Ag
00:06:72  Netezza
00:06:73  Optelecom, Inc.
00:06:74  Spectrum Control, Inc.
00:06:75  Banderacom, Inc.
00:06:76  Novra Technologies Inc.
00:06:77  Sick Ag
00:06:78  Marantz Japan, Inc.
00:06:79  Konami Corporation
00:06:7A  Jmp Systems
00:06:7B  Toplink C&c Corporation
00:06:7C  Cisco Systems, Inc.
00:06:7D  Takasago Ltd.
00:06:7E  Wincom Systems, Inc.
00:06:7F  Rearden Steel Technologies
00:06:80  Card Access, Inc.
00:06:81  Goepel Electronic Gmbh
00:06:82  Convedia
00:06:83  Bravara Communications, Inc.
00:06:84  Biacore Ab
00:06:85  Netnearu Corporation
00:06:86  Zardcom Co., Ltd.
00:06:87  Omnitron Systems Technology, Inc.
00:06:88  Telways Communication Co., Ltd.
00:06:89  Ylez Technologies Pte Ltd
00:06:8A  Neuronnet Co. Ltd. R&d Center
00:06:8B  Airrunner Technologies, Inc.
00:06:8C  3com Corporation
00:06:8D  Sangate Systems
00:06:8E  Hid Corporation
00:06:8F  Telemonitor, Inc.
00:06:90  Euracom Communication Gmbh
00:06:91  Pt Inovacao
00:06:92  Intruvert Networks, Inc.
00:06:93  Flexus Computer Technology, Inc.
00:06:94  Mobillian Corporation
00:06:95  Ensure Technologies, Inc.
00:06:96  Advent Networks
00:06:97  R & D Center
00:06:98  Egnite Software Gmbh
00:06:99  Vida Design Co.
00:06:9A  E & Tel
00:06:9B  Avt Audio Video Technologies Gmbh
00:06:9C  Transmode Systems Ab
00:06:9D  Petards Mobile Intelligence
00:06:9E  Uniqa, Inc.
00:06:9F  Kuokoa Networks
00:06:A0  Mx Imaging
00:06:A1  Celsian Technologies, Inc.
00:06:A2  Microtune, Inc.
00:06:A3  Bitran Corporation
00:06:A4  Innowell Corp.
00:06:A5  Pinon Corp.
00:06:A6  Artistic Licence (uk) Ltd
00:06:A7  Primarion
00:06:A8  Kc Technology, Inc.
00:06:A9  Universal Instruments Corp.
00:06:AA  Miltope Corporation
00:06:AB  W-link Systems, Inc.
00:06:AC  Intersoft Co.
00:06:AD  Kb Electronics Ltd.
00:06:AE  Himachal Futuristic Communications Ltd
00:06:AF  Private
00:06:B0  Comtech Ef Data Corp.
00:06:B1  Sonicwall
00:06:B2  Linxtek Co.
00:06:B3  Diagraph Corporation
00:06:B4  Vorne Industries, Inc.
00:06:B5  Luminent, Inc.
00:06:B6  Nir-or Israel Ltd.
00:06:B7  Telem Gmbh
00:06:B8  Bandspeed Pty Ltd
00:06:B9  A5tek Corp.
00:06:BA  Westwave Communications
00:06:BB  Ati Technologies Inc.
00:06:BC  Macrolink, Inc.
00:06:BD  Bntechnology Co., Ltd.
00:06:BE  Baumer Optronic Gmbh
00:06:BF  Accella Technologies Co., Ltd.
00:06:C0  United Internetworks, Inc.
00:06:C1  Cisco Systems, Inc.
00:06:C2  Smartmatic Corporation
00:06:C3  Schindler Elevators Ltd.
00:06:C4  Piolink Inc.
00:06:C5  Innovi Technologies Limited
00:06:C6  Lesswire Ag
00:06:C7  Rfnet Technologies Pte Ltd (s)
00:06:C8  Sumitomo Metal Micro Devices, Inc.
00:06:C9  Technical Marketing Research, Inc.
00:06:CA  American Computer & Digital Components, Inc. (acdc)
00:06:CB  Jotron Electronics A/s
00:06:CC  Jmi Electronics Co., Ltd.
00:06:CD  Creoscitex Corporation Ltd.
00:06:CE  Dateno
00:06:CF  Thales Avionics In-flight Systems, Llc
00:06:D0  Elgar Electronics Corp.
00:06:D1  Tahoe Networks, Inc.
00:06:D2  Tundra Semiconductor Corp.
00:06:D3  Alpha Telecom, Inc. U.s.a.
00:06:D4  Interactive Objects, Inc.
00:06:D5  Diamond Systems Corp.
00:06:D6  Cisco Systems, Inc.
00:06:D7  Cisco Systems, Inc.
00:06:D8  Maple Optical Systems
00:06:D9  Ipm-net S.p.a.
00:06:DA  Itran Communications Ltd.
00:06:DB  Ichips Co., Ltd.
00:06:DC  Syabas Technology (amquest)
00:06:DD  At & T Laboratories - Cambridge Ltd
00:06:DE  Flash Technology
00:06:DF  Aidonic Corporation
00:06:E0  Mat Co., Ltd.
00:06:E1  Techno Trade S.a
00:06:E2  Ceemax Technology Co., Ltd.
00:06:E3  Quantitative Imaging Corporation
00:06:E4  Citel Technologies Ltd.
00:06:E5  Fujian Newland Computer Ltd. Co.
00:06:E6  Dongyang Telecom Co., Ltd.
00:06:E7  Bit Blitz Communications Inc.
00:06:E8  Optical Network Testing, Inc.
00:06:E9  Intime Corp.
00:06:EA  Elzet80 Mikrocomputer Gmbh&co. Kg
00:06:EB  Global Data
00:06:EC  M/a Com Private Radio System Inc.
00:06:ED  Inara Networks
00:06:EE  Shenyang Neu-era Information & Technology Stock Co., Ltd
00:06:EF  Maxxan Systems, Inc.
00:06:F0  Digeo, Inc.
00:06:F1  Optillion
00:06:F2  Platys Communications
00:06:F3  Accelight Networks
00:06:F4  Prime Electronics & Satellitics Inc.
00:06:F8  Private
00:06:F9  Mitsui Zosen Systems Research Inc.
00:06:FA  Ip Square Co, Ltd.
00:06:FB  Hitachi Koki Co., Ltd.
00:06:FC  Fnet Co., Ltd.
00:06:FD  Comjet Information Systems Corp.
00:06:FE  Celion Networks, Inc.
00:06:FF  Sheba Systems Co., Ltd.
00:07:00  Zettamedia Korea
00:07:01  Racal-datacom
00:07:02  Varian Medical Systems
00:07:03  Csee Transport
00:07:05  Endress & Hauser Gmbh & Co
00:07:06  Sanritz Corporation
00:07:07  Interalia Inc.
00:07:08  Bitrage Inc.
00:07:09  Westerstrand Urfabrik Ab
00:07:0A  Unicom Automation Co., Ltd.
00:07:0B  Octal, Sa
00:07:0C  Sva-intrusion.com Co. Ltd.
00:07:0D  Cisco Systems Inc.
00:07:0E  Cisco AIR-PCM352
00:07:0F  Fujant, Inc.
00:07:10  Adax, Inc.
00:07:11  Acterna
00:07:12  Jal Information Technology
00:07:13  Ip One, Inc.
00:07:14  Brightcom
00:07:15  General Research Of Electronics, Inc.
00:07:16  J & S Marine Ltd.
00:07:17  Wieland Electric Gmbh
00:07:18  Icantek Co., Ltd.
00:07:19  Mobiis Co., Ltd.
00:07:1A  Finedigital Inc.
00:07:1B  Position Technology Inc.
00:07:1C  At&t Fixed Wireless Services
00:07:1D  Satelsa Sistemas Y Aplicaciones De Telecomunicaciones, S.a.
00:07:1E  Tri-m Engineering / Nupak Dev. Corp.
00:07:1F  European Systems Integration
00:07:20  Trutzschler Gmbh & Co. Kg
00:07:21  Formac Elektronik Gmbh
00:07:22  Nielsen Media Research
00:07:23  Elcon Systemtechnik Gmbh
00:07:24  Telemax Co., Ltd.
00:07:25  Bematech International Corp.
00:07:27  Zi Corporation (hk) Ltd.
00:07:28  Neo Telecom
00:07:29  Kistler Instrumente Ag
00:07:2A  Innovance Networks
00:07:2B  Jung Myung Telecom Co., Ltd.
00:07:2C  Fabricom
00:07:2D  Cnsystems
00:07:2E  North Node Ab
00:07:2F  Instransa, Inc.
00:07:30  Hutchison Optel Telecom Technology Co., Ltd.
00:07:31  Spiricon, Inc.
00:07:32  Aaeon Technology Inc.
00:07:33  Dancontrol Engineering
00:07:34  Agile Storage, Inc.
00:07:35  Flarion Technologies, Inc.
00:07:36  Data Video Technologies Co., Ltd.
00:07:37  Soriya Co. Ltd.
00:07:38  Young Technology Co., Ltd.
00:07:39  Motion Media Technology Ltd.
00:07:3A  Inventel Systemes
00:07:3B  Tenovis Gmbh & Co Kg
00:07:3C  Telecom Design
00:07:3D  Nanjing Postel Telecommunications Co., Ltd.
00:07:3E  China Great-wall Computer Shenzhen Co., Ltd.
00:07:3F  Woojyun Systec Co., Ltd.
00:07:40  Melco Inc.
00:07:41  Sierra Automated Systems
00:07:42  Current Technologies
00:07:43  Chelsio Communications
00:07:44  Unico, Inc.
00:07:45  Radlan Computer Communications Ltd.
00:07:46  Interlink Bt, Llc
00:07:47  Mecalc
00:07:48  The Imaging Source Europe
00:07:49  Cenix Inc.
00:07:4A  Carl Valentin Gmbh
00:07:4B  Daihen Corporation
00:07:4C  Beicom Inc.
00:07:4D  Zebra Technologies Corp.
00:07:4E  Naughty Boy Co., Ltd.
00:07:4F  Cisco Systems, Inc.
00:07:50  Cisco AIR-LMC352
00:07:51  M.u.t. - Gmbh
00:07:52  Rhythm Watch Co., Ltd.
00:07:53  Beijing Qxcomm Technology Co., Ltd.
00:07:54  Xyterra Computing, Inc.
00:07:55  Lafon Sa
00:07:56  Juyoung Telecom
00:07:57  Topcall International Ag
00:07:58  Dragonwave
00:07:59  Boris Manufacturing Corp.
00:07:5A  Air Products And Chemicals, Inc.
00:07:5B  Gibson Guitars
00:07:5C  Encad, Inc.
00:07:5D  Celleritas Inc.
00:07:5E  Pulsar Technologies, Inc.
00:07:5F  Vcs Video Communication Systems Ag
00:07:60  Tomis Information & Telecom Corp.
00:07:61  Logitech Sa
00:07:62  Group Sense Limited
00:07:63  Sunniwell Cyber Tech. Co., Ltd.
00:07:64  Youngwoo Telecom Co. Ltd.
00:07:65  Jade Quantum Technologies, Inc.
00:07:66  Chou Chin Industrial Co., Ltd.
00:07:67  Yuxing Electronics Company Limited
00:07:68  Danfoss A/s
00:07:69  Italiana Macchi Spa
00:07:6A  Nexteye Co., Ltd.
00:07:6B  Stralfors Ab
00:07:6C  Daehanet, Inc.
00:07:6D  Flexlight Networks
00:07:6E  Sinetica Corporation Ltd.
00:07:6F  Synoptics Limited
00:07:70  Locusnetworks Corporation
00:07:71  Embedded System Corporation
00:07:72  Shanghai Bell Company Limited
00:07:73  Ascom Powerline Communications Ltd.
00:07:74  Guangzhou Thinker Technology Co. Ltd.
00:07:75  Valence Semiconductor, Inc.
00:07:76  Federal Apd
00:07:77  Motah Ltd.
00:07:78  Gerstel Gmbh & Co. Kg
00:07:79  Sungil Telecom Co., Ltd.
00:07:7A  Infoware System Co., Ltd.
00:07:7B  Millimetrix Broadband Networks
00:07:7C  Ontime Networks
00:07:7E  Elrest Gmbh
00:07:7F  J Communications Co., Ltd.
00:07:80  Bluegiga Technologies Oy
00:07:81  Itron Inc.
00:07:82  Nauticus Networks, Inc.
00:07:83  Syncom Network, Inc.
00:07:84  Cisco Systems Inc.
00:07:85  Cisco Systems Inc.
00:07:86  Wireless Networks Inc.
00:07:87  Idea System Co., Ltd.
00:07:88  Clipcomm, Inc.
00:07:89  Eastel Systems Corporation
00:07:8A  Mentor Data System Inc.
00:07:8B  Wegener Communications, Inc.
00:07:8C  Elektronikspecialisten I Borlange Ab
00:07:8D  Netengines Ltd.
00:07:8E  Garz & Friche Gmbh
00:07:8F  Emkay Innovative Products
00:07:90  Tri-m Technologies (s) Limited
00:07:91  International Data Communications, Inc.
00:07:92  Suetron Electronic Gmbh
00:07:93  Private
00:07:94  Simple Devices, Inc.
00:07:95  Elitegroup Computer System Co. (ecs)
00:07:96  Lsi Systems, Inc.
00:07:97  Netpower Co., Ltd.
00:07:98  Selea Srl
00:07:99  Tipping Point Technologies, Inc.
00:07:9A  Smartsight Networks Inc.
00:07:9B  Aurora Networks
00:07:9C  Golden Electronics Technology Co., Ltd.
00:07:9D  Musashi Co., Ltd.
00:07:9E  Ilinx Co., Ltd.
00:07:9F  Action Digital Inc.
00:07:A0  E-watch Inc.
00:07:A1  Viasys Critical Care
00:07:A2  Opteon Corporation
00:07:A3  Ositis Software, Inc.
00:07:A4  Gn Netcom Ltd.
00:07:A5  Y.d.k Co. Ltd.
00:07:A6  Home Automation, Inc.
00:07:A7  A-z Inc.
00:07:A8  Haier Group Technologies Ltd.
00:07:A9  Novasonics
00:07:AA  Quantum Data Inc.
00:07:AC  Eolring
00:07:AD  Pentacon Gmbh Foto-und Feinwerktechnik
00:07:AE  Layer N Networks
00:07:AF  N-tron Corp.
00:07:B0  Office Details, Inc.
00:07:B1  Equator Technologies
00:07:B2  Transaccess S.a.
00:07:B3  Cisco Systems Inc.
00:07:B4  Cisco Systems Inc.
00:07:B5  Any One Wireless Ltd.
00:07:B6  Telecom Technology Ltd.
00:07:B7  Samurai Ind. Prods Eletronicos Ltda
00:07:B8  American Predator Corp.
00:07:B9  Ginganet Corporation
00:07:BA  Xebeo Communications, Inc.
00:07:BB  Confluence Networks
00:07:BC  Identix Inc.
00:07:BD  Radionet Ltd.
00:07:BE  Datalogic Spa
00:07:BF  Armillaire Technologies, Inc.
00:07:C0  Netzerver Inc.
00:07:C1  Overture Networks, Inc.
00:07:C2  Netsys Telecom
00:07:C3  Cirpack
00:07:C4  Jean Co. Ltd.
00:07:C5  Gcom, Inc.
00:07:C6  Vds Vosskuhler Gmbh
00:07:C7  Synectics Systems Limited
00:07:C8  Brain21, Inc.
00:07:C9  Technol Seven Co., Ltd.
00:07:CA  Creatix Polymedia Ges Fur Kommunikaitonssysteme
00:07:CB  Freebox Sa
00:07:CC  Kaba Benzing Gmbh
00:07:CD  Nmtel Co., Ltd.
00:07:CE  Cabletime Limited
00:07:CF  Anoto Ab
00:07:D0  Automat Engenharia De Automaoa Ltda.
00:07:D1  Spectrum Signal Processing Inc.
00:07:D2  Logopak Systeme
00:07:D3  Stork Digital Imaging B.v.
00:07:D4  Zhejiang Yutong Network Communication Co Ltd.
00:07:D5  3e Technologies Int;., Inc.
00:07:D6  Commil Ltd.
00:07:D7  Caporis Networks Ag
00:07:D8  Hitron Systems Inc.
00:07:D9  Splicecom
00:07:DA  Neuro Telecom Co., Ltd.
00:07:DB  Kirana Networks, Inc.
00:07:DC  Atek Co, Ltd.
00:07:DD  Cradle Technologies
00:07:DE  Ecopilt Ab
00:07:DF  Vbrick Systems Inc.
00:07:E0  Palm Inc.
00:07:E1  Wis Communications Co. Ltd.
00:07:E2  Bitworks, Inc.
00:07:E3  Navcom Technology, Inc.
00:07:E4  Softradio Co., Ltd.
00:07:E5  Coup Corporation
00:07:E6  Edgeflow Canada Inc.
00:07:E7  Freewave Technologies
00:07:E8  St. Bernard Software
00:07:E9  Intel Corporation
00:07:EA  Massana, Inc.
00:07:EB  Cisco Systems Inc.
00:07:EC  Cisco Systems Inc.
00:07:ED  Altera Corporation
00:07:EE  Telco Informationssysteme Gmbh
00:07:EF  Lockheed Martin Tactical Systems
00:07:F0  Logisync Corporation
00:07:F1  Teraburst Networks Inc.
00:07:F2  Ioa Corporation
00:07:F3  Think Engine Networks
00:07:F4  Eletex Co., Ltd.
00:07:F5  Bridgeco Co Ag
00:07:F6  Qqest Software Systems
00:07:F7  Galtronics
00:07:F8  Itdevices, Inc.
00:07:F9  Phonetics, Inc.
00:07:FA  Itt Co., Ltd.
00:07:FB  Giga Stream Umts Technologies Gmbh
00:07:FC  Adept Systems Inc.
00:07:FD  Lanergy Ltd.
00:07:FE  Rigaku Corporation
00:07:FF  Gluon Networks
00:08:00  Multitech Systems, Inc.
00:08:01  Highspeed Surfing Inc.
00:08:02  Compaq Computer Corporation
00:08:03  Cos Tron
00:08:04  Ica Inc.
00:08:05  Techno-holon Corporation
00:08:06  Raonet Systems, Inc.
00:08:07  Access Devices Limited
00:08:08  Ppt Vision, Inc.
00:08:09  Systemonic Ag
00:08:0A  Espera-werke Gmbh
00:08:0B  Birka Bpa Informationssystem Ab
00:08:0C  Vda Elettronica Srl
00:08:0D  Toshiba
00:08:0E  Motorola, Bcs
00:08:0F  Proximion Fiber Optics Ab
00:08:10  Key Technology, Inc.
00:08:11  Voix Corporation
00:08:12  Gm-2 Corporation
00:08:13  Diskbank, Inc.
00:08:14  Til Technologies
00:08:15  Cats Co., Ltd.
00:08:16  Bluetags A/s
00:08:17  Emergecore Networks Llc
00:08:18  Pixelworks, Inc.
00:08:19  Banksys
00:08:1A  Sanrad Intelligence Storage Communications (2000) Ltd.
00:08:1B  Windigo Systems
00:08:1C  @pos.com
00:08:1D  Ipsil, Incorporated
00:08:1E  Repeatit Ab
00:08:1F  Pou Yuen Tech Corp. Ltd.
00:08:20  Cisco Systems Inc.
00:08:21  Cisco	AIR-PCM352
00:08:22  Inpro Comm
00:08:23  Texa Corp.
00:08:24  Promatek Industries Ltd.
00:08:25  Acme Packet
00:08:26  Colorado Med Tech
00:08:27  Pirelli Cables & Systems
00:08:28  Koei Engineering Ltd.
00:08:29  Aval Nagasaki Corporation
00:08:2A  Powerwallz Network Security
00:08:2B  Wooksung Electronics, Inc.
00:08:2C  Homag Ag
00:08:2D  Indus Teqsite Private Limited
00:08:2E  Multitone Electronics Plc
00:08:4E  Divergenet, Inc.
00:08:4F  Qualstar Corporation
00:08:50  Arizona Instrument Corp.
00:08:51  Canadian Bank Note Company, Ltd.
00:08:52  Davolink Co. Inc.
00:08:53  Schleicher Gmbh & Co. Relaiswerke Kg
00:08:54  Netronix, Inc.
00:08:55  Nasa-goddard Space Flight Center
00:08:56  Gamatronic Electronic Industries Ltd.
00:08:57  Polaris Networks, Inc.
00:08:58  Novatechnology Inc.
00:08:59  Shenzhen Unitone Electronics Co., Ltd.
00:08:5A  Intigate Inc.
00:08:5B  Hanbit Electronics Co., Ltd.
00:08:5C  Shanghai Dare Technologies Co. Ltd.
00:08:5D  Aastra
00:08:5E  Pco Computer Optics Gmbh
00:08:5F  Picanol N.v.
00:08:60  Lodgenet Entertainment Corp.
00:08:61  Softenergy Co., Ltd.
00:08:62  Nec Eluminant Technologies, Inc.
00:08:63  Entrisphere Inc.
00:08:64  Fasy S.p.a.
00:08:65  Jascom Co., Ltd
00:08:66  Dsx Access Systems, Inc.
00:08:67  Uptime Devices
00:08:68  Puroptix
00:08:69  Command-e Technology Co.,ltd.
00:08:6A  Industrie Technik Ips Gmbh
00:08:6B  Mipsys
00:08:6C  Plasmon Lms
00:08:6D  Missouri Freenet
00:08:6E  Hyglo Ab
00:08:6F  Resources Computer Network Ltd.
00:08:70  Rasvia Systems, Inc.
00:08:71  Northdata Co., Ltd.
00:08:72  Sorenson Technologies, Inc.
00:08:73  Dap Design B.v.
00:08:74  Dell Computer Corp.
00:08:75  Acorp Electronics Corp.
00:08:76  Sdsystem
00:08:77  Liebert Hiross S.p.a.
00:08:78  Benchmark Storage Innovations
00:08:79  Cem Corporation
00:08:7A  Wipotec Gmbh
00:08:7B  Rtx Telecom A/s
00:08:7C  Cisco Systems, Inc.
00:08:7D  Cisco Systems Inc.
00:08:7E  Bon Electro-telecom Inc.
00:08:7F  Spaun Electronic Gmbh & Co. Kg
00:08:80  Broadtel Canada Communications Inc.
00:08:81  Digital Hands Co.,ltd.
00:08:82  Sigma Corporation
00:08:83  Hewlett-packard Company
00:08:84  Index Braille Ab
00:08:85  Ems Dr. Thomas Wuensche
00:08:86  Hansung Teliann, Inc.
00:08:87  Private
00:08:88  Oullim Information Technology Inc,.
00:08:89  Echostar Technologies Corp
00:08:8A  Minds@work
00:08:8B  Tropic Networks Inc.
00:08:8C  Quanta Network Systems Inc.
00:08:8D  Sigma-links Inc.
00:08:8E  Nihon Computer Co., Ltd.
00:08:8F  Advanced Digital Technology
00:08:90  Avilinks Sa
00:08:91  Lyan Inc.
00:08:92  Em Solutions
00:08:93  Private
00:08:94  Innovision Multimedia Ltd.
00:08:95  Private
00:08:96  Printronix, Inc.
00:08:97  Quake Technologies
00:08:98  Gigabit Optics Corporation
00:08:99  Netbind, Inc.
00:08:9A  Alcatel Microelectronics
00:08:9B  Icp Electronics Inc.
00:08:9C  Elecs Industry Co., Ltd.
00:08:9D  Uhd-elektronik
00:08:9E  Beijing Enter-net Co.ltd
00:08:9F  Efm Networks
00:08:A0  Stotz Feinmesstechnik Gmbh
00:08:A1  Cnet Technology Inc.
00:08:A2  Adi Engineering, Inc.
00:08:A3  Cisco Systems
00:08:A4  Cisco Systems
00:08:A5  Peninsula Systems Inc.
00:08:A6  Multiware & Image Co., Ltd.
00:08:A7  Ilogic Inc.
00:08:A8  Systec Co., Ltd.
00:08:A9  Sangsang Technology, Inc.
00:08:AA  Karam
00:08:AB  Enerlinx.com, Inc.
00:08:AC  Private
00:08:AD  Toyo-linx Co., Ltd.
00:08:AE  Packetfront
00:08:AF  Novatec Corporation
00:08:B0  Bktel Communications Gmbh
00:08:B1  Proquent Systems
00:08:B2  Shenzhen Compass Technology Development Co.,ltd
00:08:B3  Fastwel
00:08:B4  Syspol
00:08:B5  Tai Guen Enterprise Co., Ltd
00:08:B6  Routefree, Inc.
00:08:B7  Hit Incorporated
00:08:B8  E.f. Johnson
00:08:B9  Kaon Media Co., Ltd.
00:08:BA  Erskine Systems Ltd
00:08:BB  Netexcell
00:08:BC  Ilevo Ab
00:08:BD  Tepg-us
00:08:BE  Xenpak Msa Group
00:08:BF  Aptus Elektronik Ab
00:08:C0  Asa Systems
00:08:C1  Avistar Communications Corporation
00:08:C2  Cisco Systems
00:08:C3  Contex A/s
00:08:C4  Private
00:08:C5  Liontech Co., Ltd.
00:08:C6  Philips Consumer Communications
00:08:C7  Compaq Computer Corporation
00:08:C8  Soneticom, Inc.
00:08:C9  Technisat Digital Gmbh
00:08:CA  Twinhan Technology Co.,ltd
00:08:CB  Zeta Broadband Inc.
00:08:CC  Remotec, Inc.
00:08:CD  With-net Inc
00:08:CE  Private
00:08:CF  Nippon Koei Power Systems Co., Ltd.
00:08:D0  Musashi Engineering Co., Ltd.
00:08:D1  Karel Inc.
00:08:D2  Zoom Networks Inc.
00:08:D3  Hercules Technologies S.a.
00:08:D4  Ineoquest Technologies, Inc
00:08:D5  Vanguard Managed Solutions
00:08:D6  Hassnet Inc.
00:08:D7  How Corporation
00:08:D8  Dowkey Microwave
00:08:D9  Mitadenshi Co.,ltd
00:08:DA  Sofaware Technologies Ltd.
00:08:DB  Corrigent Systems
00:08:DC  Wiznet
00:08:DD  Telena Communications, Inc.
00:08:DE  3up Systems
00:08:DF  Alistel Inc.
00:08:E0  Ato Technology Ltd.
00:08:E1  Barix Ag
00:08:E2  Cisco Systems
00:08:E3  Cisco Systems
00:08:E4  Envenergy Inc
00:08:E5  Idk Corporation
00:08:E6  Littlefeet
00:08:E7  Shi Controlsystems,ltd.
00:08:E8  Excel Master Ltd.
00:08:E9  Nextgig
00:08:EA  Motion Control Engineering, Inc
00:08:EB  Romwin Co.,ltd.
00:08:EC  Zonu, Inc.
00:08:ED  St&t Instrument Corp.
00:08:EE  Logic Product Development
00:08:EF  Dibal,s.a.
00:08:F0  Next Generation Systems, Inc.
00:08:F1  Voltaire
00:08:F2  Private
00:08:F3  Wany
00:08:F4  Bluetake Technology Co., Ltd.
00:08:F5  Yestechnology Co.,ltd.
00:08:F6  Sumitomo Electric Hightechs.co.,ltd.
00:08:F7  Hitachi Ltd, Semiconductor &amp; Integrated Circuits Gr
00:08:F8  Guardall Ltd
00:08:F9  Padcom, Inc.
00:08:FA  Karl E.brinkmann Gmbh
00:08:FB  Private
00:08:FC  Gigaphoton Inc.
00:08:FD  Bluekorea Co., Ltd.
00:08:FE  Private
00:08:FF  Trilogy Broadcast (holdings) Ltd
00:09:00  Tmt
00:09:01  Shenzhen Shixuntong Information & Technoligy Co
00:09:02  Redline Communications Inc.
00:09:03  Panasas, Inc
00:09:04  Mondial Electronic
00:09:05  Itec Technologies Ltd.
00:09:06  Esteem Networks
00:09:07  Chrysalis Development
00:09:08  Vtech Technology Corp.
00:09:09  Telenor Connect A/s
00:09:0A  Snedfar Technology Co., Ltd.
00:09:0B  Mtl  Instruments Plc
00:09:0C  Mayekawa Mfg. Co. Ltd.
00:09:0D  Private
00:09:0E  Helix Technology Inc.
00:09:0F  Private
00:09:10  Simple Access Inc.
00:09:11  Cisco Systems
00:09:12  Cisco Systems
00:09:13  Private
00:09:14  Computrols Inc.
00:09:15  Cas Corp.
00:09:16  Listman Home Technologies, Inc.
00:09:17  Wem Technology Inc
00:09:18  Samsung Techwin Co.,ltd
00:09:19  Mds Gateways
00:09:1A  Macat Optics & Electronics Co., Ltd.
00:09:1B  Digital Generation Inc.
00:09:1C  Cachevision, Inc
00:09:1D  Proteam Computer Corporation
00:09:1E  Firstech Technology Corp.
00:09:1F  A&amp;d Co., Ltd.
00:09:20  Private
00:09:21  Planmeca Oy
00:09:22  Touchless Sensor Technology Ag
00:09:23  Heaman System Co., Ltd
00:09:24  Telebau Gmbh
00:09:25  Vsn Systemen Bv
00:09:26  Yoda Communications, Inc.
00:09:27  Toyokeiki Co.,ltd.
00:09:28  Telecore Inc
00:09:29  Sanyo Industries (uk) Limited
00:09:2A  Mytecs Co.,ltd.
00:09:2B  Iqstor Networks, Inc.
00:09:2C  Hitpoint Inc.
00:09:2D  High Tech Computer, Corp.
00:09:2E  B&tech System Inc.
00:09:2F  Akom Technology Corporation
00:09:30  Aeroconcierge Inc.
00:09:31  Future Internet, Inc.
00:09:32  Omnilux
00:09:33  Optovalley Co. Ltd.
00:09:34  Dream-multimedia-tv Gmbh
00:09:35  Sandvine Incorporated
00:09:36  Ipetronik Gmbh & Co.kg
00:09:37  Inventec Appliance Corp
00:09:38  Allot Communications
00:09:39  Shibasoku Co.,ltd.
00:09:3A  Molex Fiber Optics
00:09:3B  Hyundai Networks Inc.
00:09:3C  Jacques Technologies P/l
00:09:3D  Private
00:09:3E  C&i Technologies
00:09:3F  Double-win Enterpirse Co., Ltd
00:09:40  Agfeo Gmbh & Co. Kg
00:09:41  Allied Telesis K.k.
00:09:42  Cresco, Ltd.
00:09:43  Cisco	AIR-LMC352
00:09:44  Cisco Systems
00:09:45  Palmmicro Communications Inc
00:09:46  Cluster Labs Gmbh
00:09:47  Aztek, Inc.
00:09:48  Vista Control Systems, Corp.
00:09:49  Glyph Technologies Inc.
00:09:4A  Homenet Communications
00:09:4B  Fillfactory Nv
00:09:4C  Communication Weaver Co.,ltd.
00:09:4D  Braintree Communications Pty Ltd
00:09:4E  Bartech Systems International, Inc
00:09:4F  Private
00:09:50  Independent Storage Corporation
00:09:51  Private
00:09:52  Auerswald Gmbh & Co. Kg
00:09:53  Linkage System Integration Co.ltd.
00:09:54  Amit Spol. S. R. O.
00:09:55  Young Generation International Corp.
00:09:56  Network Systems Group, Ltd. (nsg)
00:09:57  Supercaller, Inc.
00:09:58  Intelnet S.a.
00:09:59  Sitecsoft
00:09:5A  Racewood Technology
00:09:5B  Netgear MA701, MA401RA
00:09:5C  Private
00:09:5D  Dialogue Technology Corp.
00:09:5E  Masstech Group Inc.
00:09:5F  Telebyte, Inc.
00:09:60  Yozan Inc.
00:09:61  Switchgear And Instrumentation Ltd
00:09:62  Filetrac As
00:09:63  Private
00:09:64  Hi-techniques
00:09:65  Private
00:09:66  Thales Navigation
00:09:67  Tachyon, Inc
00:09:68  Technoventure, Inc.
00:09:69  Meret Optical Communications
00:09:6A  Cloverleaf Communications Inc.
00:09:6B  Ibm Corporation
00:09:6C  Imedia Semiconductor Corp.
00:09:6D  Powernet Technologies Corp.
00:09:6E  Giant Electronics Ltd.
00:09:6F  Beijing Zhongqing Elegant Tech. Corp.,limited
00:09:70  Vibration Research Corporation
00:09:71  Time Management, Inc.
00:09:72  Securebase,inc
00:09:73  Lenten Technology Co., Ltd.
00:09:74  Innopia Technologies, Inc.
00:09:75  Fsona Communications Corporation
00:09:76  Private
00:09:77  Brunner Elektronik Ag
00:09:78  Aiji System Co., Ltd.
00:09:79  Advanced Television Systems Committee, Inc.
00:09:7A  Louis Design Labs.
00:09:7B  Cisco Systems
00:09:7C  Cisco	AIR-LMC352
00:09:7D  Secwell Networks Oy
00:09:7E  Imi Technology Co., Ltd
00:09:7F  Private
00:09:80  Power Zenith Inc.
00:09:81  Newport Networks
00:09:82  Loewe Opta Gmbh
00:09:83  Gvision Incorporated
00:09:84  Mycasa Network Inc.
00:09:85  Auto Telecom Company
00:09:86  Metalink Ltd.
00:09:87  Nishi Nippon Electric Wire & Cable Co.,ltd.
00:09:88  Nudian Electron Co., Ltd.
00:09:89  Vividlogic Inc.
00:09:8A  Equallogic Inc
00:09:8B  Entropic Communications, Inc.
00:09:8C  Possio Ab
00:09:8D  Dct Ltd (digital Communication Technologies Ltd)
00:09:8E  Ipcas Gmbh
00:09:8F  Cetacean Networks
00:09:90  Acksys Communications & Systems
00:09:91  Ge Fanuc Automation Manufacturing, Inc.
00:09:92  Interepoch Technology,inc.
00:09:93  Visteon Corporation
00:09:94  Cronyx Engineering
00:09:95  Castle Technology Ltd
00:09:96  Rdi
00:09:97  Nortel Networks
00:09:98  Private
00:09:99  Cp Georges Renault
00:09:9A  Elmo Company, Limited
00:09:9B  Western Telematic Inc.
00:09:9C  Naval Research Laboratory
00:09:9D  Haliplex Communications
00:09:9E  Testech, Inc.
00:09:9F  Private
00:09:A0  Microtechno Corporation
00:09:A1  Telewise Communications, Inc.
00:09:A2  Interface Co., Ltd.
00:09:A3  Leadfly Techologies Corp. Ltd.
00:09:A4  Hartec Corporation
00:09:A5  Hansung Eletronic Industries Development Co., Ltd
00:09:A6  Ignis Optics, Inc.
00:09:A7  Bang & Olufsen A/s
00:09:A8  Eastmode Pte Ltd
00:09:A9  Ikanos Communications
00:09:AA  Data Comm For Business, Inc.
00:09:AB  Netcontrol Oy
00:09:AC  Lanvoice
00:09:AD  Hyundai Syscomm, Inc.
00:09:AE  Okano Electric Co.,ltd
00:09:AF  E-generis
00:09:B0  Onkyo Corporation
00:09:B1  Kanematsu Electronics, Ltd.
00:09:B2  L&f Inc.
00:09:B3  Mcm Systems Ltd
00:09:B4  Kisan Telecom Co., Ltd.
00:09:B5  3j Tech. Co., Ltd.
00:09:B6  Cisco Systems
00:09:B7  Cisco Systems
00:09:B8  Entise Systems
00:09:B9  Action Imaging Solutions
00:09:BA  Maku Informationstechik Gmbh
00:09:BB  Mathstar, Inc.
00:09:BC  Private
00:09:BD  Epygi Technologies, Ltd.
00:09:BE  Mamiya-op Co.,ltd.
00:09:BF  Nintendo Co.,ltd.
00:09:C0  6wind
00:09:C1  Proces-data A/s
00:09:C2  Private
00:09:C3  Netas
00:09:C4  Medicore Co., Ltd
00:09:C5  Kingene Technology Corporation
00:09:C6  Visionics Corporation
00:09:C7  Movistec
00:09:C8  Sinagawa Tsushin Keisou Service
00:09:C9  Bluewinc Co., Ltd.
00:09:CA  Imaxnetworks(shenzhen)limited.
00:09:CB  Hbrain
00:09:CC  Moog Gmbh
00:09:CD  Hudson Soft Co.,ltd.
00:09:CE  Spacebridge Semiconductor Corp.
00:09:CF  Iad Gmbh
00:09:D0  Versatel Networks
00:09:D1  Seranoa Networks Inc
00:09:D2  Mai Logic Inc.
00:09:D3  Western Datacom Co., Inc.
00:09:D4  Transtech Networks
00:09:D5  Signal Communication, Inc.
00:09:D6  Knc One Gmbh
00:09:D7  Dc Security Products
00:09:D8  Private
00:09:D9  Private
00:09:DA  Control Module Inc.
00:09:DB  Espace
00:09:DC  Galaxis Technology Ag
00:09:DD  Mavin Technology Inc.
00:09:DE  Samjin Information & Communications Co., Ltd.
00:09:DF  Vestel Komunikasyon Sanayi Ve Ticaret A.s.
00:09:E0  Xemics S.a.
00:09:E1  Gemtek Technology Co., Ltd.
00:09:E2  Sinbon Electronics Co., Ltd.
00:09:E3  Angel Iglesias S.a.
00:09:E4  K Tech Infosystem Inc.
00:09:E5  Hottinger Baldwin Messtechnik Gmbh
00:09:E6  Cyber Switching Inc.
00:09:E7  Adc Techonology
00:09:E8  Cisco	AIR-LMC352
00:09:E9  Cisco Systems
00:09:EA  Yem Inc.
00:09:EB  Humandata Ltd.
00:09:EC  Daktronics, Inc.
00:09:ED  Cipheroptics
00:09:EE  Meikyo Electric Co.,ltd
00:09:EF  Vocera Communications
00:09:F0  Shimizu Technology Inc.
00:09:F1  Yamaki Electric Corporation
00:09:F2  Cohu, Inc., Electronics Division
00:09:F3  Well Communication Corp.
00:09:F4  Alcon Laboratories, Inc.
00:09:F5  Emerson Network Power Co.,ltd
00:09:F6  Shenzhen Eastern Digital Tech Ltd.
00:09:F7  Sed, A Division Of Calian
00:09:F8  Unimo Technology Co., Ltd.
00:09:F9  Art Japan Co., Ltd.
00:09:FB  Philips Medizinsysteme Boeblingen Gmbh
00:09:FC  Ipflex Inc.
00:09:FD  Ubinetics Limited
00:09:FE  Daisy Technologies, Inc.
00:09:FF  X.net 2000 Gmbh
00:0A:00  Mediatek Corp.
00:0A:01  Sohoware, Inc.
00:0A:02  Annso Co., Ltd.
00:0A:03  Endesa Servicios, S.l.
00:0A:04  3com Europe Ltd
00:0A:05  Widax Corp.
00:0A:06  Teledex Llc
00:0A:07  Beijing Comsys Technologies Co.,ltd.
00:0A:08  Alpine Electronics, Inc.
00:0A:09  Private
00:0A:0A  Sunix Co., Ltd.
00:0A:0B  Sealevel Systems, Inc.
00:0A:0C  Scientific Research Corporation
00:0A:0D  Mergeoptics Gmbh
00:0A:0E  Invivo Research Inc.
00:0A:0F  Ilryung Telesys, Inc
00:0A:10  Fast Media Integrations Ag
00:0A:11  Expet Technologies, Inc
00:0A:12  Azylex Technology, Inc
00:0A:13  Silent Witness
00:0A:14  Teco A.s.
00:0A:15  Silicon Data, Inc
00:0A:16  Lassen Research
00:0A:17  Nestar Communications, Inc
00:0A:18  Vichel Inc.
00:0A:19  Valere Power, Inc.
00:0A:1A  Imerge Ltd
00:0A:1B  Stream Labs
00:0A:1C  Bridge Information Co., Ltd.
00:0A:1D  Optical Communications Products Inc.
00:0A:1E  Red-m (communications) Limited
00:0A:1F  Art Ware Telecommunication Co., Ltd.
00:0A:20  Sva Networks, Inc.
00:0A:21  Integra Telecom Co. Ltd
00:0A:22  Amperion Inc
00:0A:23  Parama Networks Inc
00:0A:24  Octave Communications
00:0A:25  Ceragon Networks
00:0A:26  Private
00:0A:27  Apple Computer, Inc.
00:0A:28  Motorola Personal Communications Sector
00:0A:29  Pan Dacom Networking Ag
00:0A:2A  Qsi Systems Inc.
00:0A:2B  Etherstuff
00:0A:2C  Active Tchnology Corporation
00:0A:2D  Private
00:0A:2E  Maple Networks Co., Ltd
00:0A:2F  Private
00:0A:30  Johnson Controls-asg
00:0A:31  Hcv Wireless
00:0A:32  Xsido Corporation
00:0A:33  Sierra Logic, Inc.
00:0A:34  Identicard Systems Incorporated
00:0A:35  Xilinx
00:0A:36  Synelec Telecom Multimedia
00:0A:37  Procera Networks, Inc.
00:0A:38  Netlock Technologies, Inc.
00:0A:39  Private
00:0A:3A  J-three International Holding Co., Ltd.
00:0A:3B  Gct Semiconductor, Inc
00:0A:3C  Enerpoint Ltd.
00:0A:3D  Elo Sistemas Eletronicos S.a.
00:0A:3E  Eads Telecom
00:0A:3F  Data East Corporation
00:0A:40  Crown Audio
00:0A:41  Cisco	AIR-PCM352
00:0A:42  Cisco Systems
00:0A:43  Chunghwa Telecom Co., Ltd.
00:0A:44  Avery Dennison Deutschland Gmbh
00:0A:45  Audio-technica Corp.
00:0A:46  Aro Controls Sas
00:0A:47  Allied Vision Technologies
00:0A:48  Albatron Technology
00:0A:49  Acopia Networks
00:0A:4A  Targa Systems Ltd.
00:0A:4B  Datapower Technology, Inc.
00:0A:4C  Molecular Devices Corporation
00:0A:4D  Noritz Corporation
00:0A:4E  Unitek Electronics Inc.
00:0A:4F  Brain Boxes Limited
00:0A:50  Remotek Corporation
00:0A:51  Gyrosignal Technology Co., Ltd.
00:0A:52  Venitek Co. Ltd.
00:0A:53  Intronics, Incorporated
00:0A:54  Laguna Hills, Inc.
00:0A:55  Markem Corporation
00:0A:56  Hitachi Maxell Ltd.
00:0A:57  Hewlett-packard Company - Standards
00:0A:58  Ingenieur-buero Freyer & Siegel
00:0A:59  Hw Server
00:0A:5A  Greennet Technologies Co.,ltd.
00:0A:5B  Power-one As
00:0A:5C  Carel S.p.a.
00:0A:5D  Puc Founder (msc) Berhad
00:0A:5E  3com Corporation
00:0A:5F  Almedio Inc.
00:0A:60  Autostar Technology Pte Ltd
00:0A:61  Cellinx Systems Inc.
00:0A:62  Crinis Networks, Inc.
00:0A:63  Dhd Gmbh
00:0A:64  Eracom Technologies
00:0A:65  Gentechmedia.co.,ltd.
00:0A:66  Mitsubishi Electric System & Service Co.,ltd.
00:0A:67  Ongcorp
00:0A:68  Solarflare Communications, Inc.
00:0A:69  Sunny Bell Technology Co., Ltd.
00:0A:6A  Svm Microwaves S.r.o.
00:0A:6B  Tadiran Telecom Business Systems Ltd
00:0A:6C  Walchem Corporation
00:0A:6D  Eks Elektronikservice Gmbh
00:0A:6E  Broadcast Technology Limited
00:0A:6F  Zytera Technologies Inc.
00:0A:70  Mpls Forum
00:0A:71  Avrio Technologies, Inc
00:0A:72  Simpletech, Inc.
00:0A:73  Scientific Atlanta
00:0A:74  Manticom Networks Inc.
00:0A:75  Cat Electronics
00:0A:76  Beida Jade Bird Huaguang Technology Co.,ltd
00:0A:77  Bluewire Technologies Llc
00:0A:78  Olitec
00:0A:79  Corega K.k.
00:0A:7A  Kyoritsu Electric Co., Ltd.
00:0A:7B  Private
00:0A:7C  Tecton Ltd
00:0A:7D  Valo, Inc.
00:0A:7E  The Advantage Group
00:0A:7F  Teradon Industries, Inc
00:0A:80  Telkonet Inc.
00:0A:81  Teima Audiotex S.l.
00:0A:82  Tatsuta System Electronics Co.,ltd.
00:0A:83  Salto Systems S.l.
00:0A:84  Rainsun Enterprise Co., Ltd.
00:0A:85  Plat'c2,inc
00:0A:86  Lenze
00:0A:87  Integrated Micromachines Inc.
00:0A:88  Incypher S.a.
00:0A:89  Creval Systems, Inc.
00:0A:8A  Cisco	AIR-PCM352
00:0A:8B  Cisco Systems
00:0A:8C  Guardware Systems Ltd.
00:0A:8D  Eurotherm Limited
00:0A:8E  Invacom Ltd
00:0A:8F  Aska International Inc.
00:0A:90  Bayside Interactive, Inc.
00:0A:91  Hemocue Ab
00:0A:92  Presonus Corporation
00:0A:93  W2 Networks, Inc.
00:0A:94  Shanghai Cellink Co., Ltd
00:0A:95  Apple Computer, Inc.
00:0A:96  Mewtel Technology Inc.
00:0A:97  Sonicblue, Inc.
00:0A:98  M+f Gwinner Gmbh & Co
00:0A:99  Dataradio Inc.
00:0A:9A  Aiptek International Inc
00:0A:9B  Towa Meccs Corporation
00:0A:9C  Server Technology, Inc.
00:0A:9D  King Young Technology Co. Ltd.
00:0A:9E  Broadweb Corportation
00:0A:9F  Private
00:0A:A0  Cedar Point Communications
00:0A:A1  V V S Limited
00:0A:A2  Systek Inc.
00:0A:A3  Shimafuji Electric Co.,ltd.
00:0A:A4  Shanghai Surveillance Technology Co,ltd
00:0A:A5  Maxlink Industries Limited
00:0A:A6  Hochiki Corporation
00:0A:A7  Fei Company
00:0A:A8  Epipe Pty. Ltd.
00:0A:A9  Brooks Automation Gmbh
00:0A:AA  Altigen Communications Inc.
00:0A:AB  Toyota Macs, Inc.
00:0A:AC  Terratec Electronic Gmbh
00:0A:AD  Stargames Corporation
00:0A:AE  Rosemount Process Analytical
00:0A:AF  Private
00:0A:B0  Loytec Electronics Gmbh
00:0A:B1  Genetec Corporation
00:0A:B2  Fresnel Wireless Systems
00:0A:B3  Fa. Gira
00:0A:B4  Etic Telecommunications
00:0A:B5  Digital Electronic Network
00:0A:B6  Compunetix, Inc
00:0A:B7  Cisco Systems
00:0A:B8  Cisco Systems
00:0A:B9  Astera Technologies Corp.
00:0A:BA  Arcon Technology Limited
00:0A:BB  Taiwan Secom Co,. Ltd
00:0A:BC  Seabridge Ltd.
00:0A:BD  Private
00:0A:BE  Opnet Technologies Co., Ltd.
00:0A:BF  Hirota Ss
00:0A:C0  Fuyoh Video Industry Co., Ltd.
00:0A:C1  Futuretel
00:0A:C2  Fiberhome Telecommunication Technologies Co.,ltd
00:0A:C3  Em Technics Co., Ltd.
00:0A:C4  Daewoo Teletech Co., Ltd
00:0A:C5  Color Kinetics
00:0A:C6  Private
00:0A:C7  Unication Group
00:0A:C8  Zpsys Co.,ltd. (planning&management)
00:0A:C9  Zambeel Inc
00:0A:CA  Yokoyama Shokai Co.,ltd.
00:0A:CB  Xpak Msa Group
00:0A:CC  Winnow Networks, Inc.
00:0A:CD  Sunrich Technology Limited
00:0A:CE  Radiantech, Inc.
00:0A:CF  Provideo Multimedia Co. Ltd.
00:0A:D0  Niigata Develoment Center,  F.i.t. Co., Ltd.
00:0A:D1  Mws
00:0A:D2  Jepico Corporation
00:0A:D3  Initech Co., Ltd
00:0A:D4  Corebell Systems Inc.
00:0A:D5  Brainchild Electronic Co., Ltd.
00:0A:D6  Beamreach Networks
00:0A:D7  Private
00:0A:D8  Ipcserv Technology Corp.
00:0A:D9  Sony Ericsson Mobile Communications Ab
00:0A:DA  Private
00:0A:DB  Skypilot Network, Inc
00:0A:DC  Ruggedcom Inc.
00:0A:DD  Inscitek Microsystems, Inc.
00:0A:DE  Happy Communication Co., Ltd.
00:0A:DF  Gennum Corporation
00:0A:E0  Fujitsu Softek
00:0A:E1  Eg Technology
00:0A:E2  Binatone Electronics International, Ltd
00:0A:E3  Yang Mei Technology Co., Ltd
00:0A:E4  Wistron Corp.
00:0A:E5  Scottcare Corporation
00:0A:E6  Elitegroup Computer System Co. (ecs)
00:0A:E7  Eliop S.a.
00:0A:E8  Cathay Roxus Information Technology Co. Ltd
00:0A:E9  Airvast Technology Inc.
00:0A:EA  Adam Elektronik Ltd.sti.
00:0A:EB  Shenzhen Tp-link Technology Co; Ltd.
00:0A:EC  Koatsu Gas Kogyo Co., Ltd.
00:0A:ED  Harting Vending G.m.b.h. & Co Kg
00:0A:EE  Gcd Hard- & Software Gmbh
00:0A:EF  Otrum Asa
00:0A:F0  Shin-oh Electronics Co., Ltd. R&d
00:0A:F1  Clarity Design, Inc.
00:0A:F2  Neoaxiom Corp.
00:0A:F3  Cisco Systems
00:0A:F4  Cisco Systems
00:0A:F5  Airgo Networks, Inc.
00:0A:F6  Computer Process Controls
00:0A:F7  Broadcom Corp.
00:0A:F8  American Telecare Inc.
00:0A:F9  Private
00:0A:FA  Traverse Technologies Australia
00:0A:FB  Ambri Limited
00:0A:FC  Core Tec Communications, Llc
00:0A:FD  Viking Electronic Services
00:0A:FE  Novapal Ltd
00:0A:FF  Kilchherr Elektronik Ag
00:0B:00  Fujian Start Computer Equipment Co.,ltd
00:0B:01  Daiichi Electronics Co., Ltd.
00:0B:02  Dallmeier Electronic
00:0B:03  Taekwang Industrial Co., Ltd
00:0B:04  Volktek Corporation
00:0B:05  Pacific Broadband Networks
00:0B:06  Motorola Bcs
00:0B:07  Voxpath Networks
00:0B:08  Pillar Data Systems
00:0B:09  Ifoundry Systems Singapore
00:0B:0A  Dbm Optics
00:0B:0B  Corrent Corporation
00:0B:0C  Agile Systems Inc.
00:0B:0D  Air2u, Inc.
00:0B:0E  Trapeze Networks
00:0B:0F  Nyquist Industrial Control Bv
00:0B:10  11wave Technonlogy Co.,ltd
00:0B:11  Himeji Abc Trading Co.,ltd.
00:0B:12  Private
00:0B:13  Zetron Inc
00:0B:14  Viewsonic Corporation
00:0B:15  Platypus Technology
00:0B:16  Communication Machinery Corporation
00:0B:17  Mks Instruments
00:0B:18  Private
00:0B:19  Vernier Networks, Inc.
00:0B:1A  Teltone Corporation
00:0B:1B  Systronix, Inc.
00:0B:1C  Private
00:0B:1D  Layerzero Power Systems, Inc.
00:0B:1E  Kappa Opto-electronics Gmbh
00:0B:1F  I Con Computer Co.
00:0B:20  Hirata Corporation
00:0B:21  G-star Communications Inc.
00:0B:22  Environmental Systems And Services
00:0B:23  Efficient Networks, Inc.
00:0B:24  Airlogic
00:0B:25  Aeluros
00:0B:26  Wetek Corporation
00:0B:27  Scion Corporation
00:0B:28  Quatech Inc.
00:0B:29  Lg Industrial Systems Co.,ltd.
00:0B:2A  Howtel Co., Ltd.
00:0B:2B  Hostnet Corporation
00:0B:2C  Eiki Industrial Co. Ltd.
00:0B:2D  Danfoss Inc.
00:0B:2E  Cal-comp Electronics (thailand) Public Company Limited Taipe
00:0B:2F  Bplan Gmbh
00:0B:30  Beijing Gongye Science & Technology Co.,ltd
00:0B:31  Yantai Zhiyang Scientific And Technology Industry Co., Ltd
00:0B:32  Vormetric, Inc.
00:0B:33  Vivato
00:0B:34  Shanghai Broadband Technologies Co.ltd
00:0B:35  Quad Bit System Co., Ltd.
00:0B:36  Productivity Systems, Inc.
00:0B:37  Manufacture Des Montres Rolex Sa
00:0B:38  Knuerr Ag
00:0B:39  Keisoku Giken Co.,ltd.
00:0B:3A  Fortel Dtv, Inc.
00:0B:3B  Devolo Ag
00:0B:3C  Cygnal Integrated Products, Inc.
00:0B:3D  Contal Ok Ltd.
00:0B:3E  Bittware, Inc
00:0B:3F  Anthology Solutions Inc.
00:0B:40  Opnext Inc.
00:0B:41  Ing. Buero Dr. Beutlhauser
00:0B:42  Commax Co., Ltd.
00:0B:43  Microscan Systems, Inc.
00:0B:44  Concord Idea Corp.
00:0B:45  Cisco
00:0B:46  Cisco
00:0B:47  Advanced Energy
00:0B:48  Sofrel
00:0B:49  Rf-link System Inc.
00:0B:4A  Visimetrics (uk) Ltd
00:0B:4B  Visiowave Sa
00:0B:4C  Clarion (m) Sdn Bhd
00:0B:4D  Emuzed
00:0B:4E  Vertexrsi Antenna Products Division
00:0B:4F  Verifone, Inc.
00:0B:50  Oxygnet
00:0B:51  Micetek International Inc.
00:0B:52  Joymax Electronics Corp.
00:0B:53  Initium Co., Ltd.
00:0B:54  Bitmicro Networks, Inc.
00:0B:55  Adinstruments
00:0B:56  Cybernetics
00:0B:57  Silicon Laboratories
00:0B:58  Astronautics C.a  Ltd
00:0B:59  Scriptpro, Llc
00:0B:5A  Hyperedge
00:0B:5B  Rincon Research Corporation
00:0B:5C  Newtech Co.,ltd
00:0B:5D  Fujitsu Limited
00:0B:5E  Atmava Ltd
00:0B:5F  Cisco Systems
00:0B:60  Cisco Systems
00:0B:61  Friedrich Lütze Gmbh &co.
00:0B:62  Ingenieurbüro Ingo Mohnen
00:0B:63  Private
00:0B:64  Kieback & Peter Gmbh & Co Kg
00:0B:65  Sy.a.c. Srl
00:0B:66  Teralink Communications
00:0B:67  Topview Technology Corporation
00:0B:68  Addvalue Communications Pte Ltd
00:0B:69  Franke Finland Oy
00:0B:6A  Asiarock Incorporation
00:0B:6B  Wistron Neweb Corp.
00:0B:6C  Sychip Inc.
00:0B:6D  Solectron Japan Nakaniida
00:0B:6E  Neff Instrument Corp.
00:0B:6F  Media Streaming Networks Inc
00:0B:70  Load Technology, Inc.
00:0B:71  Litchfield Communications Inc.
00:0B:72  Lawo Ag
00:0B:73  Kodeos Communications
00:0B:74  Kingwave Technology Co., Ltd.
00:0B:75  Iosoft Ltd.
00:0B:76  Et&t Co. Ltd.
00:0B:77  Cogent Systems, Inc.
00:0B:78  Taifatech Inc.
00:0B:79  X-com, Inc.
00:0B:7A  Private
00:0B:7B  Test-um Inc.
00:0B:7C  Telex Communications
00:0B:7D  Solomon Extreme International Ltd.
00:0B:7E  Saginomiya Seisakusho Inc.
00:0B:7F  Omniwerks
00:0B:80  Private
00:0B:81  Kaparel Corporation
00:0B:82  Grandstream Networks, Inc.
00:0B:83  Datawatt B.v.
00:0B:84  Bodet
00:0B:85  Black Storm Networks
00:0B:86  Aruba Networks
00:0B:87  American Reliance Inc.
00:0B:88  Vidisco Ltd.
00:0B:89  Top Global Technology, Ltd.
00:0B:8A  Miteq Inc.
00:0B:8B  Kerajet, S.a.
00:0B:8C  Flextronics Israel
00:0B:8D  Avvio Networks
00:0B:8E  Ascent Corporation
00:0B:8F  Akita Electronics Systems Co.,ltd.
00:0B:90  Covaro Networks, Inc.
00:0B:91  Aglaia Gesellschaft Für Bildverarbeitung Und Kommunikation M
00:0B:92  Ascom Danmark A/s
00:0B:93  Barmag Electronic
00:0B:94  Digital Monitoring Products, Inc.
00:0B:95  Ebet Gaming Systems Pty Ltd
00:0B:96  Innotrac Diagnostics Oy
00:0B:97  Matsushita Electric Industrial Co.,ltd.
00:0B:98  Nicetechvision
00:0B:99  Sensable Technologies, Inc.
00:0B:9A  Shanghai Ulink Telecom Equipment Co. Ltd.
00:0B:9B  Sirius System Co, Ltd.
00:0B:9C  Tribeam Technologies, Inc.
00:0B:9D  Twinmos Technologies Inc.
00:0B:9E  Yasing Technology Corp.
00:0B:9F  Neue Elsa Gmbh
00:0B:A0  T&l Information Inc.
00:0B:A1  Syscom Ltd.
00:0B:A2  Sumitomo Electric Networks, Inc
00:0B:A3  Siemens Ag, I&s
00:0B:A4  Shiron Satellite Communications Ltd. (1996)
00:0B:A5  Quasar Cipta Mandiri, Pt
00:0B:A6  Miyakawa Electric Works Ltd.
00:0B:A7  Maranti Networks
00:0B:A8  Hanback Electronics Co., Ltd.
00:0B:A9  Private
00:0B:AA  Aiphone Co.,ltd
00:0B:AB  Advantech Technology (china) Co., Ltd.
00:0B:AC  3com Europe Ltd.
00:0B:AD  Pc-pos Inc.
00:0B:AE  Vitals System Inc.
00:0B:AF  Private
00:0B:B0  Sysnet Telematica Srl
00:0B:B1  Super Star Technology Co., Ltd.
00:0B:B2  Smallbig Technology
00:0B:B3  Rit Technologies Ltd.
00:0B:B4  Rdc Semiconductor Inc.,
00:0B:B5  Nstor Technologies, Inc.
00:0B:B6  Mototech Inc.
00:0B:B7  Micro Systems Co.,ltd.
00:0B:B8  Kihoku Electronic Co.
00:0B:B9  Imsys Ab
00:0B:BA  Harmonic Broadband Access Networks
00:0B:BB  Etin Systems Co., Ltd
00:0B:BC  En Garde Systems, Inc.
00:0B:BD  Connexionz Limited
00:0B:BE  Cisco Systems
00:0B:BF  Cisco Systems
00:0B:C0  China Iwncomm Co., Ltd.
00:0B:C1  Bay Microsystems, Inc.
00:0B:C2  Corinex Communication Corp.
00:0B:C3  Multiplex, Inc.
00:0B:C4  Biotronik Gmbh & Co
00:0B:C5  Smc Networks, Inc.
00:0B:C6  Isac, Inc.
00:0B:C7  Icet S.p.a.
00:0B:C8  Airflow Networks
00:0B:C9  Electroline Equipment
00:0B:CA  Datavan International Corporation
00:0B:CB  Fagor Automation , S. Coop
00:0B:CC  Jusan, S.a.
00:0B:CD  Compaq (hp)
00:0B:CE  Free2move Ab
00:0B:CF  Agfa Ndt Inc.
00:0B:D0  Ximeta Technology Americas Inc.
00:0B:D1  Aeronix, Inc.
00:0B:D2  Remopro Technology Inc.
00:0B:D3  Cd3o
00:0B:D4  Beijing Wise Technology & Science Development Co.ltd
00:0B:D5  Nvergence, Inc.
00:0B:D6  Paxton Access Ltd
00:0B:D7  Mbb Gelma Gmbh
00:0B:D8  Industrial Scientific Corp.
00:0B:D9  General Hydrogen
00:0B:DA  Eyecross Co.,inc.
00:0B:DB  Esg Pcba Test
00:0B:DC  Akcp
00:0B:DD  Tohoku Ricoh Co., Ltd.
00:0B:DE  Private
00:0B:DF  Shenzhen Routerd Networks Limited
00:0B:E0  Serconet Ltd.
00:0B:E1  Private
00:0B:E2  Lumenera Corporation
00:0B:E3  Key Stream Co., Ltd.
00:0B:E4  Hosiden Corporation
00:0B:E5  Hims Korea Co., Ltd.
00:0B:E6  Datel Electronics
00:0B:E7  Comflux Technology Inc.
00:0B:E8  Aoip
00:0B:E9  Private
00:0B:EA  Zultys Technologies
00:0B:EB  Systegra Ag
00:0B:EC  Nippon Electric Instrument, Inc.
00:0B:ED  Elm Inc.
00:0B:EE  Inc.jet, Incorporated
00:0B:EF  Code Corporation
00:0B:F0  Motex Products Co., Ltd.
00:0B:F1  Lap Laser Applikations
00:0B:F2  Chih-kan Technology Co., Ltd.
00:0B:F3  Bae Systems
00:0C:6E  Silicon Integrated Sys. Corp.
00:10:00  Cable Television Laboraties, Inc.
00:10:01  Mck Communications
00:10:02  Actia
00:10:03  Imatron, Inc.
00:10:04  The Brantley Coile Company,inc
00:10:05  Uec Commercial
00:10:06  Thales Contact Solutions Ltd.
00:10:07  Cisco Systems, Inc.
00:10:08  Vienna Systems Corporation
00:10:09  Horo Quartz
00:10:0A  Williams Communications Group
00:10:0B  Cisco Systems, Inc.
00:10:0C  Ito Co., Ltd.
00:10:0D  Cisco Systems, Inc.
00:10:0E  Micro Linear Coporation
00:10:0F  Industrial Cpu Systems
00:10:10  Initio Corporation
00:10:11  Cisco Systems, Inc.
00:10:12  Processor Systems (i) Pvt Ltd
00:10:13  Industrial Computer Source
00:10:14  Cisco Systems, Inc.
00:10:15  Oomon Inc.
00:10:16  T.sqware
00:10:17  Micos Gmbh
00:10:18  Broadcom Corporation
00:10:19  Sirona Dental Systems Gmbh & Co. Kg
00:10:1A  Picturetel Corp.
00:10:1B  Cornet Technology, Inc.
00:10:1C  Ohm Technologies Intl, Llc
00:10:1D  Winbond Electronics Corp.
00:10:1E  Matsushita Electronic Instruments Corp.
00:10:1F  Cisco Systems, Inc.
00:10:20  Welch Allyn, Data Collection
00:10:21  Encanto Networks, Inc.
00:10:22  Satcom Media Corporation
00:10:23  Flowwise Networks, Inc.
00:10:24  Nagoya Electric Works Co., Ltd
00:10:25  Grayhill Inc.
00:10:26  Accelerated Networks, Inc.
00:10:27  L-3 Communications East
00:10:28  Computer Technica, Inc.
00:10:29  Cisco Systems, Inc.
00:10:2A  Zf Microsystems, Inc.
00:10:2B  Umax Data Systems, Inc.
00:10:2C  Lasat Networks A/s
00:10:2D  Hitachi Software Engineering
00:10:2E  Network Systems & Technologies Pvt. Ltd.
00:10:2F  Cisco Systems, Inc.
00:10:30  Wi-lan, Inc.
00:10:31  Objective Communications, Inc.
00:10:32  Alta Technology
00:10:33  Accesslan Communications, Inc.
00:10:34  Gnp Computers
00:10:35  Elitegroup Computer Systems Co., Ltd
00:10:36  Inter-tel Integrated Systems
00:10:37  Cyq've Technology Co., Ltd.
00:10:38  Micro Research Institute, Inc.
00:10:39  Vectron Systems Ag
00:10:3A  Diamond Network Tech
00:10:3B  Hippi Networking Forum
00:10:3C  Ic Ensemble, Inc.
00:10:3D  Phasecom, Ltd.
00:10:3E  Netschools Corporation
00:10:3F  Tollgrade Communications, Inc.
00:10:40  Intermec Corporation
00:10:41  Bristol Babcock, Inc.
00:10:42  Alacritech
00:10:43  A2 Corporation
00:10:44  Innolabs Corporation
00:10:45  Nortel Networks
00:10:46  Alcorn Mcbride Inc.
00:10:47  Echo Eletric Co. Ltd.
00:10:48  Htrc Automation, Inc.
00:10:49  Shoreline Teleworks, Inc.
00:10:4A  The Parvuc Corporation
00:10:4B  3com Corporation
00:10:4C  Computer Access Technology
00:10:4D  Surtec Industries, Inc.
00:10:4E  Ceologic
00:10:4F  Storage Technology Corporation
00:10:50  Rion Co., Ltd.
00:10:51  Cmicro Corporation
00:10:52  Mettler-toledo (albstadt) Gmbh
00:10:53  Computer Technology Corp.
00:10:54  Cisco Systems, Inc.
00:10:55  Fujitsu Microelectronics, Inc.
00:10:56  Sodick Co., Ltd.
00:10:57  Rebel.com, Inc.
00:10:58  Arrowpoint Communications
00:10:59  Diablo Research Co. Llc
00:10:5A  3com Corporation
00:10:5B  Net Insight Ab
00:10:5C  Quantum Designs (h.k.) Ltd.
00:10:5D  Draeger Medical
00:10:5E  Hekimian Laboratories, Inc.
00:10:5F  In-snec
00:10:60  Billionton Systems, Inc.
00:10:61  Hostlink Corp.
00:10:62  Nx Server, Ilnc.
00:10:63  Starguide Digital Networks
00:10:64  Digital Equipment Corp.
00:10:65  Radyne Corporation
00:10:66  Advanced Control Systems, Inc.
00:10:67  Redback Networks, Inc.
00:10:68  Comos Telecom
00:10:69  Helioss Communications, Inc.
00:10:6A  Digital Microwave Corporation
00:10:6B  Sonus Networks, Inc.
00:10:6C  Infratec Plus Gmbh
00:10:6D  Integrity Communications, Inc.
00:10:6E  Tadiran Com. Ltd.
00:10:6F  Trenton Technology Inc.
00:10:70  Caradon Trend Ltd.
00:10:71  Advanet Inc.
00:10:72  Gvn Technologies, Inc.
00:10:73  Technobox, Inc.
00:10:74  Aten International Co., Ltd.
00:10:75  Maxtor Corporation
00:10:76  Eurem Gmbh
00:10:77  Saf Drive Systems, Ltd.
00:10:78  Nuera Communications, Inc.
00:10:79  Cisco Systems, Inc.
00:10:7A  Ambicom, Inc.
00:10:7B  Cisco Systems, Inc.
00:10:7C  P-com, Inc.
00:10:7D  Aurora Communications, Ltd.
00:10:7E  Bachmann Electronic Gmbh
00:10:7F  Crestron Electronics, Inc.
00:10:80  Metawave Communications
00:10:81  Dps, Inc.
00:10:82  Jna Telecommunications Limited
00:10:83  Hewlett-packard Company
00:10:84  K-bot Communications
00:10:85  Polaris Communications, Inc.
00:10:86  Atto Technology, Inc.
00:10:87  Xstreamis Plc
00:10:88  American Networks Inc.
00:10:89  Websonic
00:10:8A  Teralogic, Inc.
00:10:8B  Laseranimation Sollinger Gmbh
00:10:8C  Fujitsu Telecommunications Europe, Ltd.
00:10:8D  Johnson Controls, Inc.
00:10:8E  Hugh Symons Concept Technologies Ltd.
00:10:8F  Raptor Systems
00:10:90  Cimetrics, Inc.
00:10:91  No Wires Needed Bv
00:10:92  Netcore Inc.
00:10:93  Cms Computers, Ltd.
00:10:94  Adtech, Inc.
00:10:95  Thomson Multimedia, Inc.
00:10:96  Tracewell Systems, Inc.
00:10:97  Winnet Metropolitan Communications Systems, Inc.
00:10:98  Starnet Technologies, Inc.
00:10:99  Innomedia, Inc.
00:10:9A  Netline
00:10:9B  Vixel Corporation
00:10:9C  M-system Co., Ltd.
00:10:9D  Clarinet Systems, Inc.
00:10:9E  Aware, Inc.
00:10:9F  Pavo, Inc.
00:10:A0  Innovex Technologies, Inc.
00:10:A1  Kendin Semiconductor, Inc.
00:10:A2  Tns
00:10:A3  Omnitronix, Inc.
00:10:A4  Xircom
00:10:A5  Oxford Instruments
00:10:A6  Cisco Systems, Inc.
00:10:A7  Unex Technology Corporation
00:10:A8  Reliance Computer Corp.
00:10:A9  Adhoc Technologies
00:10:AA  Media4, Inc.
00:10:AB  Koito Industries, Ltd.
00:10:AC  Imci Technologies
00:10:AD  Softronics Usb, Inc.
00:10:AE  Shinko Electric Industries Co.
00:10:AF  Tac Systems, Inc.
00:10:B0  Meridian Technology Corp.
00:10:B1  For-a Co., Ltd.
00:10:B2  Coactive Aesthetics
00:10:B3  Nokia Multimedia Terminals
00:10:B4  Atmosphere Networks
00:10:B5  Accton Technology Corporation
00:10:B6  Entrata Communications Corp.
00:10:B7  Coyote Technologies, Llc
00:10:B8  Ishigaki Computer System Co.
00:10:B9  Maxtor Corp.
00:10:BA  Martinho-davis Systems, Inc.
00:10:BB  Data & Information Technology
00:10:BC  Nortel Networks
00:10:BD  The Telecommunication Technology Committee
00:10:BE  Telexis Corp.
00:10:BF  Interair Wireless
00:10:C0  Arma, Inc.
00:10:C1  Oi Electric Co., Ltd.
00:10:C2  Willnet, Inc.
00:10:C3  Csi-control Systems
00:10:C4  Media Links Co., Ltd.
00:10:C5  Protocol Technologies, Inc.
00:10:C6  Usi
00:10:C7  Data Transmission Network
00:10:C8  Communications Electronics Security Group
00:10:C9  Mitsubishi Electronics Logistic Support Co.
00:10:CA  Integral Access
00:10:CB  Facit K.k.
00:10:CC  Clp Computer Logistik Planung Gmbh
00:10:CD  Interface Concept
00:10:CE  Volamp, Ltd.
00:10:CF  Fiberlane Communications
00:10:D0  Witcom, Ltd.
00:10:D1  Top Layer Networks, Inc.
00:10:D2  Nitto Tsushinki Co., Ltd
00:10:D3  Grips Electronic Gmbh
00:10:D4  Storage Computer Corporation
00:10:D5  Imasde Canarias, S.a.
00:10:D6  Itt - A/cd
00:10:D7  Argosy Research Inc.
00:10:D8  Calista
00:10:D9  Ibm Japan, Fujisawa Mt+d
00:10:DA  Motion Engineering, Inc.
00:10:DB  Netscreen Technologies, Inc.
00:10:DC  Micro-star International Co., Ltd.
00:10:DD  Enable Semiconductor, Inc.
00:10:DE  International Datacasting Corporation
00:10:DF  Rise Computer Inc.
00:10:E0  Cobalt Microserver, Inc.
00:10:E1  S.i. Tech, Inc.
00:10:E2  Arraycomm, Inc.
00:10:E3  Compaq Computer Corporation
00:10:E4  Nsi Corporation
00:10:E5  Solectron Texas
00:10:E6  Applied Intelligent Systems, Inc.
00:10:E7  Breezecom
00:10:E8  Telocity, Incorporated
00:10:E9  Raidtec Ltd.
00:10:EA  Adept Technology
00:10:EB  Selsius Systems, Inc.
00:10:EC  Rpcg, Llc
00:10:ED  Sundance Technology, Inc.
00:10:EE  Cti Products, Inc.
00:10:EF  Dbtel Incorporated
00:10:F1  I-o Corporation
00:10:F2  Antec
00:10:F3  Nexcom International Co., Ltd.
00:10:F4  Vertical Networks, Inc.
00:10:F5  Amherst Systems, Inc.
00:10:F6  Cisco Systems, Inc.
00:10:F7  Iriichi Technologies Inc.
00:10:F8  Kenwood Tmi Corporation
00:10:F9  Unique Systems, Inc.
00:10:FA  Zayante, Inc.
00:10:FB  Zida Technologies Limited
00:10:FC  Broadband Networks, Inc.
00:10:FD  Cocom A/s
00:10:FE  Digital Equipment Corporation
00:10:FF  Cisco Systems, Inc.
00:1C:7C  Perq Systems Corporation
00:20:00  Lexmark International, Inc.
00:20:01  Dsp Solutions, Inc.
00:20:02  Seritech Enterprise Co., Ltd.
00:20:03  Pixel Power Ltd.
00:20:04  Yamatake-honeywell Co., Ltd.
00:20:05  Simple Technology
00:20:06  Garrett Communications, Inc.
00:20:07  Sfa, Inc.
00:20:08  Cable & Computer Technology
00:20:09  Packard Bell Elec., Inc.
00:20:0A  Source-comm Corp.
00:20:0B  Octagon Systems Corp.
00:20:0C  Adastra Systems Corp.
00:20:0D  Carl Zeiss
00:20:0E  Satellite Technology Mgmt, Inc
00:20:0F  Tanbac Co., Ltd.
00:20:10  Jeol System Technology Co. Ltd
00:20:11  Canopus Co., Ltd.
00:20:12  Camtronics Medical Systems
00:20:13  Diversified Technology, Inc.
00:20:14  Global View Co., Ltd.
00:20:15  Actis Computer Sa
00:20:16  Showa Electric Wire & Cable Co
00:20:17  Orbotech
00:20:18  Cis Technology Inc.
00:20:19  Ohler Gmbh
00:20:1A  N-base Switch Communications
00:20:1B  Northern Telecom/network
00:20:1C  Excel, Inc.
00:20:1D  Katana Products
00:20:1E  Netquest Corporation
00:20:1F  Best Power Technology, Inc.
00:20:20  Megatron Computer Industries Pty, Ltd.
00:20:21  Algorithms Software Pvt. Ltd.
00:20:22  Teknique, Inc.
00:20:23  T.c. Technologies Pty. Ltd
00:20:24  Pacific Communication Sciences
00:20:25  Control Technology, Inc.
00:20:26  Amkly Systems, Inc.
00:20:27  Ming Fortune Industry Co., Ltd
00:20:28  West Egg Systems, Inc.
00:20:29  Teleprocessing Products, Inc.
00:20:2A  N.v. Dzine
00:20:2B  Advanced Telecommunications Modules, Ltd.
00:20:2C  Welltronix Co., Ltd.
00:20:2D  Taiyo Corporation
00:20:2E  Daystar Digital
00:20:2F  Zeta Communications, Ltd.
00:20:30  Analog & Digital Systems
00:20:31  Ertec Gmbh
00:20:32  Alcatel Taisel
00:20:33  Synapse Technologies, Inc.
00:20:34  Rotec Industrieautomation Gmbh
00:20:35  Ibm Corporation
00:20:36  Bmc Software
00:20:37  Seagate Technology
00:20:38  Vme Microsystems International Corporation
00:20:39  Scinets
00:20:3A  Digital Bi0metrics Inc.
00:20:3B  Wisdm Ltd.
00:20:3C  Eurotime Ab
00:20:3D  Novar Electronics Corporation
00:20:3E  Logican Technologies, Inc.
00:20:3F  Juki Corporation
00:20:40  Motorola Broadband Communications Sector
00:20:41  Data Net
00:20:42  Datametrics Corp.
00:20:43  Neuron Company Limited
00:20:44  Genitech Pty Ltd
00:20:45  Ion Networks, Inc.
00:20:46  Ciprico, Inc.
00:20:47  Steinbrecher Corp.
00:20:48  Marconi Communications
00:20:49  Comtron, Inc.
00:20:4A  Pronet Gmbh
00:20:4B  Autocomputer Co., Ltd.
00:20:4C  Mitron Computer Pte Ltd.
00:20:4D  Inovis Gmbh
00:20:4E  Network Security Systems, Inc.
00:20:4F  Deutsche Aerospace Ag
00:20:50  Korea Computer Inc.
00:20:51  Phoenix Data Commununications
00:20:52  Ragula Systems
00:20:53  Huntsville Microsystems, Inc.
00:20:54  Eastern Research, Inc.
00:20:55  Altech Co., Ltd.
00:20:56  Neoproducts
00:20:57  Titze Datentechnik Gmbh
00:20:58  Allied Signal Inc.
00:20:59  Miro Computer Products Ag
00:20:5A  Computer Identics
00:20:5B  Skyline Technology
00:20:5C  Internet Systems Of Florida, Inc.
00:20:5D  Nanomatic Oy
00:20:5E  Castle Rock, Inc.
00:20:5F  Gammadata Computer Gmbh
00:20:60  Alcatel Italia S.p.a.
00:20:61  Dynatech Communications, Inc.
00:20:62  Scorpion Logic, Ltd.
00:20:63  Wipro Infotech Ltd.
00:20:64  Protec Microsystems, Inc.
00:20:65  Supernet Networking Inc.
00:20:66  General Magic, Inc.
00:20:67  Private
00:20:68  Isdyne
00:20:69  Isdn Systems Corporation
00:20:6A  Osaka Computer Corp.
00:20:6B  Minolta Camera Co., Ltd.
00:20:6C  Evergreen Technology Corp.
00:20:6D  Data Race, Inc.
00:20:6E  Xact, Inc.
00:20:6F  Flowpoint Corporation
00:20:70  Hynet, Ltd.
00:20:71  Ibr Gmbh
00:20:72  Worklink Innovations
00:20:73  Fusion Systems Corporation
00:20:74  Sungwoon Systems
00:20:75  Motorola Communication Israel
00:20:76  Reudo Corporation
00:20:77  Kardios Systems Corp.
00:20:78  Runtop, Inc.
00:20:79  Mikron Gmbh
00:20:7A  Wise Communications, Inc.
00:20:7B  Intel Corporation
00:20:7C  Autec Gmbh
00:20:7D  Advanced Computer Applications
00:20:7E  Finecom Co., Ltd.
00:20:7F  Kyoei Sangyo Co., Ltd.
00:20:80  Synergy (uk) Ltd.
00:20:81  Titan Electronics
00:20:82  Oneac Corporation
00:20:83  Presticom Incorporated
00:20:84  Oce Printing Systems, Gmbh
00:20:85  Exide Electronics
00:20:86  Microtech Electronics Limited
00:20:87  Memotec Communications Corp.
00:20:88  Global Village Communication
00:20:89  T3plus Networking, Inc.
00:20:8A  Sonix Communications, Ltd.
00:20:8B  Lapis Technologies, Inc.
00:20:8C  Galaxy Networks, Inc.
00:20:8D  Cmd Technology
00:20:8E  Chevin Software Eng. Ltd.
00:20:8F  Eci Telecom Ltd.
00:20:90  Advanced Compression Technology, Inc.
00:20:91  J125, National Security Agency
00:20:92  Chess Engineering B.v.
00:20:93  Landings Technology Corp.
00:20:94  Cubix Corporation
00:20:95  Riva Electronics
00:20:96  Invensys
00:20:97  Applied Signal Technology
00:20:98  Hectronic Ab
00:20:99  Bon Electric Co., Ltd.
00:20:9A  The 3do Company
00:20:9B  Ersat Electronic Gmbh
00:20:9C  Primary Access Corp.
00:20:9D  Lippert Automationstechnik
00:20:9E  Brown's Operating System Services, Ltd.
00:20:9F  Mercury Computer Systems, Inc.
00:20:A0  Oa Laboratory Co., Ltd.
00:20:A1  Dovatron
00:20:A2  Galcom Networking Ltd.
00:20:A3  Divicom Inc.
00:20:A4  Multipoint Networks
00:20:A5  Api Engineering
00:20:A6  Proxim, Inc.
00:20:A7  Pairgain Technologies, Inc.
00:20:A8  Sast Technology Corp.
00:20:A9  White Horse Industrial
00:20:AA  Digimedia Vision Ltd.
00:20:AB  Micro Industries Corp.
00:20:AC  Interflex Datensysteme Gmbh
00:20:AD  Linq Systems
00:20:AE  Ornet Data Communication Tech.
00:20:AF  3com Corporation
00:20:B0  Gateway Devices, Inc.
00:20:B1  Comtech Research Inc.
00:20:B2  Gkd Gesellschaft Fur Kommunikation Und Datentechnik
00:20:B3  Scltec Communications Systems
00:20:B4  Terma Elektronik As
00:20:B5  Yaskawa Electric Corporation
00:20:B6  Agile Networks, Inc.
00:20:B7  Namaqua Computerware
00:20:B8  Prime Option, Inc.
00:20:B9  Metricom, Inc.
00:20:BA  Center For High Performance
00:20:BB  Zax Corporation
00:20:BC  Jtec Pty Ltd.
00:20:BD  Niobrara R & D Corporation
00:20:BE  Lan Access Corp.
00:20:BF  Aehr Test Systems
00:20:C0  Pulse Electronics, Inc.
00:20:C1  Taiko Electric Works, Ltd.
00:20:C2  Texas Memory Systems, Inc.
00:20:C3  Counter Solutions Ltd.
00:20:C4  Inet,inc.
00:20:C5  Eagle Technology
00:20:C6  Nectec
00:20:C7  Akai Professional M.i. Corp.
00:20:C8  Larscom Incorporated
00:20:C9  Victron Bv
00:20:CA  Digital Ocean
00:20:CB  Pretec Electronics Corp.
00:20:CC  Digital Services, Ltd.
00:20:CD  Hybrid Networks, Inc.
00:20:CE  Logical Design Group, Inc.
00:20:CF  Test & Measurement Systems Inc
00:20:D0  Versalynx Corporation
00:20:D1  Microcomputer Systems (m) Sdn.
00:20:D2  Rad Data Communications, Ltd.
00:20:D3  Ost (ouest Standard Telematiqu
00:20:D4  Cabletron - Zeittnet Inc.
00:20:D5  Vipa Gmbh
00:20:D6  Breezecom
00:20:D7  Japan Minicomputer Systems Co., Ltd.
00:20:D8  Nortel Networks
00:20:D9  Panasonic Technologies, Inc./mieco-us
00:20:DA  Xylan Corporation
00:20:DB  Xnet Technology, Inc.
00:20:DC  Densitron Taiwan Ltd.
00:20:DD  Awa Ltd.
00:20:DE  Japan Digital Laborat'y Co.ltd
00:20:DF  Kyosan Electric Mfg. Co., Ltd.
00:20:E0  Premax Electronics, Inc.
00:20:E1  Alamar Electronics
00:20:E2  Information Resource Engineering
00:20:E3  Mcd Kencom Corporation
00:20:E4  Hsing Tech Enterprise Co., Ltd
00:20:E5  Apex Data, Inc.
00:20:E6  Lidkoping Machine Tools Ab
00:20:E7  B&w Nuclear Service Company
00:20:E8  Datatrek Corporation
00:20:E9  Dantel
00:20:EA  Efficient Networks, Inc.
00:20:EB  Cincinnati Microwave, Inc.
00:20:EC  Techware Systems Corp.
00:20:ED  Giga-byte Technology Co., Ltd.
00:20:EE  Gtech Corporation
00:20:EF  Usc Corporation
00:20:F0  Universal Microelectronics Co.
00:20:F1  Altos India Limited
00:20:F2  Sun Microsystems, Inc.
00:20:F3  Raynet Corporation
00:20:F4  Spectrix Corporation
00:20:F5  Pandatel Ag
00:20:F6  Net Tek  And Karlnet, Inc.
00:20:F7  Cyberdata
00:20:F8  Carrera Computers, Inc.
00:20:F9  Paralink Networks, Inc.
00:20:FA  Gde Systems, Inc.
00:20:FB  Octel Communications Corp.
00:20:FC  Matrox
00:20:FD  Itv Technologies, Inc.
00:20:FE  Topware Inc. / Grand Computer
00:20:FF  Symmetrical Technologies
00:30:00  Allwell Technology Corp.
00:30:01  Smp
00:30:02  Expand Networks
00:30:03  Phasys Ltd.
00:30:04  Leadtek Research Inc.
00:30:05  Fujitsu Siemens Computers
00:30:06  Superpower Computer
00:30:07  Opti, Inc.
00:30:08  Avio Digital, Inc.
00:30:09  Tachion Networks, Inc.
00:30:0A  Aztech Systems Ltd.
00:30:0B  Mphase Technologies, Inc.
00:30:0C  Congruency, Ltd.
00:30:0D  Mmc Technology, Inc.
00:30:0E  Klotz Digital Ag
00:30:0F  Imt - Information Management T
00:30:10  Visionetics International
00:30:11  Hms Fieldbus Systems Ab
00:30:12  Digital Engineering Ltd.
00:30:13  Nec Corporation
00:30:14  Divio, Inc.
00:30:15  Cp Clare Corp.
00:30:16  Ishida Co., Ltd.
00:30:17  Terastack Ltd.
00:30:18  Jetway Information Co., Ltd.
00:30:19  Cisco Systems, Inc.
00:30:1A  Smartbridges Pte. Ltd.
00:30:1B  Shuttle, Inc.
00:30:1C  Altvater Airdata Systems
00:30:1D  Skystream, Inc.
00:30:1E  3com Europe Ltd.
00:30:1F  Optical Networks, Inc.
00:30:20  Tsi, Inc..
00:30:21  Hsing Tech. Enterprise Co.,ltd
00:30:22  Fong Kai Industrial Co., Ltd.
00:30:23  Cogent Computer Systems, Inc.
00:30:24  Cisco Systems, Inc.
00:30:25  Checkout Computer Systems, Ltd
00:30:26  Heitel
00:30:27  Kerbango, Inc.
00:30:28  Fase Saldatura Srl
00:30:29  Opicom
00:30:2A  Southern Information
00:30:2B  Inalp Networks, Inc.
00:30:2C  Sylantro Systems Corporation
00:30:2D  Quantum Bridge Communications
00:30:2E  Hoft & Wessel Ag
00:30:2F  Smiths Industries
00:30:30  Harmonix Corporation
00:30:31  Lightwave Communications, Inc.
00:30:32  Magicram, Inc.
00:30:33  Orient Telecom Co., Ltd.
00:30:34  Private
00:30:35  Private
00:30:36  Rmp Elektroniksysteme Gmbh
00:30:37  Packard Bell Nec Services
00:30:38  Xcp, Inc.
00:30:39  Softbook Press
00:30:3A  Maatel
00:30:3B  Powercom Technology
00:30:3C  Onnto Corp.
00:30:3D  Iva Corporation
00:30:3E  Radcom Ltd.
00:30:3F  Turbocomm Tech Inc.
00:30:40  Cisco Systems, Inc.
00:30:41  Saejin T & M Co., Ltd.
00:30:42  Detewe-deutsche Telephonwerke
00:30:43  Idream Technologies, Pte. Ltd.
00:30:44  Portsmith Llc
00:30:45  Village Networks, Inc. (vni)
00:30:46  Controlled Electronic Manageme
00:30:47  Nissei Electric Co., Ltd.
00:30:48  Supermicro Computer, Inc.
00:30:49  Bryant Technology, Ltd.
00:30:4A  Fraunhofer Institute Ims
00:30:4B  Orbacom Systems, Inc.
00:30:4C  Appian Communications, Inc.
00:30:4D  Esi
00:30:4E  Bustec Production Ltd.
00:30:4F  Planet Technology Corporation
00:30:50  Versa Technology
00:30:51  Orbit Avionic & Communication
00:30:52  Elastic Networks
00:30:53  Basler Ag
00:30:54  Castlenet Technology, Inc.
00:30:55  Hitachi Semiconductor America,
00:30:56  Beck Ipc Gmbh
00:30:57  E-tel Corporation
00:30:58  Api Motion
00:30:59  Digital-logic Ag
00:30:5A  Telgen Corporation
00:30:5B  Module Department
00:30:5C  Smar Laboratories Corp.
00:30:5D  Digitra Systems, Inc.
00:30:5E  Abelko Innovation
00:30:5F  Imacon Aps
00:30:60  Starmatix, Inc.
00:30:61  Mobytel
00:30:62  Path 1 Network Technol's Inc.
00:30:63  Santera Systems, Inc.
00:30:64  Adlink Technology, Inc.
00:30:65  Apple	Airport Card 2002
00:30:66  Digital Wireless Corporation
00:30:67  Biostar Microtech Int'l Corp.
00:30:68  Cybernetics Tech. Co., Ltd.
00:30:69  Impacct Technology Corp.
00:30:6A  Penta Media Co., Ltd.
00:30:6B  Cmos Systems, Inc.
00:30:6C  Hitex Holding Gmbh
00:30:6D  Lucent Technologies
00:30:6E  Hewlett Packard
00:30:6F  Seyeon Tech. Co., Ltd.
00:30:70  1net Corporation
00:30:71  Cisco Systems, Inc.
00:30:72  Intellibyte Inc.
00:30:73  International Microsystems, In
00:30:74  Equiinet Ltd.
00:30:75  Adtech
00:30:76  Akamba Corporation
00:30:77  Onprem Networks
00:30:78  Cisco Systems, Inc.
00:30:79  Cqos, Inc.
00:30:7A  Advanced Technology & Systems
00:30:7B  Cisco Systems, Inc.
00:30:7C  Adid Sa
00:30:7D  Gre America, Inc.
00:30:7E  Redflex Communication Systems
00:30:7F  Irlan Ltd.
00:30:80  Cisco Systems, Inc.
00:30:81  Altos C&c
00:30:82  Taihan Electric Wire Co., Ltd.
00:30:83  Ivron Systems
00:30:84  Allied Telesyn Internaional
00:30:85  Cisco Systems, Inc.
00:30:86  Transistor Devices, Inc.
00:30:87  Vega Grieshaber Kg
00:30:88  Siara Systems, Inc.
00:30:89  Spectrapoint Wireless, Llc
00:30:8A  Nicotra Sistemi S.p.a
00:30:8B  Brix Networks
00:30:8C  Advanced Digital Information
00:30:8D  Pinnacle Systems, Inc.
00:30:8E  Cross Match Technologies, Inc.
00:30:8F  Micrilor, Inc.
00:30:90  Cyra Technologies, Inc.
00:30:91  Taiwan First Line Elec. Corp.
00:30:92  Modunorm Gmbh
00:30:93  Sonnet Technologies, Inc.
00:30:94  Cisco Systems, Inc.
00:30:95  Procomp Informatics, Ltd.
00:30:96  Cisco Systems, Inc.
00:30:97  Exomatic Ab
00:30:98  Global Converging Technologies
00:30:99  Boenig Und Kallenbach Ohg
00:30:9A  Astro Terra Corp.
00:30:9B  Smartware
00:30:9C  Timing Applications, Inc.
00:30:9D  Nimble Microsystems, Inc.
00:30:9E  Workbit Corporation.
00:30:9F  Amber Networks
00:30:A0  Tyco Submarine Systems, Ltd.
00:30:A1  Opti Tech Co., Ltd.
00:30:A2  Lightner Engineering
00:30:A3  Cisco Systems, Inc.
00:30:A4  Woodwind Communications System
00:30:A5  Active Power
00:30:A6  Vianet Technologies, Ltd.
00:30:A7  Schweitzer Engineering
00:30:A8  Ol'e Communications, Inc.
00:30:A9  Netiverse, Inc.
00:30:AA  Axus Microsystems, Inc.
00:30:AB  Delta Networks, Inc.
00:30:AC  Systeme Lauer Gmbh & Co., Ltd.
00:30:AD  Shanghai Communication
00:30:AE  Times N System, Inc.
00:30:AF  Honeywell Reqelsysteme Gmbh
00:30:B0  Convergenet Technologies
00:30:B1  Goc Gesellschaft Fur Optische
00:30:B2  Wescam - Healdsburg
00:30:B3  San Valley Systems, Inc.
00:30:B4  Intersil Corp.
00:30:B5  Tadiran Microwave Networks
00:30:B6  Cisco Systems, Inc.
00:30:B7  Teletrol Systems, Inc.
00:30:B8  Riverdelta Networks
00:30:B9  Ectel
00:30:BA  Ac&t System Co., Ltd.
00:30:BB  Cacheflow, Inc.
00:30:BC  Optronic Ag
00:30:BD  Belkin Components
00:30:BE  City-net Technology, Inc.
00:30:BF  Multidata Gmbh
00:30:C0  Lara Technology, Inc.
00:30:C1  Hewlett-packard
00:30:C2  Comone
00:30:C3  Flueckiger Elektronik Ag
00:30:C4  Niigata Canotec Co., Inc.
00:30:C5  Cadence Design Systems
00:30:C6  Control Solutions, Inc.
00:30:C7  Macromate Corp.
00:30:C8  Gad Line, Ltd.
00:30:C9  Luxn, N
00:30:CA  Discovery Com
00:30:CB  Omni Flow Computers, Inc.
00:30:CC  Tenor Networks, Inc.
00:30:CD  Conexant Systems, Inc.
00:30:CE  Zaffire
00:30:CF  Two Technologies, Inc.
00:30:D0  Private
00:30:D1  Inova Corporation
00:30:D2  Win Technologies, Co., Ltd.
00:30:D3  Agilent Technologies
00:30:D4  Comtier
00:30:D5  Dresearch Gmbh
00:30:D6  Msc Vertriebs Gmbh
00:30:D7  Innovative Systems, L.l.c.
00:30:D8  Sitek
00:30:D9  Datacore Software Corp.
00:30:DA  Comtrend Co.
00:30:DB  Mindready Solutions, Inc.
00:30:DC  Rightech Corporation
00:30:DD  Indigita Corporation
00:30:DE  Wago Kontakttechnik Gmbh
00:30:DF  Kb/tel Telecomunicaciones
00:30:E0  Oxford Semiconductor Ltd.
00:30:E1  Acrotron Systems, Inc.
00:30:E2  Garnet Systems Co., Ltd.
00:30:E3  Sedona Networks Corp.
00:30:E4  Chiyoda System Riken
00:30:E5  Amper Datos S.a.
00:30:E6  Siemens Medical Systems
00:30:E7  Cnf Mobile Solutions, Inc.
00:30:E8  Ensim Corp.
00:30:E9  Gma Communication Manufact'g
00:30:EA  Teraforce Technology Corporation
00:30:EB  Turbonet Communications, Inc.
00:30:EC  Borgardt
00:30:ED  Expert Magnetics Corp.
00:30:EE  Dsg Technology, Inc.
00:30:EF  Neon Technology, Inc.
00:30:F0  Uniform Industrial Corp.
00:30:F1  Accton Technology Corp.
00:30:F2  Cisco Systems, Inc.
00:30:F3  At Work Computers
00:30:F4  Stardot Technologies
00:30:F5  Wild Lab. Ltd.
00:30:F6  Securelogix Corporation
00:30:F7  Ramix Inc.
00:30:F8  Dynapro Systems, Inc.
00:30:F9  Sollae Systems Co., Ltd.
00:30:FA  Telica, Inc.
00:30:FB  Azs Technology Ag
00:30:FC  Terawave Communications, Inc.
00:30:FD  Integrated Systems Design
00:30:FE  Dsa Gmbh
00:30:FF  Datafab Systems, Inc.
00:40:00  Pci Componentes Da Amzonia Ltd
00:40:01  Zyxel Communications, Inc.
00:40:02  Perle Systems Limited
00:40:03  Westinghouse Process Control
00:40:04  Icm Co. Ltd.
00:40:05  Ani Communications Inc.
00:40:06  Sampo Technology Corporation
00:40:07  Telmat Informatique
00:40:08  A Plus Info Corporation
00:40:09  Tachibana Tectron Co., Ltd.
00:40:0A  Pivotal Technologies, Inc.
00:40:0B  Cisco Systems, Inc.
00:40:0C  General Micro Systems, Inc.
00:40:0D  Lannet Data Communications,ltd
00:40:0E  Memotec Communications, Inc.
00:40:0F  Datacom Technologies
00:40:10  Sonic Systems, Inc.
00:40:11  Andover Controls Corporation
00:40:12  Windata, Inc.
00:40:13  Ntt Data Comm. Systems Corp.
00:40:14  Comsoft Gmbh
00:40:15  Ascom Infrasys Ag
00:40:16  Hadax Electronics, Inc.
00:40:17  Xcd Inc.
00:40:18  Adobe Systems, Inc.
00:40:19  Aeon Systems, Inc.
00:40:1A  Fuji Electric Co., Ltd.
00:40:1B  Printer Systems Corp.
00:40:1C  Ast Research, Inc.
00:40:1D  Invisible Software, Inc.
00:40:1E  Icc
00:40:1F  Colorgraph Ltd
00:40:20  Pinacl Communication
00:40:21  Raster Graphics
00:40:22  Klever Computers, Inc.
00:40:23  Logic Corporation
00:40:24  Compac Inc.
00:40:25  Molecular Dynamics
00:40:26  Melco, Inc.
00:40:27  Smc Massachusetts, Inc.
00:40:28  Netcomm Limited
00:40:29  Compex
00:40:2A  Canoga-perkins
00:40:2B  Trigem Computer, Inc.
00:40:2C  Isis Distributed Systems, Inc.
00:40:2D  Harris Adacom Corporation
00:40:2E  Precision Software, Inc.
00:40:2F  Xlnt Designs Inc.
00:40:30  Gk Computer
00:40:31  Kokusai Electric Co., Ltd
00:40:32  Digital Communications
00:40:33  Addtron Technology Co., Ltd.
00:40:34  Bustek Corporation
00:40:35  Opcom
00:40:36  Tribe Computer Works, Inc.
00:40:37  Sea-ilan, Inc.
00:40:38  Talent Electric Incorporated
00:40:39  Optec Daiichi Denko Co., Ltd.
00:40:3A  Impact Technologies
00:40:3B  Synerjet International Corp.
00:40:3C  Forks, Inc.
00:40:3D  Teradata
00:40:3E  Raster Ops Corporation
00:40:3F  Ssangyong Computer Systems
00:40:40  Ring Access, Inc.
00:40:41  Fujikura Ltd.
00:40:42  N.a.t. Gmbh
00:40:43  Nokia Telecommunications
00:40:44  Qnix Computer Co., Ltd.
00:40:45  Twinhead Corporation
00:40:46  Udc Research Limited
00:40:47  Wind River Systems
00:40:48  Smd Informatica S.a.
00:40:49  Tegimenta Ag
00:40:4A  West Australian Department
00:40:4B  Maple Computer Systems
00:40:4C  Hypertec Pty Ltd.
00:40:4D  Telecommunications Techniques
00:40:4E  Fluent, Inc.
00:40:4F  Space & Naval Warfare Systems
00:40:50  Ironics, Incorporated
00:40:51  Gracilis, Inc.
00:40:52  Star Technologies, Inc.
00:40:53  Ampro Computers
00:40:54  Connection Machines Services
00:40:55  Metronix Gmbh
00:40:56  Mcm Japan Ltd.
00:40:57  Lockheed - Sanders
00:40:58  Kronos, Inc.
00:40:59  Yoshida Kogyo K. K.
00:40:5A  Goldstar Information & Comm.
00:40:5B  Funasset Limited
00:40:5C  Future Systems, Inc.
00:40:5D  Star-tek, Inc.
00:40:5E  North Hills Israel
00:40:5F  Afe Computers Ltd.
00:40:60  Comendec Ltd
00:40:61  Datatech Enterprises Co., Ltd.
00:40:62  E-systems, Inc./garland Div.
00:40:63  Via Technologies, Inc.
00:40:64  Kla Instruments Corporation
00:40:65  Gte Spacenet
00:40:66  Hitachi Cable, Ltd.
00:40:67  Omnibyte Corporation
00:40:68  Extended Systems
00:40:69  Lemcom Systems, Inc.
00:40:6A  Kentek Information Systems,inc
00:40:6B  Sysgen
00:40:6C  Copernique
00:40:6D  Lanco, Inc.
00:40:6E  Corollary, Inc.
00:40:6F  Sync Research Inc.
00:40:70  Interware Co., Ltd.
00:40:71  Atm Computer Gmbh
00:40:72  Applied Innovation Inc.
00:40:73  Bass Associates
00:40:74  Cable And Wireless
00:40:75  M-trade (uk) Ltd
00:40:76  Sun Conversion Technologies
00:40:77  Maxton Technology Corporation
00:40:78  Wearnes Automation Pte Ltd
00:40:79  Juko Manufacture Company, Ltd.
00:40:7A  Societe D'exploitation Du Cnit
00:40:7B  Scientific Atlanta
00:40:7C  Qume Corporation
00:40:7D  Extension Technology Corp.
00:40:7E  Evergreen Systems, Inc.
00:40:7F  Flir Systems
00:40:80  Athenix Corporation
00:40:81  Mannesmann Scangraphic Gmbh
00:40:82  Laboratory Equipment Corp.
00:40:83  Tda Industria De Produtos
00:40:84  Honeywell Inc.
00:40:85  Saab Instruments Ab
00:40:86  Michels & Kleberhoff Computer
00:40:87  Ubitrex Corporation
00:40:88  Mobius Technologies, Inc.
00:40:89  Meidensha Corporation
00:40:8A  Tps Teleprocessing Sys. Gmbh
00:40:8B  Raylan Corporation
00:40:8C  Axis Communications Ab
00:40:8D  The Goodyear Tire & Rubber Co.
00:40:8E  Digilog, Inc.
00:40:8F  Wm-data Minfo Ab
00:40:90  Ansel Communications
00:40:91  Procomp Industria Eletronica
00:40:92  Asp Computer Products, Inc.
00:40:93  Paxdata Networks Ltd.
00:40:94  Shographics, Inc.
00:40:95  R.p.t. Intergroups Int'l Ltd.
00:40:96  Aironet Wireless Communication
00:40:97  Datex Division Of
00:40:98  Dressler Gmbh & Co.
00:40:99  Newgen Systems Corp.
00:40:9A  Network Express, Inc.
00:40:9B  Hal Computer Systems Inc.
00:40:9C  Transware
00:40:9D  Digiboard, Inc.
00:40:9E  Concurrent Technologies  Ltd.
00:40:9F  Lancast/casat Technology, Inc.
00:40:A0  Goldstar Co., Ltd.
00:40:A1  Ergo Computing
00:40:A2  Kingstar Technology Inc.
00:40:A3  Microunity Systems Engineering
00:40:A4  Rose Electronics
00:40:A5  Clinicomp Intl.
00:40:A6  Cray, Inc.
00:40:A7  Itautec Philco S.a.
00:40:A8  Imf International Ltd.
00:40:A9  Datacom Inc.
00:40:AA  Valmet Automation Inc.
00:40:AB  Roland Dg Corporation
00:40:AC  Super Workstation, Inc.
00:40:AD  Sma Regelsysteme Gmbh
00:40:AE  Delta Controls, Inc.
00:40:AF  Digital Products, Inc.
00:40:B0  Bytex Corporation, Engineering
00:40:B1  Codonics Inc.
00:40:B2  Systemforschung
00:40:B3  Par Microsystems Corporation
00:40:B4  Nextcom K.k.
00:40:B5  Video Technology Computers Ltd
00:40:B6  Computerm  Corporation
00:40:B7  Stealth Computer Systems
00:40:B8  Idea Associates
00:40:B9  Macq Electronique Sa
00:40:BA  Alliant Computer Systems Corp.
00:40:BB  Goldstar Cable Co., Ltd.
00:40:BC  Algorithmics Ltd.
00:40:BD  Starlight Networks, Inc.
00:40:BE  Boeing Defense & Space
00:40:BF  Channel Systems Intern'l Inc.
00:40:C0  Vista Controls Corporation
00:40:C1  Bizerba-werke Wilheim Kraut
00:40:C2  Applied Computing Devices
00:40:C3  Fischer And Porter Co.
00:40:C4  Kinkei System Corporation
00:40:C5  Micom Communications Inc.
00:40:C6  Fibernet Research, Inc.
00:40:C7  Ruby Tech Corporation
00:40:C8  Milan Technology Corporation
00:40:C9  Ncube
00:40:CA  First Internat'l Computer, Inc
00:40:CB  Lanwan Technologies
00:40:CC  Silcom Manuf'g Technology Inc.
00:40:CD  Tera Microsystems, Inc.
00:40:CE  Net-source, Inc.
00:40:CF  Strawberry Tree, Inc.
00:40:D0  Mitac International Corp.
00:40:D1  Fukuda Denshi Co., Ltd.
00:40:D2  Pagine Corporation
00:40:D3  Kimpsion International Corp.
00:40:D4  Gage Talker Corp.
00:40:D5  Sartorius Ag
00:40:D6  Locamation B.v.
00:40:D7  Studio Gen Inc.
00:40:D8  Ocean Office Automation Ltd.
00:40:D9  American Megatrends Inc.
00:40:DA  Telspec Ltd
00:40:DB  Advanced Technical Solutions
00:40:DC  Tritec Electronic Gmbh
00:40:DD  Hong Technologies
00:40:DE  Elettronica San Giorgio
00:40:DF  Digalog Systems, Inc.
00:40:E0  Atomwide Ltd.
00:40:E1  Marner International, Inc.
00:40:E2  Mesa Ridge Technologies, Inc.
00:40:E3  Quin Systems Ltd
00:40:E4  E-m Technology, Inc.
00:40:E5  Sybus Corporation
00:40:E6  C.a.e.n.
00:40:E7  Arnos Instruments & Computer
00:40:E8  Charles River Data Systems,inc
00:40:E9  Accord Systems, Inc.
00:40:EA  Plain Tree Systems Inc
00:40:EB  Martin Marietta Corporation
00:40:EC  Mikasa System Engineering
00:40:ED  Network Controls Int'natl Inc.
00:40:EE  Optimem
00:40:EF  Hypercom, Inc.
00:40:F0  Micro Systems, Inc.
00:40:F1  Chuo Electronics Co., Ltd.
00:40:F2  Janich & Klass Computertechnik
00:40:F3  Netcor
00:40:F4  Cameo Communications, Inc.
00:40:F5  Oem Engines
00:40:F6  Katron Computers Inc.
00:40:F7  Polaroid Medical Imaging Sys.
00:40:F8  Systemhaus Discom
00:40:F9  Combinet
00:40:FA  Microboards, Inc.
00:40:FB  Cascade Communications Corp.
00:40:FC  Ibr Computer Technik Gmbh
00:40:FD  Lxe
00:40:FE  Symplex Communications
00:40:FF  Telebit Corporation
00:42:52  Rlx Technologies
00:50:00  Nexo Communications, Inc.
00:50:01  Yamashita Systems Corp.
00:50:02  Omnisec Ag
00:50:03  Gretag Macbeth Ag
00:50:04  3com Corporation
00:50:06  Tac Ab
00:50:07  Siemens Telecommunication Systems Limited
00:50:08  Compaq WL100
00:50:09  Philips Broadband Networks
00:50:0A  Iris Technologies, Inc.
00:50:0B  Cisco Systems, Inc.
00:50:0C  E-tek Labs, Inc.
00:50:0D  Satori Electoric Co., Ltd.
00:50:0E  Chromatis Networks, Inc.
00:50:0F  Cisco Systems, Inc.
00:50:10  Novanet Learning, Inc.
00:50:12  Cbl - Gmbh
00:50:13  Chaparral Network Storage
00:50:14  Cisco Systems, Inc.
00:50:15  Bright Star Engineering
00:50:16  Sst/woodhead Industries
00:50:17  Rsr S.r.l.
00:50:18  Advanced Multimedia Internet Technology Inc.
00:50:19  Spring Tide Networks, Inc.
00:50:1A  Uisiqn
00:50:1B  Abl Canada, Inc.
00:50:1C  Jatom Systems, Inc.
00:50:1E  Miranda Technologies, Inc.
00:50:1F  Mrg Systems, Ltd.
00:50:20  Mediastar Co., Ltd.
00:50:21  Eis International, Inc.
00:50:22  Zonet Technology, Inc.
00:50:23  Pg Design Electronics, Inc.
00:50:24  Navic Systems, Inc.
00:50:26  Cosystems, Inc.
00:50:27  Genicom Corporation
00:50:28  Aval Communications
00:50:29  1394 Printer Working Group
00:50:2A  Cisco Systems, Inc.
00:50:2B  Genrad Ltd.
00:50:2C  Soyo Computer, Inc.
00:50:2D  Accel, Inc.
00:50:2E  Cambex Corporation
00:50:2F  Tollbridge Technologies, Inc.
00:50:30  Future Plus Systems
00:50:31  Aeroflex Laboratories, Inc.
00:50:32  Picazo Communications, Inc.
00:50:33  Mayan Networks
00:50:36  Netcam, Ltd.
00:50:37  Koga Electronics Co.
00:50:38  Dain Telecom Co., Ltd.
00:50:39  Mariner Networks
00:50:3A  Datong Electronics Ltd.
00:50:3B  Mediafire Corporation
00:50:3C  Tsinghua Novel Electronics
00:50:3E  Cisco Systems, Inc.
00:50:3F  Anchor Games
00:50:40  Emware, Inc.
00:50:41  Ctx Opto Electronic Corp.
00:50:42  Sci Manufacturing Singapore Pte, Ltd.
00:50:43  Marvell Semiconductor, Inc.
00:50:44  Asaca Corporation
00:50:45  Rioworks Solutions, Inc.
00:50:46  Menicx International Co., Ltd.
00:50:47  Private
00:50:48  Infolibria
00:50:49  Ellacoya Networks, Inc.
00:50:4A  Elteco A.s.
00:50:4B  Barconet N.v.
00:50:4C  Galil Motion Control, Inc.
00:50:4D  Tokyo Electron Device Ltd.
00:50:4E  Sierra Monitor Corp.
00:50:4F  Olencom Electronics
00:50:50  Cisco Systems, Inc.
00:50:51  Iwatsu Electric Co., Ltd.
00:50:52  Tiara Networks, Inc.
00:50:53  Cisco Systems, Inc.
00:50:54  Cisco Systems, Inc.
00:50:55  Doms A/s
00:50:56  Vmware, Inc.
00:50:57  Broadband Access Systems
00:50:58  Vegastream Limited
00:50:59  Suite Technology Systems Network
00:50:5A  Network Alchemy, Inc.
00:50:5B  Kawasaki Lsi U.s.a., Inc.
00:50:5C  Tundo Corporation
00:50:5E  Digitek Micrologic S.a.
00:50:5F  Brand Innovators
00:50:60  Tandberg Telecom As
00:50:62  Kouwell Electronics Corp.  **
00:50:63  Oy Comsel System Ab
00:50:64  Cae Electronics
00:50:65  Densei-lambad Co., Ltd.
00:50:66  Atecom Gmbh Advanced Telecomunication Modules
00:50:67  Aerocomm, Inc.
00:50:68  Electronic Industries Association
00:50:69  Pixstream Incorporated
00:50:6A  Edeva, Inc.
00:50:6B  Spx-ateg
00:50:6C  G & L Beijer Electronics Ab
00:50:6D  Videojet Systems
00:50:6E  Corder Engineering Corporation
00:50:6F  G-connect
00:50:70  Chaintech Computer Co., Ltd.
00:50:71  Aiwa Co., Ltd.
00:50:72  Corvis Corporation
00:50:73  Cisco Systems, Inc.
00:50:74  Advanced Hi-tech Corp.
00:50:75  Kestrel Solutions
00:50:76  Ibm
00:50:77  Prolific Technology, Inc.
00:50:78  Megaton House, Ltd.
00:50:79  Private
00:50:7A  Xpeed, Inc.
00:50:7B  Merlot Communications
00:50:7C  Videocon Ag
00:50:7D  Ifp
00:50:7E  Newer Technology
00:50:7F  Draytek Corp.
00:50:80  Cisco Systems, Inc.
00:50:81  Murata Machinery, Ltd.
00:50:82  Foresson Corporation
00:50:83  Gilbarco, Inc.
00:50:84  Atl Products
00:50:86  Telkom Sa, Ltd.
00:50:87  Terasaki Electric Co., Ltd.
00:50:88  Amano Corporation
00:50:89  Safety Management Systems
00:50:8B  Compaq Computer Corporation
00:50:8C  Rsi Systems
00:50:8D  Abit Computer Corporation
00:50:8E  Optimation, Inc.
00:50:8F  Asita Technologies Int'l Ltd.
00:50:90  Dctri
00:50:91  Netaccess, Inc.
00:50:92  Rigaku Industrial Corporation
00:50:93  Boeing
00:50:94  Pace Micro Technology Plc
00:50:95  Peracom Networks
00:50:96  Salix Technologies, Inc.
00:50:97  Mmc-embedded Computertechnik Gmbh
00:50:98  Globaloop, Ltd.
00:50:99  3com Europe, Ltd.
00:50:9A  Tag Electronic Systems
00:50:9B  Switchcore Ab
00:50:9C  Beta Research
00:50:9D  The Industree B.v.
00:50:9E  Les Technologies Softacoustik Inc.
00:50:9F  Horizon Computer
00:50:A0  Delta Computer Systems, Inc.
00:50:A1  Carlo Gavazzi, Inc.
00:50:A2  Cisco Systems, Inc.
00:50:A3  Transmedia Communications, Inc.
00:50:A4  Io Tech, Inc.
00:50:A5  Capitol Business Systems, Ltd.
00:50:A6  Optronics
00:50:A7  Cisco Systems, Inc.
00:50:A8  Opencon Systems, Inc.
00:50:A9  Moldat Wireless Technolgies
00:50:AA  Konica Corporation
00:50:AB  Naltec, Inc.
00:50:AC  Maple Computer Corporation
00:50:AD  Communique Wireless Corp.
00:50:AE  Iwaki Electronics Co., Ltd.
00:50:AF  Intergon, Inc.
00:50:B0  Technology Atlanta Corporation
00:50:B1  Giddings & Lewis
00:50:B2  Brodel Automation
00:50:B3  Voiceboard Corporation
00:50:B4  Satchwell Control Systems, Ltd
00:50:B5  Fichet-bauche
00:50:B6  Good Way Ind. Co., Ltd.
00:50:B7  Boser Technology Co., Ltd.
00:50:B8  Inova Computers Gmbh & Co. Kg
00:50:B9  Xitron Technologies, Inc.
00:50:BA  D-link
00:50:BB  Cms Technologies
00:50:BC  Hammer Storage Solutions
00:50:BD  Cisco Systems, Inc.
00:50:BE  Fast Multimedia Ag
00:50:BF  Mototech Inc.
00:50:C0  Gatan, Inc.
00:50:C1  Gemflex Networks, Ltd.
00:50:C2  Ieee Registration Authority
00:50:C4  Imd
00:50:C5  Ads Technologies, Inc.
00:50:C6  Loop Telecommunication International, Inc.
00:50:C8  Addonics Communications, Inc.
00:50:C9  Maspro Denkoh Corp.
00:50:CA  Net To Net Technologies
00:50:CB  Jetter
00:50:CC  Xyratex
00:50:CD  Digianswer A/s
00:50:CE  Lg International Corp.
00:50:CF  Vanlink Communication Technology Research Institute
00:50:D0  Minerva Systems
00:50:D1  Cisco Systems, Inc.
00:50:D2  Bae Systems Canada, Inc.
00:50:D3  Digital Audio Processing Pty. Ltd.
00:50:D4  Joohong Information &
00:50:D5  Ad Systems Corp.
00:50:D6  Atlas Copco Tools Ab
00:50:D7  Telstrat
00:50:D8  Unicorn Computer Corp.
00:50:D9  Engetron-engenharia Eletronica Ind. E Com. Ltda
00:50:DA  3Com 3CRWE73796B
00:50:DB  Contemporary Control
00:50:DC  Tas Telefonbau A. Schwabe Gmbh & Co. Kg
00:50:DD  Serra Soldadura, S.a.
00:50:DE  Signum Systems Corp.
00:50:DF  Airfiber, Inc.
00:50:E1  Ns Tech Electronics Sdn Bhd
00:50:E2  Cisco Systems, Inc.
00:50:E3  Telegate
00:50:E4  Apple Computer, Inc.
00:50:E6  Hakusan Corporation
00:50:E7  Paradise Innovations (asia)
00:50:E8  Nomadix Inc.
00:50:EA  Xel Communications, Inc.
00:50:EB  Alpha-top Corporation
00:50:EC  Olicom A/s
00:50:ED  Anda Networks
00:50:EE  Tek Digitel Corporation
00:50:EF  Spe Systemhaus Gmbh
00:50:F0  Cisco Systems, Inc.
00:50:F1  Libit Signal Processing, Ltd.
00:50:F2  Microsoft Corp.
00:50:F3  Global Net Information Co., Ltd.
00:50:F4  Sigmatek Gmbh & Co. Kg
00:50:F6  Pan-international Industrial Corp.
00:50:F7  Venture Manufacturing (singapore) Ltd.
00:50:F8  Entrega Technologies, Inc.
00:50:F9  Private
00:50:FA  Oxtel, Ltd.
00:50:FB  Vsk Electronics
00:50:FC  Edimax Technology Co., Ltd.
00:50:FD  Visioncomm Co., Ltd.
00:50:FE  Pctvnet Asa
00:50:FF  Hakko Electronics Co., Ltd.
00:60:00  Xycom Inc.
00:60:01  Innosys, Inc.
00:60:02  Screen Subtitling Systems, Ltd
00:60:03  Teraoka Weigh System Pte, Ltd.
00:60:04  Computadores Modulares Sa
00:60:05  Feedback Data Ltd.
00:60:06  Sotec Co., Ltd
00:60:07  Acres Gaming, Inc.
00:60:08  3com Corporation
00:60:09  Cisco Systems, Inc.
00:60:0A  Sord Computer Corporation
00:60:0B  Logware Gmbh
00:60:0C  Applied Data Systems, Inc.
00:60:0D  Digital Logic Gmbh
00:60:0E  Wavenet International, Inc.
00:60:0F  Westell, Inc.
00:60:10  Network Machines, Inc.
00:60:11  Crystal Semiconductor Corp.
00:60:12  Power Computing Corporation
00:60:13  Netstal Maschinen Ag
00:60:14  Edec Co., Ltd.
00:60:15  Net2net Corporation
00:60:16  Clariion
00:60:17  Tokimec Inc.
00:60:18  Stellar One Corporation
00:60:19  Roche Diagnostics
00:60:1A  Keithley Instruments
00:60:1B  Mesa Electronics
00:60:1C  Telxon Corporation
00:60:1D  Lucent Technologies
00:60:1E  Softlab, Inc.
00:60:1F  Stallion Technologies
00:60:20  Pivotal Networking, Inc.
00:60:21  Dsc Corporation
00:60:22  Vicom Systems, Inc.
00:60:23  Pericom Semiconductor Corp.
00:60:24  Gradient Technologies, Inc.
00:60:25  Active Imaging Plc
00:60:26  Viking Components, Inc.
00:60:27  Superior Modular Products
00:60:28  Macrovision Corporation
00:60:29  Cary Peripherals Inc.
00:60:2A  Symicron Computer Communications, Ltd.
00:60:2B  Peak Audio
00:60:2C  Linx Data Terminals, Inc.
00:60:2D  Alerton Technologies, Inc.
00:60:2E  Cyclades Corporation
00:60:2F  Cisco Systems, Inc.
00:60:30  Village Tronic Entwicklung
00:60:31  Hrk Systems
00:60:32  I-cube, Inc.
00:60:33  Acuity Imaging, Inc.
00:60:34  Robert Bosch Gmbh
00:60:35  Dallas Semiconductor, Inc.
00:60:36  Austrian Research Center Seibersdorf
00:60:37  Philips Semiconductors
00:60:38  Nortel Networks
00:60:39  Sancom Technology, Inc.
00:60:3A  Quick Controls Ltd.
00:60:3B  Amtec Spa
00:60:3C  Hagiwara Sys-com Co., Ltd.
00:60:3D  3cx
00:60:3E  Cisco Systems, Inc.
00:60:3F  Patapsco Designs
00:60:40  Netro Corp.
00:60:41  Yokogawa Electric Corporation
00:60:42  Tks (usa), Inc.
00:60:43  Comsoft Systems, Inc.
00:60:44  Litton/poly-scientific
00:60:45  Pathlight Technologies
00:60:46  Vmetro, Inc.
00:60:47  Cisco Systems, Inc.
00:60:48  Emc Corporation
00:60:49  Vina Technologies
00:60:4A  Saic Ideas Group
00:60:4B  Biodata Gmbh
00:60:4C  Sat
00:60:4D  Mmc Networks, Inc.
00:60:4E  Cycle Computer Corporation, Inc.
00:60:4F  Suzuki Mfg. Co., Ltd.
00:60:50  Internix Inc.
00:60:51  Quality Semiconductor
00:60:52  Peripherals Enterprise Co., Ltd.
00:60:53  Toyoda Machine Works, Ltd.
00:60:54  Controlware Gmbh
00:60:55  Cornell University
00:60:56  Network Tools, Inc.
00:60:57  Murata Manufacturing Co., Ltd.
00:60:58  Copper Mountain Communications, Inc.
00:60:59  Technical Communications Corp.
00:60:5A  Celcore, Inc.
00:60:5B  Intraserver Technology, Inc.
00:60:5C  Cisco Systems, Inc.
00:60:5D  Scanivalve Corp.
00:60:5E  Liberty Technology Networking
00:60:5F  Nippon Unisoft Corporation
00:60:60  Dawning Technologies, Inc.
00:60:61  Whistle Communications Corp.
00:60:62  Telesync, Inc.
00:60:63  Psion Dacom Plc.
00:60:64  Netcomm Limited
00:60:65  Bernecker & Rainer Industrie-elektronic Gmbh
00:60:66  Lacroix Technolgie
00:60:67  Acer Netxus Inc.
00:60:68  Eicon Technology Corporation
00:60:69  Brocade Communications Systems, Inc.
00:60:6A  Mitsubishi Wireless Communications. Inc.
00:60:6B  Synclayer Inc.
00:60:6C  Arescom
00:60:6D  Cabletron CSIBB-AA
00:60:6E  Davicom Semiconductor, Inc.
00:60:6F  Clarion Corporation Of America
00:60:70  Cisco Systems, Inc.
00:60:71  Midas Lab, Inc.
00:60:72  Vxl Instruments, Limited
00:60:73  Redcreek Communications, Inc.
00:60:74  Qsc Audio Products
00:60:75  Pentek, Inc.
00:60:76  Schlumberger Technologies Retail Petroleum Systems
00:60:77  Prisa Networks
00:60:78  Power Measurement Ltd.
00:60:79  Mainstream Data, Inc.
00:60:7A  Dvs Gmbh
00:60:7B  Fore Systems, Inc.
00:60:7C  Waveaccess, Ltd.
00:60:7D  Sentient Networks Inc.
00:60:7E  Gigalabs, Inc.
00:60:7F  Aurora Technologies, Inc.
00:60:80  Microtronix Datacom Ltd.
00:60:81  Tv/com International
00:60:82  Novalink Technologies, Inc.
00:60:83  Cisco Systems, Inc.
00:60:84  Digital Video
00:60:85  Storage Concepts
00:60:86  Logic Replacement Tech. Ltd.
00:60:87  Kansai Electric Co., Ltd.
00:60:88  White Mountain Dsp, Inc.
00:60:89  Xata
00:60:8A  Citadel Computer
00:60:8B  Confertech International
00:60:8C  3com Corporation
00:60:8D  Unipulse Corp.
00:60:8E  He Electronics, Technologie & Systemtechnik Gmbh
00:60:8F  Tekram Technology Co., Ltd.
00:60:90  Able Communications, Inc.
00:60:91  First Pacific Networks, Inc.
00:60:92  Micro/sys, Inc.
00:60:93  Varian
00:60:94  Ibm Corp.
00:60:95  Accu-time Systems, Inc.
00:60:96  T.s. Microtech Inc.
00:60:97  3com Corporation
00:60:98  Ht Communications
00:60:99  Lan Media Corporation
00:60:9A  Njk Techno Co.
00:60:9B  Astro-med, Inc.
00:60:9C  Perkin-elmer Incorporated
00:60:9D  Pmi Food Equipment Group
00:60:9E  Asc X3 - Information Technology Standards Secretariats
00:60:9F  Phast Corporation
00:60:A0  Switched Network Technologies, Inc.
00:60:A1  Vpnet, Inc.
00:60:A2  Nihon Unisys Limited Co.
00:60:A3  Continuum Technology Corp.
00:60:A4  Grinaker System Technologies
00:60:A5  Performance Telecom Corp.
00:60:A6  Particle Measuring Systems
00:60:A7  Microsens Gmbh & Co. Kg
00:60:A8  Tidomat Ab
00:60:A9  Gesytec Mbh
00:60:AA  Intelligent Devices Inc. (idi)
00:60:AB  Larscom Incorporated
00:60:AC  Resilience Corporation
00:60:AD  Megachips Corporation
00:60:AE  Trio Information Systems Ab
00:60:AF  Pacific Micro Data, Inc.
00:60:B0  Hewlett-packard Co.
00:60:B1  Input/output, Inc.
00:60:B2  Process Control Corp.
00:60:B3  SMC SMC2642W
00:60:B4  Glenayre R&d Inc.
00:60:B5  Keba Gmbh
00:60:B6  Land Computer Co., Ltd.
00:60:B7  Channelmatic, Inc.
00:60:B8  Corelis Inc.
00:60:B9  Nitsuko Corporation
00:60:BA  Sahara Networks, Inc.
00:60:BB  Cabletron - Netlink, Inc.
00:60:BC  Keunyoung Electronics & Communication Co., Ltd.
00:60:BD  Hubbell-pulsecom
00:60:BE  Webtronics
00:60:BF  Macraigor Systems, Inc.
00:60:C0  Nera As
00:60:C1  Wavespan Corporation
00:60:C2  Mpl Ag
00:60:C3  Netvision Corporation
00:60:C4  Soliton Systems K.k.
00:60:C5  Ancot Corp.
00:60:C6  Dcs Ag
00:60:C7  Amati Communications Corp.
00:60:C8  Kuka Welding Systems & Robots
00:60:C9  Controlnet, Inc.
00:60:CA  Harmonic Systems Incorporated
00:60:CB  Hitachi Zosen Corporation
00:60:CC  Emtrak, Incorporated
00:60:CD  Videoserver, Inc.
00:60:CE  Acclaim Communications
00:60:CF  Alteon Networks, Inc.
00:60:D0  Snmp Research Incorporated
00:60:D1  Cascade Communications
00:60:D2  Lucent Technologies Taiwan Telecommunications Co., Ltd.
00:60:D3  At&t
00:60:D4  Eldat Communication Ltd.
00:60:D5  Miyachi Technos Corp.
00:60:D6  Novatel Wireless Technologies Ltd.
00:60:D7  Ecole Polytechnique Federale De Lausanne (epfl)
00:60:D8  Elmic Systems, Inc.
00:60:D9  Transys Networks Inc.
00:60:DA  Jbm Electronics Co.
00:60:DB  Ntp Elektronik A/s
00:60:DC  Toyo Communication Equipment Co., Ltd.
00:60:DD  Myricom, Inc.
00:60:DE  Kayser-threde Gmbh
00:60:DF  Inrange Technologies Corp.
00:60:E0  Axiom Technology Co., Ltd.
00:60:E1  Orckit Communications Ltd.
00:60:E2  Quest Engineering & Development
00:60:E3  Arbin Instruments
00:60:E4  Compuserve, Inc.
00:60:E5  Fuji Automation Co., Ltd.
00:60:E6  Shomiti Systems Incorporated
00:60:E7  Randata
00:60:E8  Hitachi Computer Products (america), Inc.
00:60:E9  Atop Technologies, Inc.
00:60:EA  Streamlogic
00:60:EB  Fourthtrack Systems
00:60:EC  Hermary Opto Electronics Inc.
00:60:ED  Ricardo Test Automation Ltd.
00:60:EE  Apollo
00:60:EF  Flytech Technology Co., Ltd.
00:60:F0  Johnson & Johnson Medical, Inc
00:60:F1  Exp Computer, Inc.
00:60:F2  Lasergraphics, Inc.
00:60:F3  Netcom Systems, Inc.
00:60:F4  Advanced Computer Solutions, Inc.
00:60:F5  Icon West, Inc.
00:60:F6  Nextest Communications Products, Inc.
00:60:F7  Datafusion Systems
00:60:F8  Loran International Technologies Inc.
00:60:F9  Diamond Lane Communications
00:60:FA  Educational Technology Resources, Inc.
00:60:FB  Packeteer, Inc.
00:60:FC  Conservation Through Innovation Ltd.
00:60:FD  Netics, Inc.
00:60:FE  Lynx System Developers, Inc.
00:60:FF  Quvis, Inc.
00:70:B0  M/a-com Inc. Companies
00:70:B3  Data Recall Ltd.
00:80:00  Multitech Systems, Inc.
00:80:01  Periphonics Corporation
00:80:02  Satelcom (uk) Ltd
00:80:03  Hytec Electronics Ltd.
00:80:04  Antlow Communications, Ltd.
00:80:05  Cactus Computer Inc.
00:80:06  Compuadd Corporation
00:80:07  Dlog Nc-systeme
00:80:08  Dynatech Computer Systems
00:80:09  Jupiter Systems, Inc.
00:80:0A  Japan Computer Corp.
00:80:0B  Csk Corporation
00:80:0C  Videcom Limited
00:80:0D  Vosswinkel F.u.
00:80:0E  Atlantix Corporation
00:80:0F  Standard Microsystems
00:80:10  Commodore International
00:80:11  Digital Systems Int'l. Inc.
00:80:12  Integrated Measurement Systems
00:80:13  Thomas-conrad Corporation
00:80:14  Esprit Systems
00:80:15  Seiko Systems, Inc.
00:80:16  Wandel And Goltermann
00:80:17  Pfu Limited
00:80:18  Kobe Steel, Ltd.
00:80:19  Dayna Communications, Inc.
00:80:1A  Bell Atlantic
00:80:1B  Kodiak Technology
00:80:1C  Newport Systems Solutions
00:80:1D  Integrated Inference Machines
00:80:1E  Xinetron, Inc.
00:80:1F  Krupp Atlas Electronik Gmbh
00:80:20  Network Products
00:80:21  Newbridge Research Corp.
00:80:22  Scan-optics
00:80:23  Integrated Business Networks
00:80:24  Kalpana, Inc.
00:80:25  Stollmann Gmbh
00:80:26  Network Products Corporation
00:80:27  Adaptive Systems, Inc.
00:80:28  Tradpost (hk) Ltd
00:80:29  Eagle Technology, Inc.
00:80:2A  Test Systems & Simulations Inc
00:80:2B  Integrated Marketing Co
00:80:2C  The Sage Group Plc
00:80:2D  Xylogics Inc
00:80:2E  Castle Rock Computing
00:80:2F  National Instruments Corp.
00:80:30  Nexus Electronics
00:80:31  Basys, Corp.
00:80:32  Access Co., Ltd.
00:80:33  Formation, Inc.
00:80:34  Smt Goupil
00:80:35  Technology Works, Inc.
00:80:36  Reflex Manufacturing Systems
00:80:37  Ericsson Group
00:80:38  Data Research & Applications
00:80:39  Alcatel Stc Australia
00:80:3A  Varityper, Inc.
00:80:3B  Apt Communications, Inc.
00:80:3C  Tvs Electronics Ltd
00:80:3D  Surigiken Co.,  Ltd.
00:80:3E  Synernetics
00:80:3F  Tatung Company
00:80:40  John Fluke Manufacturing Co.
00:80:41  Veb Kombinat Robotron
00:80:42  Force Computers
00:80:43  Networld, Inc.
00:80:44  Systech Computer Corp.
00:80:45  Matsushita Electric Ind. Co
00:80:46  University Of Toronto
00:80:47  In-net Corp.
00:80:48  Compex Incorporated
00:80:49  Nissin Electric Co., Ltd.
00:80:4A  Pro-log
00:80:4B  Eagle Technologies Pty.ltd.
00:80:4C  Contec Co., Ltd.
00:80:4D  Cyclone Microsystems, Inc.
00:80:4E  Apex Computer Company
00:80:4F  Daikin Industries, Ltd.
00:80:50  Ziatech Corporation
00:80:51  Fibermux
00:80:52  Technically Elite Concepts
00:80:53  Intellicom, Inc.
00:80:54  Frontier Technologies Corp.
00:80:55  Fermilab
00:80:56  Sphinx Elektronik Gmbh
00:80:57  Adsoft, Ltd.
00:80:58  Printer Systems Corporation
00:80:59  Stanley Electric Co., Ltd
00:80:5A  Tulip Computers Internat'l B.v
00:80:5B  Condor Systems, Inc.
00:80:5C  Agilis Corporation
00:80:5D  Canstar
00:80:5E  Lsi Logic Corporation
00:80:5F  Compaq Computer Corporation
00:80:60  Network Interface Corporation
00:80:61  Litton Systems, Inc.
00:80:62  Interface  Co.
00:80:63  Richard Hirschmann Gmbh & Co.
00:80:64  Wyse Technology
00:80:65  Cybergraphic Systems Pty Ltd.
00:80:66  Arcom Control Systems, Ltd.
00:80:67  Square D Company
00:80:68  Yamatech Scientific Ltd.
00:80:69  Computone Systems
00:80:6A  Eri (empac Research Inc.)
00:80:6B  Schmid Telecommunication
00:80:6C  Cegelec Projects Ltd
00:80:6D  Century Systems Corp.
00:80:6E  Nippon Steel Corporation
00:80:6F  Onelan Ltd.
00:80:70  Computadoras Micron
00:80:71  Sai Technology
00:80:72  Microplex Systems Ltd.
00:80:73  Dwb Associates
00:80:74  Fisher Controls
00:80:75  Parsytec Gmbh
00:80:76  Mcnc
00:80:77  Brother Industries, Ltd.
00:80:78  Practical Peripherals, Inc.
00:80:79  Microbus Designs Ltd.
00:80:7A  Aitech Systems Ltd.
00:80:7B  Artel Communications Corp.
00:80:7C  Fibercom, Inc.
00:80:7D  Equinox Systems Inc.
00:80:7E  Southern Pacific Ltd.
00:80:7F  Dy-4 Incorporated
00:80:80  Datamedia Corporation
00:80:81  Kendall Square Research Corp.
00:80:82  Pep Modular Computers Gmbh
00:80:83  Amdahl
00:80:84  The Cloud Inc.
00:80:85  H-three Systems Corporation
00:80:86  Computer Generation Inc.
00:80:87  Oki Electric Industry Co., Ltd
00:80:88  Victor Company Of Japan, Ltd.
00:80:89  Tecnetics (pty) Ltd.
00:80:8A  Summit Microsystems Corp.
00:80:8B  Dacoll Limited
00:80:8C  Netscout Systems, Inc.
00:80:8D  Westcoast Technology B.v.
00:80:8E  Radstone Technology
00:80:8F  C. Itoh Electronics, Inc.
00:80:90  Microtek International, Inc.
00:80:91  Tokyo Electric Co.,ltd
00:80:92  Japan Computer Industry, Inc.
00:80:93  Xyron Corporation
00:80:94  Alfa Laval Automation Ab
00:80:95  Basic Merton Handelsges.m.b.h.
00:80:96  Human Designed Systems, Inc.
00:80:97  Centralp Automatismes
00:80:98  Tdk Corporation
00:80:99  Klockner Moeller Ipc
00:80:9A  Novus Networks Ltd
00:80:9B  Justsystem Corporation
00:80:9C  Luxcom, Inc.
00:80:9D  Commscraft Ltd.
00:80:9E  Datus Gmbh
00:80:9F  Alcatel Business Systems
00:80:A0  Edisa Hewlett Packard S/a
00:80:A1  Microtest, Inc.
00:80:A2  Creative Electronic Systems
00:80:A3  Lantronix
00:80:A4  Liberty Electronics
00:80:A5  Speed International
00:80:A6  Republic Technology, Inc.
00:80:A7  Measurex Corp.
00:80:A8  Vitacom Corporation
00:80:A9  Clearpoint Research
00:80:AA  Maxpeed
00:80:AB  Dukane Network Integration
00:80:AC  Imlogix, Division Of Genesys
00:80:AD  Cnet Technology, Inc.
00:80:AE  Hughes Network Systems
00:80:AF  Allumer Co., Ltd.
00:80:B0  Advanced Information
00:80:B1  Softcom A/s
00:80:B2  Network Equipment Technologies
00:80:B3  Aval Data Corporation
00:80:B4  Sophia Systems
00:80:B5  United Networks Inc.
00:80:B6  Themis Computer
00:80:B7  Stellar Computer
00:80:B8  Bug, Incorporated
00:80:B9  Arche Technoligies Inc.
00:80:BA  Specialix (asia) Pte, Ltd
00:80:BB  Hughes Lan Systems
00:80:BC  Hitachi Engineering Co., Ltd
00:80:BD  The Furukawa Electric Co., Ltd
00:80:BE  Aries Research
00:80:BF  Takaoka Electric Mfg. Co. Ltd.
00:80:C0  Penril Datacomm
00:80:C1  Lanex Corporation
00:80:C2  Ieee 802 Committee
00:80:C3  Bicc Information Systems & Svc
00:80:C4  Document Technologies, Inc.
00:80:C5  Novellco De Mexico
00:80:C6  National Datacomm Corporation
00:80:C7  Netwave (Xircom Netwave/Netwave Airsurfer)
00:80:C8  D-link Systems, Inc.
00:80:C9  Alberta Microelectronic Centre
00:80:CA  Netcom Research Incorporated
00:80:CB  Falco Data Products
00:80:CC  Microwave Bypass Systems
00:80:CD  Micronics Computer, Inc.
00:80:CE  Broadcast Television Systems
00:80:CF  Embedded Performance Inc.
00:80:D0  Computer Peripherals, Inc.
00:80:D1  Kimtron Corporation
00:80:D2  Shinnihondenko Co., Ltd.
00:80:D3  Shiva Corp.
00:80:D4  Chase Research Ltd.
00:80:D5  Cadre Technologies
00:80:D6  Nuvotech, Inc.
00:80:D7  Fantum Engineering
00:80:D8  Network Peripherals Inc.
00:80:D9  Emk Elektronik
00:80:DA  Bruel & Kjaer
00:80:DB  Graphon Corporation
00:80:DC  Picker International
00:80:DD  Gmx Inc/gimix
00:80:DE  Gipsi S.a.
00:80:DF  Adc Codenoll Technology Corp.
00:80:E0  Xtp Systems, Inc.
00:80:E1  Stmicroelectronics
00:80:E2  T.d.i. Co., Ltd.
00:80:E3  Coral Network Corporation
00:80:E4  Northwest Digital Systems, Inc
00:80:E5  Mylex Corporation
00:80:E6  Peer Networks, Inc.
00:80:E7  Lynwood Scientific Dev. Ltd.
00:80:E8  Cumulus Corporatiion
00:80:E9  Madge Networks
00:80:EA  Adva Optical Networking Ltd.
00:80:EB  Compcontrol B.v.
00:80:EC  Supercomputing Solutions, Inc.
00:80:ED  Iq Technologies, Inc.
00:80:EE  Thomson Csf
00:80:EF  Rational
00:80:F0  Kyushu Matsushita Electric Co.
00:80:F1  Opus Systems
00:80:F2  Raycom Systems Inc
00:80:F3  Sun Electronics Corp.
00:80:F4  Telemecanique Electrique
00:80:F5  Quantel Ltd
00:80:F6  Synergy Microsystems
00:80:F7  Zenith Electronics
00:80:F8  Mizar, Inc.
00:80:F9  Heurikon Corporation
00:80:FA  Rwt Gmbh
00:80:FB  Bvm Limited
00:80:FC  Avatar Corporation
00:80:FD  Exsceed Corpration
00:80:FE  Azure Technologies, Inc.
00:80:FF  Soc. De Teleinformatique Rtc
00:90:00  Diamond Multimedia
00:90:01  Nishimu Electronics Industries Co., Ltd.
00:90:02  Allgon Ab
00:90:03  Aplio
00:90:04  3com Europe Ltd.
00:90:05  Protech Systems Co., Ltd.
00:90:06  Hamamatsu Photonics K.k.
00:90:07  Domex Technology Corp.
00:90:08  Hana Systems Inc.
00:90:09  I Controls, Inc.
00:90:0A  Proton Electronic Industrial Co., Ltd.
00:90:0B  Lanner Electronics, Inc.
00:90:0C  Cisco Systems, Inc.
00:90:0D  Overland Data Inc.
00:90:0E  Handlink Technologies, Inc.
00:90:0F  Kawasaki Heavy Industries, Ltd
00:90:10  Simulation Laboratories, Inc.
00:90:11  Wavtrace, Inc.
00:90:12  Globespan Semiconductor, Inc.
00:90:13  Samsan Corp.
00:90:14  Rotork Instruments, Ltd.
00:90:15  Centigram Communications Corp.
00:90:16  Zac
00:90:17  Zypcom, Inc.
00:90:18  Ito Electric Industry Co, Ltd.
00:90:19  Hermes Electronics Co., Ltd.
00:90:1A  Unisphere Solutions
00:90:1B  Digital Controls
00:90:1C  Mps Software Gmbh
00:90:1D  Pec (nz) Ltd.
00:90:1E  Selesta Ingegne Ria S.p.a.
00:90:1F  Adtec Productions, Inc.
00:90:20  Philips Analytical X-ray B.v.
00:90:21  Cisco Systems, Inc.
00:90:22  Ivex
00:90:23  Zilog Inc.
00:90:24  Pipelinks, Inc.
00:90:25  Vision Systems Ltd. Pty
00:90:26  Advanced Switching Communications, Inc.
00:90:27  Intel Corporation
00:90:28  Nippon Signal Co., Ltd.
00:90:29  Crypto Ag
00:90:2A  Communication Devices, Inc.
00:90:2B  Cisco Systems, Inc.
00:90:2C  Data & Control Equipment Ltd.
00:90:2D  Data Electronics (aust.) Pty, Ltd.
00:90:2E  Namco Limited
00:90:2F  Netcore Systems, Inc.
00:90:30  Honeywell-dating
00:90:31  Mysticom, Ltd.
00:90:32  Pelcombe Group Ltd.
00:90:33  Innovaphone Gmbh
00:90:34  Imagic, Inc.
00:90:35  Alpha Telecom, Inc.
00:90:36  Ens, Inc.
00:90:37  Acucomm, Inc.
00:90:38  Fountain Technologies, Inc.
00:90:39  Shasta Networks
00:90:3A  Nihon Media Tool Inc.
00:90:3B  Triems Research Lab, Inc.
00:90:3C  Atlantic Network Systems
00:90:3D  Biopac Systems, Inc.
00:90:3E  N.v. Philips Industrial Activities
00:90:3F  Aztec Radiomedia
00:90:40  Siemens Network Convergence Llc
00:90:41  Applied Digital Access
00:90:42  Eccs, Inc.
00:90:43  Nichibei Denshi Co., Ltd.
00:90:44  Assured Digital, Inc.
00:90:45  Marconi Communications
00:90:46  Dexdyne, Ltd.
00:90:47  Giga Fast E. Ltd.
00:90:48  Zeal Corporation
00:90:49  Entridia Corporation
00:90:4A  Concur System Technologies
00:90:4B  Gemtek Technology Co., Ltd.
00:90:4C  Epigram, Inc.
00:90:4D  Spec S.a.
00:90:4E  Delem Bv
00:90:4F  Abb Power T&d Company, Inc.
00:90:50  Teleste Oy
00:90:51  Ultimate Technology Corp.
00:90:52  Selcom Elettronica S.r.l.
00:90:53  Daewoo Electronics Co., Ltd.
00:90:54  Innovative Semiconductors, Inc
00:90:55  Parker Hannifin Corporation Compumotor Division
00:90:56  Telestream, Inc.
00:90:57  Aanetcom, Inc.
00:90:58  Ultra Electronics Ltd., Command And Control Systems
00:90:59  Telecom Device K.k.
00:90:5A  Dearborn Group, Inc.
00:90:5B  Raymond And Lae Engineering
00:90:5C  Edmi
00:90:5D  Netcom Sicherheitstechnik Gmbh
00:90:5E  Rauland-borg Corporation
00:90:5F  Cisco Systems, Inc.
00:90:60  System Create Corp.
00:90:61  Pacific Research & Engineering Corporation
00:90:62  Icp Vortex Computersysteme Gmbh
00:90:63  Coherent Communications Systems Corporation
00:90:64  Thomson Broadcast Systems
00:90:65  Finisar Corporation
00:90:66  Troika Networks, Inc.
00:90:67  Walkabout Computers, Inc.
00:90:68  Dvt Corp.
00:90:69  Juniper Networks, Inc.
00:90:6A  Turnstone Systems, Inc.
00:90:6B  Applied Resources, Inc.
00:90:6C  Gwt Global Weighing Technologies Gmbh
00:90:6D  Cisco Systems, Inc.
00:90:6E  Praxon, Inc.
00:90:6F  Cisco Systems, Inc.
00:90:70  Neo Networks, Inc.
00:90:71  Applied Innovation Inc.
00:90:72  Simrad As
00:90:73  Gaio Technology
00:90:74  Argon Networks, Inc.
00:90:75  Nec Do Brasil S.a.
00:90:76  Fmt Aircraft Gate Support Systems Ab
00:90:77  Advanced Fibre Communications
00:90:78  Mer Telemanagement Solutions, Ltd.
00:90:79  Clearone, Inc.
00:90:7A  Spectralink Corp.
00:90:7B  E-tech, Inc.
00:90:7C  Digitalcast, Inc.
00:90:7D  Lake Communications
00:90:7E  Vetronix Corp.
00:90:7F  Watchguard Technologies, Inc.
00:90:80  Not Limited, Inc.
00:90:81  Aloha Networks, Inc.
00:90:82  Force Institute
00:90:83  Turbo Communication, Inc.
00:90:84  Atech System
00:90:85  Golden Enterprises, Inc.
00:90:86  Cisco Systems, Inc.
00:90:87  Itis
00:90:88  Baxall Security Ltd.
00:90:89  Softcom Microsystems, Inc.
00:90:8A  Bayly Communications, Inc.
00:90:8B  Cell Computing, Inc.
00:90:8C  Etrend Electronics, Inc.
00:90:8D  Vickers Electronics Systems
00:90:8E  Nortel Networks Broadband Access
00:90:8F  Audio Codes Ltd.
00:90:90  I-bus
00:90:91  Digitalscape, Inc.
00:90:92  Cisco Systems, Inc.
00:90:93  Nanao Corporation
00:90:94  Osprey Technologies, Inc.
00:90:95  Universal Avionics
00:90:96  Askey Computer Corp.
00:90:97  Sycamore Networks
00:90:98  Sbc Designs, Inc.
00:90:99  Allied Telesis, K.k.
00:90:9A  One World Systems, Inc.
00:90:9B  Markpoint Ab
00:90:9C  Combox, Ltd.
00:90:9D  Gse Systems, Inc.
00:90:9E  Critical Io, Llc
00:90:9F  Digi-data Corporation
00:90:A0  8x8 Inc.
00:90:A1  Flying Pig Systems, Ltd.
00:90:A2  Cybertan Technology, Inc.
00:90:A3  Corecess Inc.
00:90:A4  Altiga Networks
00:90:A5  Spectra Logic
00:90:A6  Cisco Systems, Inc.
00:90:A7  Clientec Corporation
00:90:A8  Ninetiles Networks, Ltd.
00:90:A9  Western Digital
00:90:AA  Indigo Active Vision Systems Limited
00:90:AB  Cisco Systems, Inc.
00:90:AC  Optivision, Inc.
00:90:AD  Aspect Electronics, Inc.
00:90:AE  Italtel S.p.a.
00:90:AF  J. Morita Mfg. Corp.
00:90:B0  Vadem
00:90:B1  Cisco Systems, Inc.
00:90:B2  Avici Systems Inc.
00:90:B3  Agranat Systems
00:90:B4  Willowbrook Technologies
00:90:B5  Nikon Corporation
00:90:B6  Fibex Systems
00:90:B7  Digital Lightwave, Inc.
00:90:B8  Rohde & Schwarz Gmbh & Co. Kg
00:90:B9  Beran Instruments Ltd.
00:90:BA  Valid Networks, Inc.
00:90:BB  Tainet Communication System Corp.
00:90:BC  Telemann Co., Ltd.
00:90:BD  Omnia Communications, Inc.
00:90:BE  Ibc/integrated Business Computers
00:90:BF  Cisco Systems, Inc.
00:90:C0  K.j. Law Engineers, Inc.
00:90:C1  Peco Ii, Inc.
00:90:C2  Jk Microsystems, Inc.
00:90:C3  Topic Semiconductor Corp.
00:90:C4  Javelin Systems, Inc.
00:90:C5  Internet Magic, Inc.
00:90:C6  Optim Systems, Inc.
00:90:C7  Icom Inc.
00:90:C8  Waverider Communications (canada) Inc.
00:90:C9  Productivity Enhancement Products., Inc.
00:90:CA  Accord Video Telecommunications, Ltd.
00:90:CB  Wireless Online, Inc.
00:90:CC  Planet Communications, Inc.
00:90:CD  Ent-empresa Nacional De Telecommunicacoes, S.a.
00:90:CE  Tetra Gmbh
00:90:CF  Nortel
00:90:D0  Thomson Belgium
00:90:D1  LeArtery SyncByAir LN101
00:90:D2  Artel Video Systems
00:90:D3  Giesecke & Devrient Gmbh
00:90:D4  Bindview Development Corp.
00:90:D5  Euphonix, Inc.
00:90:D6  Crystal Group
00:90:D7  Netboost Corp.
00:90:D8  Whitecross Systems
00:90:D9  Cisco Systems, Inc.
00:90:DA  Dynarc, Inc.
00:90:DB  Next Level Communications
00:90:DC  Teco Information Systems
00:90:DD  The Miharu Communications Co., Ltd.
00:90:DE  Cardkey Systems, Inc.
00:90:DF  Mitsubishi Chemical America, Inc.
00:90:E0  Systran Corp.
00:90:E1  Telena S.p.a.
00:90:E2  Distributed Processing Technology
00:90:E3  Avex Electronics Inc.
00:90:E4  Nec America, Inc.
00:90:E5  Teknema, Inc.
00:90:E6  Acer Laboratories, Inc.
00:90:E7  Horsch Elektronik Ag
00:90:E8  Moxa Technologies Corp., Ltd.
00:90:E9  Janz Computer Ag
00:90:EA  Alpha Technologies, Inc.
00:90:EB  Sentry Telecom Systems
00:90:EC  Pyrescom
00:90:ED  Central System Research Co., Ltd.
00:90:EE  Personal Communications Technologies
00:90:EF  Integrix, Inc.
00:90:F0  Harmonic Lightwaves, Ltd.
00:90:F1  Dot Hill Systems Corporation
00:90:F2  Cisco Systems, Inc.
00:90:F3  Aspect Communications
00:90:F4  Lightning Instrumentation
00:90:F5  Clevo Co.
00:90:F6  Escalate Networks, Inc.
00:90:F7  Nbase Communications Ltd.
00:90:F8  Mediatrix Telecom
00:90:F9  Leitch
00:90:FA  Giganet, Inc.
00:90:FB  Portwell, Inc.
00:90:FC  Network Computing Devices
00:90:FD  Coppercom, Inc.
00:90:FE  Elecom Co., Ltd.  (laneed Div.)
00:90:FF  Tellus Technology Inc.
00:91:D6  Crystal Group, Inc.
00:9D:8E  Cardiac Recorders, Inc.
00:A0:00  Centillion Networks, Inc.
00:A0:01  Watkins-johnson Company
00:A0:02  Leeds & Northrup Australia Pty Ltd
00:A0:03  Staefa Control System
00:A0:04  Netpower, Inc.
00:A0:05  Daniel Instruments, Ltd.
00:A0:06  Image Data Processing System Group
00:A0:07  Apexx Technology, Inc.
00:A0:08  Netcorp
00:A0:09  Whitetree Network
00:A0:0A  R.d.c. Communication
00:A0:0B  Computex Co., Ltd.
00:A0:0C  Kingmax Technology, Inc.
00:A0:0D  The Panda Project
00:A0:0E  Visual Networks, Inc.
00:A0:0F  Broadband Technologies
00:A0:10  Syslogic Datentechnik Ag
00:A0:11  Mutoh Industries Ltd.
00:A0:12  B.a.t.m. Advanced Technologies
00:A0:13  Teltrend Ltd.
00:A0:14  Csir
00:A0:15  Wyle
00:A0:16  Micropolis Corp.
00:A0:17  J B M Corporation
00:A0:18  Creative Controllers, Inc.
00:A0:19  Nebula Consultants, Inc.
00:A0:1A  Binar Elektronik Ab
00:A0:1B  Premisys Communications, Inc.
00:A0:1C  Nascent Networks Corporation
00:A0:1D  Sixnet
00:A0:1E  Est Corporation
00:A0:1F  Tricord Systems, Inc.
00:A0:20  Citicorp/tti
00:A0:21  General Dynamics-
00:A0:22  Centre For Development Of Advanced Computing
00:A0:23  Applied Creative Technology, Inc.
00:A0:24  3com Corporation
00:A0:25  Redcom Labs Inc.
00:A0:26  Teldat, S.a.
00:A0:27  Firepower Systems, Inc.
00:A0:28  Conner Peripherals
00:A0:29  Coulter Corporation
00:A0:2A  Trancell Systems
00:A0:2B  Transitions Research Corp.
00:A0:2C  Interwave Communications
00:A0:2D  1394 Trade Association
00:A0:2E  Brand Communications, Ltd.
00:A0:2F  Pirelli Cavi
00:A0:30  Captor Nv/sa
00:A0:31  Hazeltine Corporation, Ms 1-17
00:A0:32  Ges Singapore Pte. Ltd.
00:A0:33  Imc Mebsysteme Gmbh
00:A0:34  Axel
00:A0:35  Cylink Corporation
00:A0:36  Applied Network Technology
00:A0:37  Datascope Corporation
00:A0:38  Email Electronics
00:A0:39  Ross Technology, Inc.
00:A0:3A  Kubotek Corporation
00:A0:3B  Toshin Electric Co., Ltd.
00:A0:3C  Eg&g Nuclear Instruments
00:A0:3D  Opto-22
00:A0:3E  Atm Forum
00:A0:3F  Computer Society Microprocessor & Microprocessor Standards C
00:A0:40  Apple Computer
00:A0:41  Leybold-inficon
00:A0:42  Spur Products Corp.
00:A0:43  American Technology Labs, Inc.
00:A0:44  Ntt Intelligent Technology
00:A0:45  Phoenix Contact Gmbh & Co.
00:A0:46  Scitex Corp. Ltd.
00:A0:47  Integrated Fitness Corp.
00:A0:48  Questech, Ltd.
00:A0:49  Digitech Industries, Inc.
00:A0:4A  Nisshin Electric Co., Ltd.
00:A0:4B  Tfl Lan Inc.
00:A0:4C  Innovative Systems & Technologies, Inc.
00:A0:4D  Eda Instruments, Inc.
00:A0:4E  Voelker Technologies, Inc.
00:A0:4F  Ameritec Corp.
00:A0:50  Cypress Semiconductor
00:A0:51  Angia Communications. Inc.
00:A0:52  Stanilite Electronics Pty. Ltd
00:A0:53  Compact Devices, Inc.
00:A0:54  Private
00:A0:55  Linktech, Inc.
00:A0:56  Micropross
00:A0:57  Lancom Systems Gmbh
00:A0:58  Glory, Ltd.
00:A0:59  Hamilton Hallmark
00:A0:5A  Kofax Image Products
00:A0:5B  Marquip, Inc.
00:A0:5C  Inventory Conversion, Inc./
00:A0:5D  Cs Computer Systeme Gmbh
00:A0:5E  Myriad Logic Inc.
00:A0:5F  Btg Engineering Bv
00:A0:60  Acer Peripherals, Inc.
00:A0:61  Puritan Bennett
00:A0:62  Aes Prodata
00:A0:63  Jrl Systems, Inc.
00:A0:64  Kvb/analect
00:A0:65  Nexland, Inc.
00:A0:66  Isa Co., Ltd.
00:A0:67  Network Services Group
00:A0:68  Bhp Limited
00:A0:69  Truetime
00:A0:6A  Verilink Corp.
00:A0:6B  Dms Dorsch Mikrosystem Gmbh
00:A0:6C  Shindengen Electric Mfg. Co., Ltd.
00:A0:6D  Mannesmann Tally Corporation
00:A0:6E  Austron, Inc.
00:A0:6F  The Appcon Group, Inc.
00:A0:70  Coastcom
00:A0:71  Video Lottery Technologies,inc
00:A0:72  Ovation Systems Ltd.
00:A0:73  Com21, Inc.
00:A0:74  Perception Technology
00:A0:75  Micron Technology, Inc.
00:A0:76  Cardware Lab, Inc.
00:A0:77  Fujitsu Nexion, Inc.
00:A0:78  Marconi Communications
00:A0:79  Alps Electric (usa), Inc.
00:A0:7A  Advanced Peripherals Technologies, Inc.
00:A0:7B  Dawn Computer Incorporation
00:A0:7C  Tonyang Nylon Co., Ltd.
00:A0:7D  Seeq Technology, Inc.
00:A0:7E  Avid Technology, Inc.
00:A0:7F  Gsm-syntel, Ltd.
00:A0:80  Antares Microsystems
00:A0:81  Alcatel Data Networks
00:A0:82  Nkt Elektronik A/s
00:A0:83  Asimmphony Turkey
00:A0:84  Dataplex Pty. Ltd.
00:A0:85  Private
00:A0:86  Amber Wave Systems, Inc.
00:A0:87  Zarlink Semiconductor Ltd.
00:A0:88  Essential Communications
00:A0:89  Xpoint Technologies, Inc.
00:A0:8A  Brooktrout Technology, Inc.
00:A0:8B  Aston Electronic Designs Ltd.
00:A0:8C  Multimedia Lans, Inc.
00:A0:8D  Jacomo Corporation
00:A0:8E  Nokia Internet Communications
00:A0:8F  Desknet Systems, Inc.
00:A0:90  Timestep Corporation
00:A0:91  Applicom International
00:A0:92  H. Bollmann Manufacturers, Ltd
00:A0:93  B/e Aerospace, Inc.
00:A0:94  Comsat Corporation
00:A0:95  Acacia Networks, Inc.
00:A0:96  Mitumi Electric Co., Ltd.
00:A0:97  Jc Information Systems
00:A0:98  Network Appliance Corp.
00:A0:99  K-net Ltd.
00:A0:9A  Nihon Kohden America
00:A0:9B  Qpsx Communications, Ltd.
00:A0:9C  Xyplex, Inc.
00:A0:9D  Johnathon Freeman Technologies
00:A0:9E  Ictv
00:A0:9F  Commvision Corp.
00:A0:A0  Compact Data, Ltd.
00:A0:A1  Epic Data Inc.
00:A0:A2  Digicom S.p.a.
00:A0:A3  Reliable Power Meters
00:A0:A4  Micros Systems, Inc.
00:A0:A5  Teknor Microsysteme, Inc.
00:A0:A6  M.i. Systems, K.k.
00:A0:A7  Vorax Corporation
00:A0:A8  Renex Corporation
00:A0:A9  Gn Nettest (canada) Navtel Division
00:A0:AA  Spacelabs Medical
00:A0:AB  Netcs Informationstechnik Gmbh
00:A0:AC  Gilat Satellite Networks, Ltd.
00:A0:AD  Marconi Spa
00:A0:AE  Nucom Systems, Inc.
00:A0:AF  Wms Industries
00:A0:B0  I-o Data Device, Inc.
00:A0:B1  First Virtual Corporation
00:A0:B2  Shima Seiki
00:A0:B3  Zykronix
00:A0:B4  Texas Microsystems, Inc.
00:A0:B5  3h Technology
00:A0:B6  Sanritz Automation Co., Ltd.
00:A0:B7  Cordant, Inc.
00:A0:B8  Symbios Logic Inc.
00:A0:B9  Eagle Technology, Inc.
00:A0:BA  Patton Electronics Co.
00:A0:BB  Hilan Gmbh
00:A0:BC  Viasat, Incorporated
00:A0:BD  I-tech Corp.
00:A0:BE  Integrated Circuit Systems, Inc. Communications Group
00:A0:BF  Wireless Data Group Motorola
00:A0:C0  Digital Link Corp.
00:A0:C1  Ortivus Medical Ab
00:A0:C2  R.a. Systems Co., Ltd.
00:A0:C3  Unicomputer Gmbh
00:A0:C4  Cristie Electronics Ltd.
00:A0:C5  Zyxel Communication
00:A0:C6  Qualcomm Incorporated
00:A0:C7  Tadiran Telecommunications
00:A0:C8  Adtran Inc.
00:A0:C9  Intel Corporation - Hf1-06
00:A0:CA  Fujitsu Denso Ltd.
00:A0:CB  Ark Telecommunications, Inc.
00:A0:CC  Lite-on Communications, Inc.
00:A0:CD  Dr. Johannes Heidenhain Gmbh
00:A0:CE  Astrocom Corporation
00:A0:CF  Sotas, Inc.
00:A0:D0  Ten X Technology, Inc.
00:A0:D1  Inventec Corporation
00:A0:D2  Allied Telesis International Corporation
00:A0:D3  Instem Computer Systems, Ltd.
00:A0:D4  Radiolan,  Inc.
00:A0:D5  Sierra Wireless Inc.
00:A0:D6  Sbe, Inc.
00:A0:D7  Kasten Chase Applied Research
00:A0:D8  Spectra - Tek
00:A0:D9  Convex Computer Corporation
00:A0:DA  Integrated Systems Technology, Inc.
00:A0:DB  Fisher & Paykel Production
00:A0:DC  O.n. Electronic Co., Ltd.
00:A0:DD  Azonix Corporation
00:A0:DE  Yamaha Corporation
00:A0:DF  Sts Technologies, Inc.
00:A0:E0  Tennyson Technologies Pty Ltd
00:A0:E1  Westport Research Associates, Inc.
00:A0:E2  Keisoku Giken Corp.
00:A0:E3  Xkl Systems Corp.
00:A0:E4  Optiquest
00:A0:E5  Nhc Communications
00:A0:E6  Dialogic Corporation
00:A0:E7  Central Data Corporation
00:A0:E8  Reuters Holdings Plc
00:A0:E9  Electronic Retailing Systems International
00:A0:EA  Ethercom Corp.
00:A0:EB  Fastcomm Communications Corp.
00:A0:EC  Transmitton Ltd.
00:A0:ED  Pri Automation
00:A0:EE  Nashoba Networks
00:A0:EF  Lucidata Ltd.
00:A0:F0  Toronto Microelectronics Inc.
00:A0:F1  Mti
00:A0:F2  Infotek Communications, Inc.
00:A0:F3  Staubli
00:A0:F4  Ge
00:A0:F5  Radguard Ltd.
00:A0:F6  Autogas Systems Inc.
00:A0:F7  V.i Computer Corp.
00:A0:F8  Symbol Spectrum24
00:A0:F9  Bintec Communications Gmbh
00:A0:FA  Marconi Communication Gmbh
00:A0:FB  Toray Engineering Co., Ltd.
00:A0:FC  Image Sciences, Inc.
00:A0:FD  Scitex Digital Printing, Inc.
00:A0:FE  Boston Technology, Inc.
00:A0:FF  Tellabs Operations, Inc.
00:AA:00  Intel Corporation
00:AA:01  Intel Corporation
00:AA:02  Intel Corporation
00:AA:3C  Olivetti Telecom Spa (olteco)
00:B0:09  Grass Valley Group
00:B0:17  Infogear Technology Corp.
00:B0:19  Casi-rusco
00:B0:1C  Westport Technologies
00:B0:1E  Rantic Labs, Inc.
00:B0:2A  Orsys Gmbh
00:B0:2D  Viagate Technologies, Inc.
00:B0:3B  Hiq Networks
00:B0:48  Marconi Communications Inc.
00:B0:4A  Cisco Systems, Inc.
00:B0:52  Intellon Corporation
00:B0:64  Cisco Systems, Inc.
00:B0:69  Honewell Oy
00:B0:6D  Jones Futurex Inc.
00:B0:80  Mannesmann Ipulsys B.v.
00:B0:86  Locsoft Limited
00:B0:8E  Cisco Systems, Inc.
00:B0:91  Transmeta Corp.
00:B0:94  Alaris, Inc.
00:B0:9A  Morrow Technologies Corp.
00:B0:9D  Point Grey Research Inc.
00:B0:AC  Siae-microelettronica S.p.a.
00:B0:AE  Symmetricom
00:B0:B3  Xstreamis Plc
00:B0:C2  Cisco Systems, Inc.
00:B0:C7  Tellabs Operations, Inc.
00:B0:CE  Technology Rescue
00:B0:D0  Dell Computer Corp.
00:B0:DB  Nextcell, Inc.
00:B0:DF  Reliable Data Technology, Inc.
00:B0:E7  British Federal Ltd.
00:B0:EC  Eacem
00:B0:EE  Ajile Systems, Inc.
00:B0:F0  Caly Networks
00:B0:F5  Networth Technologies, Inc.
00:BB:01  Octothorpe Corp.
00:BB:F0  Ungermann-bass Inc.
00:C0:00  Lanoptics, Ltd.
00:C0:01  Diatek Patient Managment
00:C0:02  Sercomm Corporation
00:C0:03  Globalnet Communications
00:C0:04  Japan Business Computer Co.ltd
00:C0:05  Livingston Enterprises, Inc.
00:C0:06  Nippon Avionics Co., Ltd.
00:C0:07  Pinnacle Data Systems, Inc.
00:C0:08  Seco Srl
00:C0:09  Kt Technology (s) Pte Ltd
00:C0:0A  Micro Craft
00:C0:0B  Norcontrol A.s.
00:C0:0C  Relia Technolgies
00:C0:0D  Advanced Logic Research, Inc.
00:C0:0E  Psitech, Inc.
00:C0:0F  Quantum Software Systems Ltd.
00:C0:10  Hirakawa Hewtech Corp.
00:C0:11  Interactive Computing Devices
00:C0:12  Netspan Corporation
00:C0:13  Netrix
00:C0:14  Telematics Calabasas Int'l,inc
00:C0:15  New Media Corporation
00:C0:16  Electronic Theatre Controls
00:C0:17  Forte Networks
00:C0:18  Lanart Corporation
00:C0:19  Leap Technology, Inc.
00:C0:1A  Corometrics Medical Systems
00:C0:1B  Socket Communications, Inc.
00:C0:1C  Interlink Communications Ltd.
00:C0:1D  Grand Junction Networks, Inc.
00:C0:1E  La Francaise Des Jeux
00:C0:1F  S.e.r.c.e.l.
00:C0:20  Arco Electronic, Control Ltd.
00:C0:21  Netexpress
00:C0:22  Lasermaster Technologies, Inc.
00:C0:23  Tutankhamon Electronics
00:C0:24  Eden Sistemas De Computacao Sa
00:C0:25  Dataproducts Corporation
00:C0:26  Lans Technology Co., Ltd.
00:C0:27  Cipher Systems, Inc.
00:C0:28  Jasco Corporation
00:C0:29  Nexans Deutschland Ag - Ans
00:C0:2A  Ohkura Electric Co., Ltd.
00:C0:2B  Gerloff Gesellschaft Fur
00:C0:2C  Centrum Communications, Inc.
00:C0:2D  Fuji Photo Film Co., Ltd.
00:C0:2E  Netwiz
00:C0:2F  Okuma Corporation
00:C0:30  Integrated Engineering B. V.
00:C0:31  Design Research Systems, Inc.
00:C0:32  I-cubed Limited
00:C0:33  Telebit Communications Aps
00:C0:34  Transaction Network
00:C0:35  Quintar Company
00:C0:36  Raytech Electronic Corp.
00:C0:37  Dynatem
00:C0:38  Raster Image Processing System
00:C0:39  Tdk Semiconductor Corporation
00:C0:3A  Men-mikro Elektronik Gmbh
00:C0:3B  Multiaccess Computing Corp.
00:C0:3C  Tower Tech S.r.l.
00:C0:3D  Wiesemann & Theis Gmbh
00:C0:3E  Fa. Gebr. Heller Gmbh
00:C0:3F  Stores Automated Systems, Inc.
00:C0:40  Ecci
00:C0:41  Digital Transmission Systems
00:C0:42  Datalux Corp.
00:C0:43  Stratacom
00:C0:44  Emcom Corporation
00:C0:45  Isolation Systems, Ltd.
00:C0:46  Kemitron Ltd.
00:C0:47  Unimicro Systems, Inc.
00:C0:48  Bay Technical Associates
00:C0:49  U.s. Robotics, Inc.
00:C0:4A  Group 2000 Ag
00:C0:4B  Creative Microsystems
00:C0:4C  Department Of Foreign Affairs
00:C0:4D  Mitec, Inc.
00:C0:4E  Comtrol Corporation
00:C0:4F  Dell Computer Corporation
00:C0:50  Toyo Denki Seizo K.k.
00:C0:51  Advanced Integration Research
00:C0:52  Burr-brown
00:C0:53  Davox Corporation
00:C0:54  Network Peripherals, Ltd.
00:C0:55  Modular Computing Technologies
00:C0:56  Somelec
00:C0:57  Myco Electronics
00:C0:58  Dataexpert Corp.
00:C0:59  Nippon Denso Co., Ltd.
00:C0:5A  Semaphore Communications Corp.
00:C0:5B  Networks Northwest, Inc.
00:C0:5C  Elonex Plc
00:C0:5D  L&n Technologies
00:C0:5E  Vari-lite, Inc.
00:C0:5F  Fine-pal Company Limited
00:C0:60  Id Scandinavia As
00:C0:61  Solectek Corporation
00:C0:62  Impulse Technology
00:C0:63  Morning Star Technologies, Inc
00:C0:64  General Datacomm Ind. Inc.
00:C0:65  Scope Communications, Inc.
00:C0:66  Docupoint, Inc.
00:C0:67  United Barcode Industries
00:C0:68  Philip Drake Electronics Ltd.
00:C0:69  Adaptive Broadband Corporation
00:C0:6A  Zahner-elektrik Gmbh & Co. Kg
00:C0:6B  Osi Plus Corporation
00:C0:6C  Svec Computer Corp.
00:C0:6D  Boca Research, Inc.
00:C0:6E  Haft Technology, Inc.
00:C0:6F  Komatsu Ltd.
00:C0:70  Sectra Secure-transmission Ab
00:C0:71  Areanex Communications, Inc.
00:C0:72  Knx Ltd.
00:C0:73  Xedia Corporation
00:C0:74  Toyoda Automatic Loom
00:C0:75  Xante Corporation
00:C0:76  I-data International A-s
00:C0:77  Daewoo Telecom Ltd.
00:C0:78  Computer Systems Engineering
00:C0:79  Fonsys Co.,ltd.
00:C0:7A  Priva B.v.
00:C0:7B  Ascend Communications, Inc.
00:C0:7C  Hightech Information
00:C0:7D  Risc Developments Ltd.
00:C0:7E  Kubota Corporation Electronic
00:C0:7F  Nupon Computing Corp.
00:C0:80  Netstar, Inc.
00:C0:81  Metrodata Ltd.
00:C0:82  Moore Products Co.
00:C0:83  Trace Mountain Products, Inc.
00:C0:84  Data Link Corp. Ltd.
00:C0:85  Electronics For Imaging, Inc.
00:C0:86  The Lynk Corporation
00:C0:87  Uunet Technologies, Inc.
00:C0:88  Ekf Elektronik Gmbh
00:C0:89  Telindus Distribution
00:C0:8A  Lauterbach Datentechnik Gmbh
00:C0:8B  Risq Modular Systems, Inc.
00:C0:8C  Performance Technologies, Inc.
00:C0:8D  Tronix Product Development
00:C0:8E  Network Information Technology
00:C0:8F  Matsushita Electric Works, Ltd
00:C0:90  Praim S.r.l.
00:C0:91  Jabil Circuit, Inc.
00:C0:92  Mennen Medical Inc.
00:C0:93  Alta Research Corp.
00:C0:94  Vmx Inc.
00:C0:95  Znyx
00:C0:96  Tamura Corporation
00:C0:97  Archipel Sa
00:C0:98  Chuntex Electronic Co., Ltd.
00:C0:99  Yoshiki Industrial Co.,ltd.
00:C0:9A  Photonics Corporation
00:C0:9B  Reliance Comm/tec, R-tec
00:C0:9C  Toa Electronic Ltd.
00:C0:9D  Distributed Systems Int'l, Inc
00:C0:9E  Cache Computers, Inc.
00:C0:9F  Quanta Computer, Inc.
00:C0:A0  Advance Micro Research, Inc.
00:C0:A1  Tokyo Denshi Sekei Co.
00:C0:A2  Intermedium A/s
00:C0:A3  Dual Enterprises Corporation
00:C0:A4  Unigraf Oy
00:C0:A5  Dickens Data Systems
00:C0:A6  Exicom Australia Pty. Ltd
00:C0:A7  Seel Ltd.
00:C0:A8  Gvc Corporation
00:C0:A9  Barron Mccann Ltd.
00:C0:AA  Silicon Valley Computer
00:C0:AB  Telco Systems, Inc.
00:C0:AC  Gambit Computer Communications
00:C0:AD  Marben Communication Systems
00:C0:AE  Towercom Co. Inc. Dba Pc House
00:C0:AF  Teklogix Inc.
00:C0:B0  Gcc Technologies,inc.
00:C0:B1  Genius Net Co.
00:C0:B2  Norand Corporation
00:C0:B3  Comstat Datacomm Corporation
00:C0:B4  Myson Technology, Inc.
00:C0:B5  Corporate Network Systems,inc.
00:C0:B6  Snap Appliances, Inc.
00:C0:B7  American Power Conversion Corp
00:C0:B8  Fraser's Hill Ltd.
00:C0:B9  Funk Software, Inc.
00:C0:BA  Netvantage
00:C0:BB  Forval Creative, Inc.
00:C0:BC  Telecom Australia/cssc
00:C0:BD  Inex Technologies, Inc.
00:C0:BE  Alcatel - Sel
00:C0:BF  Technology Concepts, Ltd.
00:C0:C0  Shore Microsystems, Inc.
00:C0:C1  Quad/graphics, Inc.
00:C0:C2  Infinite Networks Ltd.
00:C0:C3  Acuson Computed Sonography
00:C0:C4  Computer Operational
00:C0:C5  Sid Informatica
00:C0:C6  Personal Media Corp.
00:C0:C7  Sparktrum Microsystems, Inc.
00:C0:C8  Micro Byte Pty. Ltd.
00:C0:C9  Elsag Bailey Process
00:C0:CA  Alfa, Inc.
00:C0:CB  Control Technology Corporation
00:C0:CC  Telesciences Co Systems, Inc.
00:C0:CD  Comelta, S.a.
00:C0:CE  Cei Systems & Engineering Pte
00:C0:CF  Imatran Voima Oy
00:C0:D0  Ratoc System Inc.
00:C0:D1  Comtree Technology Corporation
00:C0:D2  Syntellect, Inc.
00:C0:D3  Olympus Image Systems, Inc.
00:C0:D4  Axon Networks, Inc.
00:C0:D5  Quancom Electronic Gmbh
00:C0:D6  J1 Systems, Inc.
00:C0:D7  Taiwan Trading Center Dba
00:C0:D8  Universal Data Systems
00:C0:D9  Quinte Network Confidentiality
00:C0:DA  Nice Systems Ltd.
00:C0:DB  Ipc Corporation (pte) Ltd.
00:C0:DC  Eos Technologies, Inc.
00:C0:DD  Qlogic Corporation
00:C0:DE  Zcomm, Inc.
00:C0:DF  Kye Systems Corp.
00:C0:E0  Dsc Communication Corp.
00:C0:E1  Sonic Solutions
00:C0:E2  Calcomp, Inc.
00:C0:E3  Ositech Communications, Inc.
00:C0:E4  Siemens Building
00:C0:E5  Gespac, S.a.
00:C0:E6  Verilink Corporation
00:C0:E7  Fiberdata Ab
00:C0:E8  Plexcom, Inc.
00:C0:E9  Oak Solutions, Ltd.
00:C0:EA  Array Technology Ltd.
00:C0:EB  Seh Computertechnik Gmbh
00:C0:EC  Dauphin Technology
00:C0:ED  Us Army Electronic
00:C0:EE  Kyocera Corporation
00:C0:EF  Abit Corporation
00:C0:F0  Kingston Technology Corp.
00:C0:F1  Shinko Electric Co., Ltd.
00:C0:F2  Transition Networks
00:C0:F3  Network Communications Corp.
00:C0:F4  Interlink System Co., Ltd.
00:C0:F5  Metacomp, Inc.
00:C0:F6  Celan Technology Inc.
00:C0:F7  Engage Communication, Inc.
00:C0:F8  About Computing Inc.
00:C0:F9  Harris And Jeffries, Inc.
00:C0:FA  Canary Communications, Inc.
00:C0:FB  Advanced Technology Labs
00:C0:FC  Elastic Reality, Inc.
00:C0:FD  Prosum
00:C0:FE  Aptec Computer Systems, Inc.
00:C0:FF  Dot Hill Systems Corporation
00:CB:BD  Cambridge Broadband Ltd.
00:CF:1C  Communication Machinery Corp.
00:D0:00  Ferran Scientific, Inc.
00:D0:01  Vst Technologies, Inc.
00:D0:02  Ditech Corporation
00:D0:03  Comda Enterprises Corp.
00:D0:04  Pentacom Ltd.
00:D0:05  Zhs Zeitmanagementsysteme
00:D0:06  Cisco Systems, Inc.
00:D0:07  Mic Associates, Inc.
00:D0:08  Mactell Corporation
00:D0:09  Hsing Tech. Enterprise Co. Ltd
00:D0:0A  Lanaccess Telecom S.a.
00:D0:0B  Rhk Technology, Inc.
00:D0:0C  Snijder Micro Systems
00:D0:0D  Micromeritics Instrument
00:D0:0E  Pluris, Inc.
00:D0:0F  Speech Design Gmbh
00:D0:10  Convergent Networks, Inc.
00:D0:11  Prism Video, Inc.
00:D0:12  Gateworks Corp.
00:D0:13  Primex Aerospace Company
00:D0:14  Root, Inc.
00:D0:15  Univex Microtechnology Corp.
00:D0:16  Scm Microsystems, Inc.
00:D0:17  Syntech Information Co., Ltd.
00:D0:18  Qwes. Com, Inc.
00:D0:19  Dainippon Screen Corporate
00:D0:1A  Urmet Sud S.p.a.
00:D0:1B  Mimaki Engineering Co., Ltd.
00:D0:1C  Sbs Technologies,
00:D0:1D  Furuno Electric Co., Ltd.
00:D0:1E  Pingtel Corp.
00:D0:1F  Ctam Pty. Ltd.
00:D0:20  Aim System, Inc.
00:D0:21  Regent Electronics Corp.
00:D0:22  Incredible Technologies, Inc.
00:D0:23  Infortrend Technology, Inc.
00:D0:24  Cognex Corporation
00:D0:25  Xrosstech, Inc.
00:D0:26  Hirschmann Austria Gmbh
00:D0:27  Applied Automation, Inc.
00:D0:28  Omneon Video Networks
00:D0:29  Wakefern Food Corporation
00:D0:2A  Flexion Systems
00:D0:2B  Jetcell, Inc.
00:D0:2C  Campbell Scientific, Inc.
00:D0:2D  Ademco
00:D0:2E  Communication Automation Corp.
00:D0:2F  Vlsi Technology Inc.
00:D0:30  Safetran Systems Corp.
00:D0:31  Industrial Logic Corporation
00:D0:32  Yano Electric Co., Ltd.
00:D0:33  Dalian Daxian Network
00:D0:34  Ormec Systems Corp.
00:D0:35  Behavior Tech. Computer Corp.
00:D0:36  Technology Atlanta Corp.
00:D0:37  Philips-dvs-lo Bdr
00:D0:38  Fivemere, Ltd.
00:D0:39  Utilicom, Inc.
00:D0:3A  Zoneworx, Inc.
00:D0:3B  Vision Products Pty. Ltd.
00:D0:3C  Vieo, Inc.
00:D0:3D  Private
00:D0:3E  Rocketchips, Inc.
00:D0:3F  American Communication
00:D0:40  Sysmate Co., Ltd.
00:D0:41  Amigo Technology Co., Ltd.
00:D0:42  Mahlo Gmbh & Co. Ug
00:D0:43  Zonal Retail Data Systems
00:D0:44  Alidian Networks, Inc.
00:D0:45  Kvaser Ab
00:D0:46  Dolby Laboratories, Inc.
00:D0:47  Xn Technologies
00:D0:48  Ecton, Inc.
00:D0:49  Impresstek Co., Ltd.
00:D0:4A  Presence Technology Gmbh
00:D0:4B  La Cie Group S.a.
00:D0:4C  Eurotel Telecom Ltd.
00:D0:4D  Div Of Research & Statistics
00:D0:4E  Logibag
00:D0:4F  Bitronics, Inc.
00:D0:50  Iskratel
00:D0:51  O2 Micro, Inc.
00:D0:52  Ascend Communications, Inc.
00:D0:53  Connected Systems
00:D0:54  Sas Institute Inc.
00:D0:55  Kathrein-werke Kg
00:D0:56  Somat Corporation
00:D0:57  Ultrak, Inc.
00:D0:58  Cisco Systems, Inc.
00:D0:59  Ambit Microsystems Corp.
00:D0:5A  Symbionics, Ltd.
00:D0:5B  Acroloop Motion Control
00:D0:5C  Technotrend Systemtechnik Gmbh
00:D0:5D  Intelliworxx, Inc.
00:D0:5E  Stratabeam Technology, Inc.
00:D0:5F  Valcom, Inc.
00:D0:60  Panasonic European
00:D0:61  Tremon Enterprises Co., Ltd.
00:D0:62  Digigram
00:D0:63  Cisco Systems, Inc.
00:D0:64  Multitel
00:D0:65  Toko Electric
00:D0:66  Wintriss Engineering Corp.
00:D0:67  Campio Communications
00:D0:68  Iwill Corporation
00:D0:69  Technologic Systems
00:D0:6A  Linkup Systems Corporation
00:D0:6B  Sr Telecom Inc.
00:D0:6C  Sharewave, Inc.
00:D0:6D  Acrison, Inc.
00:D0:6E  Trendview Recorders Ltd.
00:D0:6F  Kmc Controls
00:D0:70  Long Well Electronics Corp.
00:D0:71  Echelon Corp.
00:D0:72  Broadlogic
00:D0:73  Acn Advanced Communications
00:D0:74  Taqua Systems, Inc.
00:D0:75  Alaris Medical Systems, Inc.
00:D0:76  Merrill Lynch & Co., Inc.
00:D0:77  Lucent Technologies
00:D0:78  Eltex Of Sweden Ab
00:D0:79  Cisco Systems, Inc.
00:D0:7A  Amaquest Computer Corp.
00:D0:7B  Comcam International Ltd.
00:D0:7C  Koyo Electronics Inc. Co.,ltd.
00:D0:7D  Cosine Communications
00:D0:7E  Keycorp Ltd.
00:D0:7F  Strategy & Technology, Limited
00:D0:80  Exabyte Corporation
00:D0:81  Real Time Devices Usa, Inc.
00:D0:82  Iowave Inc.
00:D0:83  Invertex, Inc.
00:D0:84  Nexcomm Systems, Inc.
00:D0:85  Otis Elevator Company
00:D0:86  Foveon, Inc.
00:D0:87  Microfirst Inc.
00:D0:88  Mainsail Networks, Inc.
00:D0:89  Dynacolor, Inc.
00:D0:8A  Photron Usa
00:D0:8B  Adva Limited
00:D0:8C  Genoa Technology, Inc.
00:D0:8D  Phoenix Group, Inc.
00:D0:8E  Nvision Inc.
00:D0:8F  Ardent Technologies, Inc.
00:D0:90  Cisco Systems, Inc.
00:D0:91  Smartsan Systems, Inc.
00:D0:92  Glenayre Western Multiplex
00:D0:93  Tq - Components Gmbh
00:D0:94  Timeline Vista, Inc.
00:D0:95  Xylan Corporation
00:D0:96  3com Europe Ltd.
00:D0:97  Cisco Systems, Inc.
00:D0:98  Photon Dynamics Canada Inc.
00:D0:99  Elcard Oy
00:D0:9A  Filanet Corporation
00:D0:9B  Spectel Ltd.
00:D0:9C  Kapadia Communications
00:D0:9D  Veris Industries
00:D0:9E  2wire, Inc.
00:D0:9F  Novtek Test Systems
00:D0:A0  Mips Denmark
00:D0:A1  Oskar Vierling Gmbh + Co. Kg
00:D0:A2  Integrated Device
00:D0:A3  Vocal Data, Inc.
00:D0:A4  Alantro Communications
00:D0:A5  American Arium
00:D0:A6  Lanbird Technology Co., Ltd.
00:D0:A7  Tokyo Sokki Kenkyujo Co., Ltd.
00:D0:A8  Network Engines, Inc.
00:D0:A9  Shinano Kenshi Co., Ltd.
00:D0:AA  Chase Communications
00:D0:AB  Deltakabel Telecom Cv
00:D0:AC  Grayson Wireless
00:D0:AD  Tl Industries
00:D0:AE  Oresis Communications, Inc.
00:D0:AF  Cutler-hammer, Inc.
00:D0:B0  Bitswitch Ltd.
00:D0:B1  Omega Electronics Sa
00:D0:B2  Xiotech Corporation
00:D0:B3  Drs Flight Safety And
00:D0:B4  Katsujima Co., Ltd.
00:D0:B5  Ipricot Formerly Dotcom
00:D0:B6  Crescent Networks, Inc.
00:D0:B7  Intel Corporation
00:D0:B8  Iomega Corp.
00:D0:B9  Microtek International, Inc.
00:D0:BA  Cisco Systems, Inc.
00:D0:BB  Cisco Systems, Inc.
00:D0:BC  Cisco Systems, Inc.
00:D0:BD  Sican Gmbh
00:D0:BE  Emutec Inc.
00:D0:BF  Pivotal Technologies
00:D0:C0  Cisco Systems, Inc.
00:D0:C1  Harmonic Data Systems, Ltd.
00:D0:C2  Balthazar Technology Ab
00:D0:C3  Vivid Technology Pte, Ltd.
00:D0:C4  Teratech Corporation
00:D0:C5  Computational Systems, Inc.
00:D0:C6  Thomas & Betts Corp.
00:D0:C7  Pathway, Inc.
00:D0:C8  I/o Consulting A/s
00:D0:C9  Advantech Co., Ltd.
00:D0:CA  Intrinsyc Software Inc.
00:D0:CB  Dasan Co., Ltd.
00:D0:CC  Technologies Lyre Inc.
00:D0:CD  Atan Technology Inc.
00:D0:CE  Asyst Electronic
00:D0:CF  Moreton Bay
00:D0:D0  Zhongxing Telecom Ltd.
00:D0:D1  Sirocco Systems, Inc.
00:D0:D2  Epilog Corporation
00:D0:D3  Cisco Systems, Inc.
00:D0:D4  V-bits, Inc.
00:D0:D5  Grundig Ag
00:D0:D6  Aethra Telecomunicazioni
00:D0:D7  B2c2, Inc.
00:D0:D8  3com Corporation
00:D0:D9  Dedicated Microcomputers
00:D0:DA  Taicom Data Systems Co., Ltd.
00:D0:DB  Mcquay International
00:D0:DC  Modular Mining Systems, Inc.
00:D0:DD  Sunrise Telecom, Inc.
00:D0:DE  Philips Multimedia Network
00:D0:DF  Kuzumi Electronics, Inc.
00:D0:E0  Dooin Electronics Co.
00:D0:E1  Avionitek Israel Inc.
00:D0:E2  Mrt Micro, Inc.
00:D0:E3  Ele-chem Engineering Co., Ltd.
00:D0:E4  Cisco Systems, Inc.
00:D0:E5  Solidum Systems Corp.
00:D0:E6  Ibond Inc.
00:D0:E7  Vcon Telecommunication Ltd.
00:D0:E8  Mac System Co., Ltd.
00:D0:E9  Advantage Century
00:D0:EA  Nextone Communications, Inc.
00:D0:EB  Lightera Networks, Inc.
00:D0:EC  Nakayo Telecommunications, Inc
00:D0:ED  Xiox
00:D0:EE  Dictaphone Corporation
00:D0:EF  Igt
00:D0:F0  Convision Technology Gmbh
00:D0:F1  Sega Enterprises, Ltd.
00:D0:F2  Monterey Networks
00:D0:F3  Solari Di Udine Spa
00:D0:F4  Carinthian Tech Institute
00:D0:F5  Orange Micro, Inc.
00:D0:F6  Alcatel Canada
00:D0:F7  Next Nets Corporation
00:D0:F8  Fujian Star Terminal
00:D0:F9  Acute Communications Corp.
00:D0:FA  Racal Guardata
00:D0:FB  Tek Microsystems, Incorporated
00:D0:FC  Granite Microsystems
00:D0:FD  Optima Tele.com, Inc.
00:D0:FE  Astral Point
00:D0:FF  Cisco Systems, Inc.
00:DD:00  Ungermann-bass Inc.
00:DD:01  Ungermann-bass Inc.
00:DD:02  Ungermann-bass Inc.
00:DD:03  Ungermann-bass Inc.
00:DD:04  Ungermann-bass Inc.
00:DD:05  Ungermann-bass Inc.
00:DD:06  Ungermann-bass Inc.
00:DD:07  Ungermann-bass Inc.
00:DD:08  Ungermann-bass Inc.
00:DD:09  Ungermann-bass Inc.
00:DD:0A  Ungermann-bass Inc.
00:DD:0B  Ungermann-bass Inc.
00:DD:0C  Ungermann-bass Inc.
00:DD:0D  Ungermann-bass Inc.
00:DD:0E  Ungermann-bass Inc.
00:DD:0F  Ungermann-bass Inc.
00:E0:00  Fujitsu, Ltd
00:E0:01  Strand Lighting Limited
00:E0:02  Crossroads Systems, Inc.
00:E0:03  Nokia Wireless Business Commun
00:E0:04  Pmc-sierra, Inc.
00:E0:05  Technical Corp.
00:E0:06  Silicon Integrated Sys. Corp.
00:E0:07  Network Alchemy Ltd.
00:E0:08  Amazing Controls! Inc.
00:E0:09  Marathon Technologies Corp.
00:E0:0A  Diba, Inc.
00:E0:0B  Rooftop Communications Corp.
00:E0:0C  Motorola
00:E0:0D  Radiant Systems
00:E0:0E  Avalon Imaging Systems, Inc.
00:E0:0F  Shanghai Baud Data
00:E0:10  Hess Sb-automatenbau Gmbh
00:E0:11  Uniden San Diego R&d Center, Inc.
00:E0:12  Pluto Technologies International Inc.
00:E0:13  Eastern Electronic Co., Ltd.
00:E0:14  Cisco Systems, Inc.
00:E0:15  Heiwa Corporation
00:E0:16  Rapid City Communications
00:E0:17  Exxact Gmbh
00:E0:18  Asustek Computer Inc.
00:E0:19  Ing. Giordano Elettronica
00:E0:1A  Comtec Systems. Co., Ltd.
00:E0:1B  Sphere Communications, Inc.
00:E0:1C  Mobility Electronicsy
00:E0:1D  Webtv Networks, Inc.
00:E0:1E  Cisco Systems, Inc.
00:E0:1F  Avidia Systems, Inc.
00:E0:20  Tecnomen Oy
00:E0:21  Freegate Corp.
00:E0:22  Medialight, Inc.
00:E0:23  Telrad
00:E0:24  Gadzoox Networks
00:E0:25  Dit Co., Ltd.
00:E0:26  Eastman Kodak Co.
00:E0:27  Dux, Inc.
00:E0:28  Aptix Corporation
00:E0:29  OEM OEM
00:E0:2A  Tandberg Television As
00:E0:2B  Extreme Networks
00:E0:2C  Ast Computer
00:E0:2D  Innomedialogic, Inc.
00:E0:2E  Spc Electronics Corporation
00:E0:2F  Mcns Holdings, L.p.
00:E0:30  Melita International Corp.
00:E0:31  Hagiwara Electric Co., Ltd.
00:E0:32  Misys Financial Systems, Ltd.
00:E0:33  E.e.p.d. Gmbh
00:E0:34  Cisco Systems, Inc.
00:E0:35  Loughborough Sound Images, Plc
00:E0:36  Pioneer Corporation
00:E0:37  Century Corporation
00:E0:38  Proxima Corporation
00:E0:39  Paradyne Corp.
00:E0:3A  Cabletron Systems, Inc.
00:E0:3B  Prominet Corporation
00:E0:3C  Advansys
00:E0:3D  Focon Electronic Systems A/s
00:E0:3E  Alfatech, Inc.
00:E0:3F  Jaton Corporation
00:E0:40  Deskstation Technology, Inc.
00:E0:41  Cspi
00:E0:42  Pacom Systems Ltd.
00:E0:43  Vitalcom
00:E0:44  Lsics Corporation
00:E0:45  Touchwave, Inc.
00:E0:46  Bently Nevada Corp.
00:E0:47  Infocus Systems
00:E0:48  Sdl Communications, Inc.
00:E0:49  Microwi Electronic Gmbh
00:E0:4A  Enhanced Messaging Systems, Inc
00:E0:4B  Jump Industrielle Computertechnik Gmbh
00:E0:4C  Realtek Semiconductor Corp.
00:E0:4D  Internet Initiative Japan, Inc
00:E0:4E  Sanyo Denki Co., Ltd.
00:E0:4F  Cisco Systems, Inc.
00:E0:50  Executone Information Systems, Inc.
00:E0:51  Talx Corporation
00:E0:52  Foundry Networks, Inc.
00:E0:53  Cellport Labs, Inc.
00:E0:54  Kodai Hitec Co., Ltd.
00:E0:55  Ingenieria Electronica Comercial Inelcom S.a.
00:E0:56  Holontech Corporation
00:E0:57  Han Microtelecom. Co., Ltd.
00:E0:58  Phase One Denmark A/s
00:E0:59  Controlled Environments, Ltd.
00:E0:5A  Galea Network Security
00:E0:5B  West End Systems Corp.
00:E0:5C  Matsushita Kotobuki Electronics Industries, Ltd.
00:E0:5D  Unitec Co., Ltd.
00:E0:5E  Japan Aviation Electronics Industry, Ltd.
00:E0:5F  E-net, Inc.
00:E0:60  Sherwood
00:E0:61  Edgepoint Networks, Inc.
00:E0:62  Host Engineering
00:E0:63  Cabletron - Yago Systems, Inc.
00:E0:64  Samsung Electronics
00:E0:65  Optical Access International
00:E0:66  Promax Systems, Inc.
00:E0:67  Eac Automation-consulting Gmbh
00:E0:68  Merrimac Systems Inc.
00:E0:69  Jaycor
00:E0:6A  Kapsch Ag
00:E0:6B  W&g Special Products
00:E0:6C  Aep Systems International Ltd
00:E0:6D  Compuware Corporation
00:E0:6E  Far Systems S.p.a.
00:E0:6F  Terayon Corp.
00:E0:70  Dh Technology
00:E0:71  Epis Microcomputer
00:E0:72  Lynk
00:E0:73  National Amusement Network, Inc.
00:E0:74  Tiernan Communications, Inc.
00:E0:75  Atlas Computer Equipment, Inc.
00:E0:76  Development Concepts, Inc.
00:E0:77  Webgear, Inc.
00:E0:78  Berkeley Networks
00:E0:79  A.t.n.r.
00:E0:7A  Mikrodidakt Ab
00:E0:7B  Bay Networks
00:E0:7C  Mettler-toledo, Inc.
00:E0:7D  Netronix, Inc.
00:E0:7E  Walt Disney Imagineering
00:E0:7F  Logististem S.r.l.
00:E0:80  Control Resources Corporation
00:E0:81  Tyan Computer Corp.
00:E0:82  Anerma
00:E0:83  Jato Technologies, Inc.
00:E0:84  Compulite R&d
00:E0:85  Global Maintech, Inc.
00:E0:86  Cybex Computer Products
00:E0:87  Lecroy - Networking Productions Division
00:E0:88  Ltx Corporation
00:E0:89  Ion Networks, Inc.
00:E0:8A  Gec Avery, Ltd.
00:E0:8B  Qlogic Corp.
00:E0:8C  Neoparadigm Labs, Inc.
00:E0:8D  Pressure Systems, Inc.
00:E0:8E  Utstarcom
00:E0:8F  Cisco Systems, Inc.
00:E0:90  Beckman Lab. Automation Div.
00:E0:91  Lg Electronics, Inc.
00:E0:92  Admtek Incorporated
00:E0:93  Ackfin Networks
00:E0:94  Osai Srl
00:E0:95  Advanced-vision Technolgies Corp.
00:E0:96  Shimadzu Corporation
00:E0:97  Carrier Access Corporation
00:E0:98  Abocom Systems, Inc.
00:E0:99  Samson Ag
00:E0:9A  Positron Industries, Inc.
00:E0:9B  Engage Networks, Inc.
00:E0:9C  Mii
00:E0:9D  Sarnoff Corporation
00:E0:9E  Quantum Corporation
00:E0:9F  Pixel Vision
00:E0:A0  Wiltron Co.
00:E0:A1  Hima Paul Hildebrandt Gmbh Co. Kg
00:E0:A2  Microslate Inc.
00:E0:A3  Cisco Systems, Inc.
00:E0:A4  Esaote S.p.a.
00:E0:A5  Comcore Semiconductor, Inc.
00:E0:A6  Telogy Networks, Inc.
00:E0:A7  Ipc Information Systems, Inc.
00:E0:A8  Sat Gmbh & Co.
00:E0:A9  Funai Electric Co., Ltd.
00:E0:AA  Electrosonic Ltd.
00:E0:AB  Dimat S.a.
00:E0:AC  Midsco, Inc.
00:E0:AD  Ees Technology, Ltd.
00:E0:AE  Xaqti Corporation
00:E0:AF  General Dynamics Information Systems
00:E0:B0  Cisco Systems, Inc.
00:E0:B1  Packet Engines, Inc.
00:E0:B2  Telmax Communications Corp.
00:E0:B3  Etherwan Systems, Inc.
00:E0:B4  Techno Scope Co., Ltd.
00:E0:B5  Ardent Communications Corp.
00:E0:B6  Entrada Networks
00:E0:B7  Pi Group, Ltd.
00:E0:B8  Gateway 2000
00:E0:B9  Byas Systems
00:E0:BA  Berghof Automationstechnik Gmbh
00:E0:BB  Nbx Corporation
00:E0:BC  Symon Communications, Inc.
00:E0:BD  Interface Systems, Inc.
00:E0:BE  Genroco International, Inc.
00:E0:BF  Torrent Networking Technologies Corp.
00:E0:C0  Seiwa Electric Mfg. Co., Ltd.
00:E0:C1  Memorex Telex Japan, Ltd.
00:E0:C2  Necsy S.p.a.
00:E0:C3  Sakai System Development Corp.
00:E0:C4  Horner Electric, Inc.
00:E0:C5  Bcom Electronics Inc.
00:E0:C6  Link2it, L.l.c.
00:E0:C7  Eurotech Srl
00:E0:C8  Virtual Access, Ltd.
00:E0:C9  Automatedlogic Corporation
00:E0:CA  Best Data Products
00:E0:CB  Reson, Inc.
00:E0:CC  Hero Systems, Ltd.
00:E0:CD  Sensis Corporation
00:E0:CE  Arn
00:E0:CF  Integrated Device Technology, Inc.
00:E0:D0  Netspeed, Inc.
00:E0:D1  Telsis Limited
00:E0:D2  Versanet Communications, Inc.
00:E0:D3  Datentechnik Gmbh
00:E0:D4  Excellent Computer
00:E0:D5  Arcxel Technologies, Inc.
00:E0:D6  Computer & Communication Research Lab.
00:E0:D7  Sunshine Electronics, Inc.
00:E0:D8  Lanbit Computer, Inc.
00:E0:D9  Tazmo Co., Ltd.
00:E0:DA  Assured Access Technology, Inc.
00:E0:DB  Viavideo Communications, Inc.
00:E0:DC  Nexware Corp.
00:E0:DD  Zenith Electronics Corporation
00:E0:DE  Datax Nv
00:E0:DF  Ke Kommunikations-electronik
00:E0:E0  Si Electronics, Ltd.
00:E0:E1  G2 Networks, Inc.
00:E0:E2  Innova Corp.
00:E0:E3  Sk-elektronik Gmbh
00:E0:E4  Fanuc Robotics North America, Inc.
00:E0:E5  Cinco Networks, Inc.
00:E0:E6  Incaa Datacom B.v.
00:E0:E7  Raytheon E-systems, Inc.
00:E0:E8  Gretacoder Data Systems Ag
00:E0:E9  Data Labs, Inc.
00:E0:EA  Innovat Communications, Inc.
00:E0:EB  Digicom Systems, Incorporated
00:E0:EC  Celestica Inc.
00:E0:ED  Silicom, Ltd.
00:E0:EE  Marel Hf
00:E0:EF  Dionex
00:E0:F0  Abler Technology, Inc.
00:E0:F1  That Corporation
00:E0:F2  Arlotto Comnet, Inc.
00:E0:F3  Websprint Communications, Inc.
00:E0:F4  Inside Technology A/s
00:E0:F5  Teles Ag
00:E0:F6  Decision Europe
00:E0:F7  Cisco Systems, Inc.
00:E0:F8  Dicna Control Ab
00:E0:F9  Cisco Systems, Inc.
00:E0:FA  Trl Technology, Ltd.
00:E0:FB  Leightronix, Inc.
00:E0:FC  Huawei Technologies Co., Ltd.
00:E0:FD  A-trend Technology Co., Ltd.
00:E0:FE  Cisco Systems, Inc.
00:E0:FF  Security Dynamics Technologies, Inc.
00:E6:D3  Nixdorf Computer Corp.
02:07:01  Racal-datacom
02:1C:7C  Perq Systems Corporation
02:60:86  Logic Replacement Tech. Ltd.
02:60:8C  3com Corporation
02:70:01  Racal-datacom
02:70:B0  M/a-com Inc. Companies
02:70:B3  Data Recall Ltd
02:9D:8E  Cardiac Recorders Inc.
02:AA:3C  Olivetti Telecomm Spa (olteco)
02:BB:01  Octothorpe Corp.
02:C0:8C  3com Corporation
02:CF:1C  Communication Machinery Corp.
02:E6:D3  Nixdorf Computer Corporation
04:0A:E0  Xmit Ag Computer Networks
04:E0:C4  Triumph-adler Ag
08:00:01  Computervision Corporation
08:00:02  Bridge Communications Inc.
08:00:03  Advanced Computer Comm.
08:00:04  Cromemco Incorporated
08:00:05  Symbolics Inc.
08:00:06  Siemens Ag
08:00:07  Apple Computer Inc.
08:00:08  Bolt Beranek And Newman Inc.
08:00:09  Hewlett Packard
08:00:0A  Nestar Systems Incorporated
08:00:0B  Unisys Corporation
08:00:0C  Miklyn Development Co.
08:00:0D  International Computers Ltd.
08:00:0E  Ncr Corporation
08:00:0F  Mitel Corporation
08:00:11  Tektronix Inc.
08:00:12  Bell Atlantic Integrated Syst.
08:00:13  Exxon
08:00:14  Excelan
08:00:15  Stc Business Systems
08:00:16  Barrister Info Sys Corp
08:00:17  National Semiconductor
08:00:18  Pirelli Focom Networks
08:00:19  General Electric Corporation
08:00:1A  Tiara/ 10net
08:00:1B  Data General
08:00:1C  Kdd-kokusai Debnsin Denwa Co.
08:00:1D  Able Communications Inc.
08:00:1E  Apollo Computer Inc.
08:00:1F  Sharp Corporation
08:00:20  Sun Microsystems Inc.
08:00:21  3m Company
08:00:22  Nbi Inc.
08:00:23  Matsuhita Graphic Comm Sys Inc
08:00:24  10net Communications/dca
08:00:25  Control Data
08:00:26  Norsk Data A.s.
08:00:27  Cadmus Computer Systems
08:00:28  Texas Instruments
08:00:29  Megatek Corporation
08:00:2A  Mosaic Technologies Inc.
08:00:2B  Digital Equipment Corporation
08:00:2C  Britton Lee Inc.
08:00:2D  Lan-tec Inc.
08:00:2E  Metaphor Computer Systems
08:00:2F  Prime Computer Inc.
08:00:30  Cern
08:00:31  Little Machines Inc.
08:00:32  Tigan Incorporated
08:00:33  Bausch & Lomb
08:00:34  Filenet Corporation
08:00:35  Microfive Corporation
08:00:36  Intergraph Corporation
08:00:37  Fuji-xerox Co. Ltd.
08:00:38  Cii Honeywell Bull
08:00:39  Spider Systems Limited
08:00:3A  Orcatech Inc.
08:00:3B  Torus Systems Limited
08:00:3C  Schlumberger Well Services
08:00:3D  Cadnetix Corporations
08:00:3E  Codex Corporation
08:00:3F  Fred Koschara Enterprises
08:00:40  Ferranti Computer Sys. Limited
08:00:41  Racal-milgo Information Sys..
08:00:42  Japan Macnics Corp.
08:00:43  Pixel Computer Inc.
08:00:44  David Systems Inc.
08:00:45  Concurrent Computer Corp.
08:00:46  Sony Corporation Ltd.
08:00:47  Sequent Computer Systems Inc.
08:00:48  Eurotherm Gauging Systems
08:00:49  Univation
08:00:4A  Banyan Systems Inc.
08:00:4B  Planning Research Corp.
08:00:4C  Hydra Computer Systems Inc.
08:00:4D  Corvus Systems Inc.
08:00:4E  3com Europe Ltd.
08:00:4F  Cygnet Systems
08:00:50  Daisy Systems Corp.
08:00:51  Experdata
08:00:52  Insystec
08:00:53  Middle East Tech. University
08:00:55  Stanford Telecomm. Inc.
08:00:56  Stanford Linear Accel. Center
08:00:57  Evans & Sutherland
08:00:58  Systems Concepts
08:00:59  A/s Mycron
08:00:5A  Ibm Corporation
08:00:5B  Vta Technologies Inc.
08:00:5C  Four Phase Systems
08:00:5D  Gould Inc.
08:00:5E  Counterpoint Computer Inc.
08:00:5F  Saber Technology Corp.
08:00:60  Industrial Networking Inc.
08:00:61  Jarogate Ltd.
08:00:62  General Dynamics
08:00:63  Plessey
08:00:64  Autophon Ag
08:00:65  Genrad Inc.
08:00:66  Agfa Corporation
08:00:67  Comdesign
08:00:68  Ridge Computers
08:00:69  Silicon Graphics Inc.
08:00:6A  Att Bell Laboratories
08:00:6B  Accel Technologies Inc.
08:00:6C  Suntek Technology Int'l
08:00:6D  Whitechapel Computer Works
08:00:6E  Masscomp
08:00:6F  Philips Apeldoorn B.v.
08:00:70  Mitsubishi Electric Corp.
08:00:71  Matra (dsie)
08:00:72  Xerox Corp Univ Grant Program
08:00:73  Tecmar Inc.
08:00:74  Casio Computer Co. Ltd.
08:00:75  Dansk Data Electronik
08:00:76  Pc Lan Technologies
08:00:77  Tsl Communications Ltd.
08:00:78  Accell Corporation
08:00:79  The Droid Works
08:00:7A  Indata
08:00:7B  Sanyo Electric Co. Ltd.
08:00:7C  Vitalink Communications Corp.
08:00:7E  Amalgamated Wireless(aus) Ltd
08:00:7F  Carnegie-mellon University
08:00:80  Aes Data Inc.
08:00:81  Astech Inc.
08:00:82  Veritas Software
08:00:83  Seiko Instrum. And Electronics
08:00:84  Tomen Electronics Corp.
08:00:85  Elxsi
08:00:86  Imagen Corporation
08:00:87  Xyplex
08:00:88  Mcdata Corporation
08:00:89  Kinetics
08:00:8A  Performance Technology
08:00:8B  Pyramid Technology Corp.
08:00:8C  Network Research Corporation
08:00:8D  Xyvision Inc.
08:00:8E  Tandem Computers
08:00:8F  Chipcom Corporation
08:00:90  Sonoma Systems
08:14:43  Unibrain S.a.
08:BB:CC  Ak-nord Edv Vertriebsges. Mbh
10:00:00  Private
10:00:5A  Ibm Corporation
10:00:E8  National Semiconductor
11:00:AA  Private
80:00:10  Att Bell Laboratories
A0:6A:00  Verilink Corporation
AA:00:00  Digital Equipment Corporation
AA:00:01  Digital Equipment Corporation
AA:00:02  Digital Equipment Corporation
AA:00:03  Digital Equipment Corporation
AA:00:04  Digital Equipment Corporation
