FIND_PATH(RTMP_INCLUDE_DIR librtmp/rtmp.h)
FIND_LIBRARY(RTMP_LIBRARIES rtmp)

IF(RTMP_INCLUDE_DIR AND RTMP_LIBRARIES)
   SET(RTMP_FOUND TRUE)
ENDIF(RTMP_INCLUDE_DIR AND RTMP_LIBRARIES)

IF(RTMP_FOUND)
   MESSAGE(STATUS "Found rtmp includes:	${RTMP_INCLUDE_DIR}/rtmp.h")
   MESSAGE(STATUS "Found rtmp library: ${RTMP_LIBRARIES}")
ELSE(RTMP_FOUND)
   MESSAGE(FATAL_ERROR "Could NOT find rtmp development files")
ENDIF(RTMP_FOUND)
